// Copyright 2025 Bloxide, all rights reserved
//! Integration tests for bloxide-codegen.

use bloxide_codegen::schema::{BloxConfig, SystemConfig};
use bloxide_codegen::{generate_all, generate_from_toml};

#[test]
fn test_parse_counter_messages_toml() {
    let toml = r#"
[[messages]]
name = "CounterMsg"
visibility = "pub"

[[messages.variants]]
name = "Tick"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let messages = config.messages.expect("messages section missing");
    assert_eq!(messages.len(), 1);
    assert_eq!(messages[0].name, "CounterMsg");
    assert_eq!(messages[0].variants.len(), 1);
    assert_eq!(messages[0].variants[0].name, "Tick");
    assert!(messages[0].variants[0].fields.is_empty());
}

#[test]
fn test_generate_counter_messages() {
    let toml = r#"
[[messages]]
name = "CounterMsg"
visibility = "pub"
copy = true

[[messages.variants]]
name = "Tick"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-messages").expect("generate failed");

    let msg_file = files
        .iter()
        .find(|(n, _)| n == "messages_countermsg.rs")
        .expect("messages file missing");
    let (_name, content) = msg_file;

    // Header
    assert!(content.contains("// Auto-generated by bloxide-codegen. Do not edit manually."));

    // Unit struct for empty fields
    assert!(content.contains("pub struct Tick;"));

    // Enum with wrapper variant
    assert!(content.contains("pub enum CounterMsg {"));
    assert!(content.contains("Tick(Tick),"));

    // Derives — Copy is present because copy = true
    assert!(content.contains("#[derive(Debug, Clone, Copy)]"));

    // message_name method
    assert!(content.contains("pub fn message_name(&self) -> &'static str {"));
    assert!(content.contains("CounterMsg::Tick(..) => \"Tick\""));
}

#[test]
fn test_generate_messages_no_copy_by_default() {
    let toml = r#"
[[messages]]
name = "CounterMsg"
visibility = "pub"

[[messages.variants]]
name = "Tick"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-messages").expect("generate failed");

    let msg_file = files
        .iter()
        .find(|(n, _)| n == "messages_countermsg.rs")
        .expect("messages file missing");
    let (_name, content) = msg_file;

    // Default: Debug + Clone, but NOT Copy in the derive attribute
    assert!(content.contains("Debug"));
    assert!(content.contains("Clone"));
    assert!(!content.contains("#[derive(Debug, Clone, Copy)]"));
}

#[test]
fn test_generate_ping_pong_messages() {
    let toml = r#"
[[messages]]
name = "PingPongMsg"
visibility = "pub"
copy = true

[[messages.variants]]
name = "Ping"
[[messages.variants.fields]]
name = "round"
ty = "u32"

[[messages.variants]]
name = "Pong"
[[messages.variants.fields]]
name = "round"
ty = "u32"

[[messages.variants]]
name = "Resume"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "ping-pong-messages").expect("generate failed");

    let msg_file = files
        .iter()
        .find(|(n, _)| n == "messages_pingpongmsg.rs")
        .expect("messages file missing");
    let (_name, content) = msg_file;

    // Named field structs
    assert!(content.contains("pub struct Ping {"));
    assert!(content.contains("pub round: u32,"));
    assert!(content.contains("pub struct Pong {"));
    assert!(content.contains("pub struct Resume;"));

    // Enum
    assert!(content.contains("pub enum PingPongMsg {"));
    assert!(content.contains("Ping(Ping),"));
    assert!(content.contains("Pong(Pong),"));
    assert!(content.contains("Resume(Resume),"));

    // message_name match arms
    assert!(content.contains("PingPongMsg::Ping(..) => \"Ping\""));
    assert!(content.contains("PingPongMsg::Pong(..) => \"Pong\""));
    assert!(content.contains("PingPongMsg::Resume(..) => \"Resume\""));
}

#[test]
fn test_generate_counter_event() {
    let toml = r#"
[actor]
name = "Counter"

[event]
name = "CounterEvent"

[[event.mailboxes]]
variant = "Msg"
message = "CounterMsg"
message_path = "counter_messages::CounterMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    // Imports
    assert!(content.contains("use ::bloxide_core::messaging::Envelope;"));

    // Enum definition
    assert!(content.contains("pub enum CounterEvent {"));
    assert!(content.contains("Lifecycle("));
    assert!(content.contains("Msg(Envelope<counter_messages::CounterMsg>),"));

    // From impls
    assert!(content.contains(
        "impl ::core::convert::From<Envelope<counter_messages::CounterMsg>> for CounterEvent"
    ));
    assert!(
        content.contains("impl ::core::convert::From<::bloxide_core::lifecycle::LifecycleCommand>")
    );

    // EventTag
    assert!(content.contains("impl ::bloxide_core::event_tag::EventTag for CounterEvent"));
    assert!(content.contains("Self::Lifecycle(..) => ::bloxide_core::event_tag::LIFECYCLE_TAG"));
    assert!(content.contains("Self::Msg(..) => 0u8"));

    // LifecycleEvent
    assert!(content.contains("impl ::bloxide_core::event_tag::LifecycleEvent for CounterEvent"));
    assert!(content.contains("fn as_lifecycle_command("));

    // Tag constants
    assert!(content.contains("pub const MSG_TAG: u8 = 0u8;"));

    // Accessor methods
    assert!(content.contains("pub fn msg_envelope("));
    assert!(content.contains("pub fn msg_payload("));

    // Lifecycle helpers
    assert!(content.contains("pub fn start() -> Self"));
    assert!(content.contains("pub fn reset() -> Self"));
    assert!(content.contains("pub fn stop() -> Self"));
    assert!(content.contains("pub fn ping() -> Self"));
}

#[test]
fn test_generate_event_with_custom_derives() {
    let toml = r#"
[actor]
name = "Counter"

[event]
name = "CounterEvent"
derives = ["Debug", "Clone", "PartialEq"]

[[event.mailboxes]]
variant = "Msg"
message = "CounterMsg"
message_path = "counter_messages::CounterMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    // All three custom derives should appear
    assert!(content.contains("#[derive(Debug, Clone, PartialEq)]"));
}

#[test]
fn test_generate_event_with_empty_derives() {
    let toml = r#"
[actor]
name = "Worker"

[event]
name = "WorkerEvent"
generics = "<R: BloxRuntime>"
derives = []

[[event.mailboxes]]
variant = "Msg"
message = "WorkerMsg"
message_path = "pool_messages::WorkerMsg"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "worker-blox").expect("generate failed");

    let events_file = files
        .iter()
        .find(|(n, _)| n == "events.rs")
        .expect("events.rs missing");
    let content = &events_file.1;

    // No derive attribute at all
    assert!(!content.contains("#[derive"));
    assert!(content.contains("pub enum WorkerEvent"));
}

#[test]
fn test_generate_counter_topology() {
    let toml = r#"
[actor]
name = "Counter"

[event]
name = "CounterEvent"

[[event.mailboxes]]
variant = "Msg"
message = "CounterMsg"
message_path = "counter_messages::CounterMsg"

[context]
name = "CounterCtx"
generics = "<R: BloxRuntime>"

[topology]

[[topology.states]]
name = "Ready"

[[topology.states]]
name = "Done"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let topo_file = files
        .iter()
        .find(|(n, _)| n == "topology.rs")
        .expect("topology.rs missing");
    let content = &topo_file.1;

    // Enum
    assert!(content.contains("pub enum CounterState {"));
    assert!(content.contains("Ready = 0u8,"));
    assert!(content.contains("Done = 1u8,"));
    assert!(content.contains("#[repr(u8)]"));

    // StateTopology impl
    assert!(content.contains("impl ::bloxide_core::topology::StateTopology for CounterState"));
    assert!(content.contains("const STATE_COUNT: usize = 2usize;"));

    // parent() — all top-level => None
    assert!(content.contains("fn parent(self) -> ::core::option::Option<Self>"));

    // is_leaf() — no composites => all true
    assert!(content.contains("fn is_leaf(self) -> bool"));

    // path() — empty static arrays for top-level states
    assert!(content.contains("fn path(self) -> &'static [Self]"));

    // as_index()
    assert!(content.contains("fn as_index(self) -> usize"));

    // Handler table macro
    assert!(content.contains("macro_rules! counter_state_handler_table {"));
    assert!(content.contains("READY_FNS"));
    assert!(content.contains("DONE_FNS"));
}

#[test]
fn test_generate_composite_topology() {
    let toml = r#"
[actor]
name = "Ping"

[topology]

[[topology.states]]
name = "Operating"
composite = true

[[topology.states]]
name = "Active"
parent = "Operating"

[[topology.states]]
name = "Paused"
parent = "Operating"

[[topology.states]]
name = "Done"

[[topology.states]]
name = "Error"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "ping-blox").expect("generate failed");

    let topo_file = files
        .iter()
        .find(|(n, _)| n == "topology.rs")
        .expect("topology.rs missing");
    let content = &topo_file.1;

    // Enum
    assert!(content.contains("pub enum PingState {"));

    // Operating is composite => not leaf
    assert!(content.contains("Self::Operating => false"));
    // Active is leaf
    assert!(content.contains("Self::Active => true"));
    // Paused is leaf
    assert!(content.contains("Self::Paused => true"));

    // Parent relationships
    assert!(content.contains("Self::Active => ::core::option::Option::Some(Self::Operating)"));
    assert!(content.contains("Self::Paused => ::core::option::Option::Some(Self::Operating)"));

    // Path static arrays for children include parent
    assert!(content.contains("static __PATH_ACTIVE"));
    assert!(content.contains("static __PATH_PAUSED"));
}

#[test]
fn test_generate_from_toml_roundtrip() {
    let toml = r#"
[actor]
name = "TestActor"

[[messages]]
name = "TestMsg"
visibility = "pub"

[[messages.variants]]
name = "Hello"
[[messages.variants.fields]]
name = "count"
ty = "u32"

[event]
name = "TestEvent"

[[event.mailboxes]]
variant = "Msg"
message = "TestMsg"
message_path = "test_messages::TestMsg"

[topology]

[[topology.states]]
name = "StateA"
"#;

    let tmp_dir = std::env::temp_dir().join("bloxide_codegen_test");
    std::fs::create_dir_all(&tmp_dir).expect("create dir");
    let toml_path = tmp_dir.join("blox.toml");
    std::fs::write(&toml_path, toml).expect("write toml");

    let files = generate_from_toml(&toml_path).expect("generate from toml failed");

    // cleanup
    let _ = std::fs::remove_dir_all(&tmp_dir);

    let names: Vec<_> = files.iter().map(|(n, _)| n.clone()).collect();
    assert!(names.contains(&"messages_testmsg.rs".to_string()));
    assert!(names.contains(&"events.rs".to_string()));
    assert!(names.contains(&"topology.rs".to_string()));
}

#[test]
fn test_cycle_detection() {
    let toml = r#"
[topology]

[[topology.states]]
name = "A"
parent = "B"

[[topology.states]]
name = "B"
parent = "A"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let result = generate_all(&config, "test");
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("cycle detected"));
}

#[test]
fn test_unknown_parent() {
    let toml = r#"
[topology]

[[topology.states]]
name = "A"
parent = "NonExistent"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let result = generate_all(&config, "test");
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("unknown parent"));
}

#[test]
fn test_generate_counter_ctx() {
    let toml = r#"
[actor]
name = "Counter"

[context]
name = "CounterCtx"

[[context.fields]]
name = "count"
type = "u32"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");
    let ctx_file = files
        .iter()
        .find(|(n, _)| n == "ctx.rs")
        .expect("ctx.rs missing");
    let content = &ctx_file.1;

    // Plain struct — no #[derive(BloxCtx)], no behavior field, no delegate macros.
    assert!(content.contains("pub struct CounterCtx"));
    assert!(content.contains("pub self_id: ::bloxide_core::ActorId"));
    assert!(content.contains("pub fn new(self_id: ::bloxide_core::ActorId) -> Self"));
}

#[test]
fn test_generate_ping_ctx() {
    let toml = r#"
[actor]
name = "Ping"

[context]
name = "PingCtx"
generics = "<R: BloxRuntime>"

[[context.uses]]
field = "peer_ref"
field_type = "ActorRef<PingPongMsg, R>"
role = "ctor"

[[context.uses]]
field = "self_ref"
field_type = "ActorRef<PingPongMsg, R>"
role = "ctor"

[[context.uses]]
field = "timer_ref"
field_type = "ActorRef<TimerCommand, R>"
role = "ctor"

[[context.fields]]
name = "current_timer"
type = "Option<TimerId>"

[[context.fields]]
name = "round"
type = "u32"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "ping-blox").expect("generate failed");

    let ctx_file = files
        .iter()
        .find(|(n, _)| n == "ctx.rs")
        .expect("ctx.rs missing");
    let content = &ctx_file.1;

    // Plain struct — no #[derive(BloxCtx)], no delegate macros, no behavior field.
    assert!(content.contains("pub struct PingCtx<R: BloxRuntime>"));
    assert!(content.contains("use ::bloxide_core::{capability::BloxRuntime, messaging::ActorRef}"));
    // Fields from uses (role = "ctor" → constructor params)
    assert!(content.contains("pub peer_ref: ActorRef<PingPongMsg, R>"));
    assert!(content.contains("pub self_ref: ActorRef<PingPongMsg, R>"));
    assert!(content.contains("pub timer_ref: ActorRef<TimerCommand, R>"));
    assert!(content.contains("pub self_id: ::bloxide_core::ActorId"));
    // Constructor takes ctor fields, zero-inits state fields
    assert!(content.contains("pub fn new("));
}

#[test]
fn test_generate_ctx_generics_passthrough() {
    let toml = r#"
[actor]
name = "Counter"

[context]
name = "CounterCtx"
generics = "<R: BloxRuntime>"

[[context.fields]]
name = "count"
type = "u32"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let ctx_file = files
        .iter()
        .find(|(n, _)| n == "ctx.rs")
        .expect("ctx.rs missing");
    let content = &ctx_file.1;

    // The free-form generics string is passed through verbatim.
    assert!(content.contains("pub struct CounterCtx<R: BloxRuntime>"));
    assert!(content.contains("pub self_id: ::bloxide_core::ActorId"));
}

#[test]
fn test_generate_ctx_uses_single_field_ctor() {
    let toml = r#"
[actor]
name = "Ping"

[context]
name = "PingCtx"
generics = "<R: BloxRuntime>"

[[context.uses]]
field = "peer_ref"
field_type = "ActorRef<PingPongMsg, R>"
role = "ctor"

[[context.uses]]
field = "self_ref"
field_type = "ActorRef<PingPongMsg, R>"
role = "ctor"

[[context.fields]]
name = "round"
type = "u32"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "ping-blox").expect("generate failed");
    let ctx_file = files
        .iter()
        .find(|(n, _)| n == "ctx.rs")
        .expect("ctx.rs missing");
    let content = &ctx_file.1;

    // Plain struct — no #[derive(BloxCtx)], no #[provides], no delegate macros.
    assert!(content.contains("pub struct PingCtx<R: BloxRuntime>"));
    assert!(content.contains("pub self_id: ::bloxide_core::ActorId"));

    // Single-field uses with role = "ctor" → constructor params
    assert!(content.contains("pub peer_ref: ActorRef<PingPongMsg, R>"));
    assert!(content.contains("pub self_ref: ActorRef<PingPongMsg, R>"));

    // Framework imports (auto-detected from field types containing ActorRef + BloxRuntime)
    assert!(content.contains("use ::bloxide_core::{capability::BloxRuntime, messaging::ActorRef}"));

    // Constructor takes ctor fields
    assert!(content.contains("pub fn new("));
}

#[test]
fn test_generate_spec_skeleton_counter() {
    let toml = r#"
[actor]
name = "Counter"

[event]
name = "CounterEvent"

[[event.mailboxes]]
variant = "Msg"
message = "CounterMsg"
message_path = "counter_messages::CounterMsg"

[context]
name = "CounterCtx"

[[context.fields]]
name = "count"
type = "u32"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.states]]
name = "Done"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    assert!(content.contains("pub struct CounterSpec"));
    assert!(content.contains("MachineSpec"));
    assert!(content.contains("for CounterSpec"));
    assert!(content.contains("type State = CounterState"));
    assert!(content.contains("type Event = CounterEvent"));
    assert!(content.contains("counter_messages::CounterMsg"));
    assert!(content.contains("counter_state_handler_table"));
    assert!(content.contains("CounterState::Ready"));
    assert!(content.contains("fn on_init_entry"));
}

#[test]
fn test_generate_spec_skeleton_ping() {
    let toml = r#"
[actor]
name = "Ping"

[event]
name = "PingEvent"

[[event.mailboxes]]
variant = "Msg"
message = "PingPongMsg"
message_path = "ping_pong_messages::PingPongMsg"

[context]
name = "PingCtx"
generics = "<R: BloxRuntime>"

[[context.uses]]
field = "peer_ref"
field_type = "ActorRef<PingPongMsg, R>"
role = "ctor"

[[context.fields]]
name = "current_timer"
type = "Option<TimerId>"

[[context.fields]]
name = "round"
type = "u32"

[topology]

[[topology.states]]
name = "Operating"
composite = true

[[topology.states]]
name = "Active"
parent = "Operating"
initial = true

[[topology.states]]
name = "Paused"
parent = "Operating"

[[topology.states]]
name = "Error"
error = true
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "ping-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    assert!(content.contains("pub struct PingSpec"));
    assert!(content.contains("MachineSpec"));
    assert!(content.contains("for PingSpec"));
    assert!(content.contains("type State = PingState"));
    assert!(content.contains("PingState::Active"));
    assert!(content.contains("fn is_error"));
    assert!(content.contains("PingState::Error"));
    assert!(content.contains("ping_state_handler_table"));
}

#[test]
fn test_state_flags_in_topology() {
    let toml = r#"
[actor]
name = "Test"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.states]]
name = "Done"

[[topology.states]]
name = "Error"
error = true
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let topo = config.topology.unwrap();
    assert_eq!(topo.states[0].initial, Some(true));
}

#[test]
fn test_no_context_no_spec_skeleton() {
    let toml = r#"
[actor]
name = "Minimal"

[topology]

[[topology.states]]
name = "Idle"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "minimal-blox").expect("generate failed");

    assert!(files.iter().all(|(n, _)| n != "ctx.rs"));
    assert!(files.iter().all(|(n, _)| n != "spec_skeleton.rs"));
}

#[test]
fn test_declarative_transitions_simple_stay() {
    let toml = r#"
[actor]
name = "Pong"

[event]
name = "PongEvent"

[[event.mailboxes]]
variant = "Msg"
message = "PingPongMsg"
message_path = "ping_pong_messages::PingPongMsg"

[context]
name = "PongCtx"
generics = "<R: BloxRuntime>"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.transitions]]
state = "Ready"
event = "PingPongMsg::Ping(_)"
target = "stay"
actions = ["reply_pong_action"]
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "pong-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    // StateFns constant generated
    assert!(content.contains("READY_FNS"));
    assert!(content.contains("StateFns"));
    // Raw StateRule struct literal emitted by codegen
    assert!(content.contains("StateRule"));
    // Event pattern in matches closure
    assert!(content.contains("PingPongMsg::Ping"));
    // Decision::Stay
    assert!(content.contains("Decision::Stay"));
    // Action function
    assert!(content.contains("reply_pong_action"));
    // Handler table array
    assert!(content.contains("HANDLER_TABLE"));
}

#[test]
fn test_declarative_transitions_with_guard() {
    let toml = r#"
[actor]
name = "Counter"

[event]
name = "CounterEvent"

[[event.mailboxes]]
variant = "Msg"
message = "CounterMsg"
message_path = "counter_messages::CounterMsg"

[context]
name = "CounterCtx"
generics = "<R: BloxRuntime>"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.states]]
name = "Done"

[[topology.transitions]]
state = "Ready"
event = "CounterMsg::Tick(_)"
target = "stay"
actions = ["count_tick"]

[[topology.transitions]]
state = "Ready"
event = "CounterMsg::Tick(_)"
target = "Done"
actions = ["count_tick"]

[[topology.transitions.guards]]
condition = "ctx.count() >= 2"
target = "Done"

[[topology.transitions.guards]]
condition = "ctx.count() < 2"
target = "stay"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "counter-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    // Decision chain generated as if/else-if/else
    assert!(content.contains("ctx.count() >= 2"));
    assert!(content.contains("ctx.count() < 2"));
    // State targets in Decision::Transition
    assert!(content.contains("CounterState::Done"));
    // Decision::Stay for fallback
    assert!(content.contains("Decision::Stay"));
    // Raw StateRule struct literal emitted by codegen
    assert!(content.contains("StateRule"));
}

#[test]
fn test_declarative_entry_exit() {
    let toml = r#"
[actor]
name = "Worker"

[event]
name = "WorkerEvent"

[[event.mailboxes]]
variant = "Msg"
message = "WorkerMsg"
message_path = "pool_messages::WorkerMsg"

[context]
name = "WorkerCtx"
generics = "<R: BloxRuntime>"

[topology]

[[topology.states]]
name = "Waiting"
initial = true

[[topology.states]]
name = "Done"

[[topology.entry]]
state = "Waiting"
actions = ["log_waiting"]

[[topology.exit]]
state = "Waiting"
actions = ["cleanup"]

[[topology.transitions]]
state = "Waiting"
event = "WorkerMsg::DoWork(_)"
target = "Done"
actions = ["process_work"]
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "worker-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    // Entry/exit actions in StateFns
    assert!(content.contains("log_waiting"));
    assert!(content.contains("cleanup"));
    assert!(content.contains("on_entry"));
    assert!(content.contains("on_exit"));
}

#[test]
fn test_declarative_transition_with_transition_target() {
    let toml = r#"
[actor]
name = "Pool"

[event]
name = "PoolEvent"

[[event.mailboxes]]
variant = "Msg"
message = "PoolMsg"
message_path = "pool_messages::PoolMsg"

[context]
name = "PoolCtx"
generics = "<R: BloxRuntime>"

[topology]

[[topology.states]]
name = "Idle"
initial = true

[[topology.states]]
name = "Active"

[[topology.states]]
name = "AllDone"

[[topology.transitions]]
state = "Idle"
event = "PoolMsg::SpawnWorker(_)"
target = "Active"
actions = ["handle_spawn_worker"]

[[topology.transitions]]
state = "Active"
event = "PoolMsg::WorkDone(_)"
target = "stay"
actions = ["handle_work_done"]

[[topology.transitions.guards]]
condition = "ctx.pending == 0"
target = "AllDone"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "pool-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    // transition targets (not stay/reset/fail)
    // Decision::Transition with LeafState::new
    assert!(content.contains("Decision::Transition"));
    assert!(content.contains("PoolState::Active"));
    assert!(content.contains("PoolState::AllDone"));
}

#[test]
fn test_declarative_transition_unknown_state() {
    let toml = r#"
[actor]
name = "Test"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.transitions]]
state = "Ready"
event = "Msg::A(_)"
target = "NonExistentState"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let result = generate_all(&config, "test-blox");
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("unknown target state"));
}

#[test]
fn test_declarative_transition_unknown_handling_state() {
    let toml = r#"
[actor]
name = "Test"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.transitions]]
state = "NonExistent"
event = "Msg::A(_)"
target = "stay"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let result = generate_all(&config, "test-blox");
    assert!(result.is_err());
    let err = result.unwrap_err().to_string();
    assert!(err.contains("unknown state"));
}

#[test]
fn test_declarative_transitions_empty_for_state() {
    let toml = r#"
[actor]
name = "Test"

[event]
name = "TestEvent"

[[event.mailboxes]]
variant = "Msg"
message = "TestMsg"
message_path = "test_messages::TestMsg"

[context]
name = "TestCtx"
generics = "<R: BloxRuntime>"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.states]]
name = "Done"

[[topology.transitions]]
state = "Ready"
event = "Msg::Go(_)"
target = "Done"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "test-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    // Done state should have empty transitions: &[]
    assert!(content.contains("DONE_FNS"));
    // The Done StateFns should have empty transitions
    // (both states get StateFns, but Done has no transition entries)
    assert!(content.contains("transitions: &[]"));
}

#[test]
fn test_parse_context_uses_single_field_ctor() {
    let toml = r#"
[actor]
name = "Ping"

[context]
name = "PingCtx"
generics = "<R: BloxRuntime>"

[[context.uses]]
field = "peer_ref"
field_type = "ActorRef<PingPongMsg, R>"
role = "ctor"

[[context.uses]]
field = "self_ref"
field_type = "ActorRef<PingPongMsg, R>"
role = "ctor"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let ctx = config.context.expect("context section missing");
    assert_eq!(ctx.uses.len(), 2);

    let u0 = &ctx.uses[0];
    assert_eq!(u0.field.as_deref(), Some("peer_ref"));
    assert_eq!(u0.field_type.as_deref(), Some("ActorRef<PingPongMsg, R>"));
    assert_eq!(u0.role.as_deref(), Some("ctor"));
    assert!(u0.fields.is_empty());

    let u1 = &ctx.uses[1];
    assert_eq!(u1.field.as_deref(), Some("self_ref"));
}

#[test]
fn test_parse_context_uses_empty_default() {
    // When [[context.uses]] is absent, uses should default to empty vec.
    let toml = r#"
[actor]
name = "Counter"

[context]
name = "CounterCtx"

"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let ctx = config.context.expect("context section missing");
    assert!(ctx.uses.is_empty());
}

// test_parse_context_field_role removed — [[context.fields]] no longer exists

#[test]
fn test_declarative_reset_fail_targets() {
    let toml = r#"
[actor]
name = "Test"

[event]
name = "TestEvent"

[[event.mailboxes]]
variant = "Msg"
message = "TestMsg"
message_path = "test_messages::TestMsg"

[context]
name = "TestCtx"
generics = "<R: BloxRuntime>"

[topology]

[[topology.states]]
name = "Ready"
initial = true

[[topology.states]]
name = "Error"
error = true

[[topology.transitions]]
state = "Ready"
event = "Msg::Reset(_)"
target = "reset"

[[topology.transitions]]
state = "Ready"
event = "Msg::Fail(_)"
target = "fail"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "test-blox").expect("generate failed");

    let spec_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &spec_file.1;

    assert!(content.contains("Decision::Reset"));
    assert!(content.contains("Decision::Fail"));
}

// ---------------------------------------------------------------------------
// system.toml — wiring manifest schema tests
// ---------------------------------------------------------------------------

#[test]
fn test_parse_system_toml_minimal() {
    // Minimal system.toml — just [system] with a runtime, no actors or supervision.
    let toml = r#"
[system]
runtime = "tokio"
"#;

    let config: SystemConfig = toml::from_str(toml).expect("parse failed");
    assert_eq!(config.system.runtime, "tokio");
    assert!(config.actors.is_empty());
    assert!(config.supervision.is_empty());
}

#[test]
fn test_parse_system_toml_ping_pong() {
    // Full ping-pong wiring manifest matching spec 19.
    let toml = r#"
[system]
runtime = "tokio"

[[actors]]
name = "timer"
blox = "bloxide-timer"

[[actors]]
name = "ping"
blox = "ping-blox"

  [actors.inject]
  self_ref = { source = "self" }
  peer_ref = { source = "actor", actor = "pong" }
  timer_ref = { source = "actor", actor = "timer" }

[[actors]]
name = "pong"
blox = "pong-blox"

  [actors.inject]
  self_ref = { source = "self" }
  peer_ref = { source = "actor", actor = "ping" }

[[supervision]]
supervisor = "bloxide-supervisor"
strategy = "when_any_done"
children = ["ping", "pong"]

  [supervision.policies]
  ping = { restart = { max = 1 } }
  pong = { stop = true }
"#;

    let config: SystemConfig = toml::from_str(toml).expect("parse failed");
    assert_eq!(config.system.runtime, "tokio");
    assert_eq!(config.actors.len(), 3);
    assert_eq!(config.supervision.len(), 1);

    // Timer actor — no inject
    let timer = &config.actors[0];
    assert_eq!(timer.name, "timer");
    assert_eq!(timer.blox, "bloxide-timer");
    assert!(timer.inject.is_empty());

    // Ping actor — has 3 inject entries
    let ping = &config.actors[1];
    assert_eq!(ping.name, "ping");
    assert_eq!(ping.blox, "ping-blox");
    assert_eq!(ping.inject.len(), 3);

    let self_ref = ping.inject.get("self_ref").expect("self_ref missing");
    assert_eq!(self_ref.source, "self");
    assert!(self_ref.actor.is_none());

    let peer_ref = ping.inject.get("peer_ref").expect("peer_ref missing");
    assert_eq!(peer_ref.source, "actor");
    assert_eq!(peer_ref.actor.as_deref(), Some("pong"));

    let timer_ref = ping.inject.get("timer_ref").expect("timer_ref missing");
    assert_eq!(timer_ref.source, "actor");
    assert_eq!(timer_ref.actor.as_deref(), Some("timer"));

    // Pong actor — 2 inject entries
    let pong = &config.actors[2];
    assert_eq!(pong.name, "pong");
    assert_eq!(pong.inject.len(), 2);
    let pong_peer = pong.inject.get("peer_ref").expect("pong peer_ref missing");
    assert_eq!(pong_peer.actor.as_deref(), Some("ping"));

    // Supervision
    let sup = &config.supervision[0];
    assert_eq!(sup.supervisor, "bloxide-supervisor");
    assert_eq!(sup.strategy, "when_any_done");
    assert_eq!(sup.children, vec!["ping", "pong"]);
    assert_eq!(sup.policies.len(), 2);

    let ping_policy = sup.policies.get("ping").expect("ping policy missing");
    let restart = ping_policy.restart.as_ref().expect("restart missing");
    assert_eq!(restart.max, 1);
    assert!(ping_policy.stop.is_none());

    let pong_policy = sup.policies.get("pong").expect("pong policy missing");
    assert_eq!(pong_policy.stop, Some(true));
    assert!(pong_policy.restart.is_none());
}

#[test]
fn test_parse_system_toml_multi_mailbox_actor() {
    // Worker actor with a secondary-channel inject (multi-mailbox actors use
    // `source = "self_secondary", index = N`).
    let toml = r#"
[system]
runtime = "tokio"

[[actors]]
name = "worker-1"
blox = "worker-blox"

  [actors.inject]
  self_ref = { source = "self" }
  ctrl_ref = { source = "self_secondary", index = 1 }
  pool_ref = { source = "actor", actor = "pool" }
"#;

    let config: SystemConfig = toml::from_str(toml).expect("parse failed");
    let worker = &config.actors[0];
    assert_eq!(worker.name, "worker-1");

    let self_ref = worker.inject.get("self_ref").expect("self_ref missing");
    assert_eq!(self_ref.source, "self");
    assert!(self_ref.index.is_none());

    let ctrl_ref = worker.inject.get("ctrl_ref").expect("ctrl_ref missing");
    assert_eq!(ctrl_ref.source, "self_secondary");
    assert_eq!(ctrl_ref.index, Some(1));

    let pool_ref = worker.inject.get("pool_ref").expect("pool_ref missing");
    assert_eq!(pool_ref.source, "actor");
    assert_eq!(pool_ref.actor.as_deref(), Some("pool"));
}

#[test]
fn test_parse_system_toml_embassy_runtime() {
    // Runtime selection: embassy.
    let toml = r#"
[system]
runtime = "embassy"

[[actors]]
name = "ping"
blox = "ping-blox"
"#;

    let config: SystemConfig = toml::from_str(toml).expect("parse failed");
    assert_eq!(config.system.runtime, "embassy");
    assert_eq!(config.actors.len(), 1);
}

#[test]
fn test_parse_system_toml_test_runtime() {
    // Runtime selection: test.
    let toml = r#"
[system]
runtime = "test"
"#;

    let config: SystemConfig = toml::from_str(toml).expect("parse failed");
    assert_eq!(config.system.runtime, "test");
}

#[test]
fn test_parse_system_toml_actor_no_behavior() {
    // Actors with no inject entries (e.g. timer service).
    let toml = r#"
[system]
runtime = "tokio"

[[actors]]
name = "timer"
blox = "bloxide-timer"
"#;

    let config: SystemConfig = toml::from_str(toml).expect("parse failed");
    let timer = &config.actors[0];
    assert!(timer.inject.is_empty());
}

#[test]
fn test_parse_system_toml_missing_system_fails() {
    // [system] table is required — parsing must fail without it.
    let toml = r#"
[[actors]]
name = "ping"
blox = "ping-blox"
"#;

    let result: Result<SystemConfig, _> = toml::from_str(toml);
    assert!(result.is_err());
}

#[test]
fn test_parse_system_toml_empty_actors_and_supervision() {
    // actors and supervision default to empty vecs when absent.
    let toml = r#"
[system]
runtime = "tokio"
"#;

    let config: SystemConfig = toml::from_str(toml).expect("parse failed");
    assert!(config.actors.is_empty());
    assert!(config.supervision.is_empty());
}

#[test]
fn test_generate_spec_skeleton_non_delegatable_uses_for_on_init() {
    let toml = r#"
[actor]
name = "Pool"

[event]
name = "PoolEvent"

[[event.mailboxes]]
variant = "Msg"
message = "PoolMsg"
message_path = "pool_messages::PoolMsg"

[context]
name = "PoolCtx"
generics = "<R: BloxRuntime>"
on_init = "ctx.worker_refs_mut().clear(); ctx.set_pending(0);"

[[context.fields]]
name = "worker_refs"
type = "Vec<ActorRef<WorkerMsg, R>>"

[[context.fields]]
name = "pending"
type = "u32"

[topology]

[[topology.states]]
name = "Idle"
initial = true

[[topology.states]]
name = "Active"
"#;

    let config: BloxConfig = toml::from_str(toml).expect("parse failed");
    let files = generate_all(&config, "pool-blox").expect("generate failed");
    let skeleton_file = files
        .iter()
        .find(|(n, _)| n == "spec_skeleton.rs")
        .expect("spec_skeleton.rs missing");
    let content = &skeleton_file.1;

    // The spec_skeleton should emit on_init_entry with the on_init body.
    // The old non-delegatable (impl_macro) crate imports are no longer emitted
    // by the codegen since accessor traits are gone.
    assert!(content.contains("on_init_entry"));
    assert!(content.contains("ctx.worker_refs_mut().clear();"));
    assert!(content.contains("ctx.set_pending(0);"));
}
