// Copyright 2025 Bloxide, all rights reserved
// Auto-generated by bloxide-codegen. Do not edit manually.
use ::bloxide_core::lifecycle::LifecycleCommand;
#[cfg(feature = "dynamic")]
use ::bloxide_supervisor::dynamic_mailboxes::SupervisorMailboxes;
#[cfg(feature = "dynamic")]
use ::bloxide_supervisor::NoSpawnRequest;
use ::bloxide_tokio::prelude::*;
use ::counter_blox::prelude::*;
use ::counter_demo_impl::CounterBehavior;
use ::counter_messages::CounterMsg;
use ::counter_messages::Tick;
::bloxide_tokio::actor_task_supervised!(counter_task, CounterSpec<CounterBehavior>);
#[cfg(not(feature = "dynamic"))]
::bloxide_tokio::root_task!(
    supervisor_task,
    ::bloxide_supervisor::supervisor::SupervisorSpec<TokioRuntime>
);
#[cfg(feature = "dynamic")]
::bloxide_tokio::root_task!(
    supervisor_task, ::bloxide_supervisor::supervisor::SupervisorSpec < TokioRuntime,
    ::bloxide_supervisor::NoSpawnFactory >
);
#[tokio::main]
async fn main() {
    tracing_log::LogTracer::init().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init()
        .ok();
    let ((counter_ref,), counter_mbox) = ::bloxide_tokio::channels! {
        CounterMsg(16),
    };
    let counter_id = counter_ref.id();
    let counter_ctx = CounterCtx::new(counter_id, CounterBehavior::default());
    let counter_machine = ::bloxide_core::StateMachine::new(counter_ctx);
    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAnyDone);
    ::bloxide_tokio::spawn_child!(
        group,
        counter_task(counter_machine, counter_mbox, counter_id),
        ChildPolicy::Stop
    );
    let _sup_control_ref_0 = group.control_ref();
    let sup_notify_0 = group.notify_ref();
    let sup_id = ::bloxide_tokio::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();
    #[cfg(not(feature = "dynamic"))]
    let sup_ctx =
        ::bloxide_supervisor::supervisor::SupervisorCtx::new(children, sup_id, sup_notify_0);
    #[cfg(not(feature = "dynamic"))]
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::supervisor::SupervisorSpec<TokioRuntime>,
    >::new(sup_ctx);
    #[cfg(not(feature = "dynamic"))]
    sup_machine.dispatch(
        ::bloxide_supervisor::event::SupervisorEvent::<TokioRuntime>::Lifecycle(
            LifecycleCommand::Start,
        ),
    );
    #[cfg(feature = "dynamic")]
    let sup_ctx = ::bloxide_supervisor::supervisor::SupervisorCtx::new(
        children,
        sup_id,
        sup_notify_0,
        ::bloxide_supervisor::NoSpawnFactory,
    );
    #[cfg(feature = "dynamic")]
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::supervisor::SupervisorSpec<
            TokioRuntime,
            ::bloxide_supervisor::NoSpawnFactory,
        >,
    >::new(sup_ctx);
    #[cfg(feature = "dynamic")]
    sup_machine.dispatch(::bloxide_supervisor::event::SupervisorEvent::<
        TokioRuntime,
        ::bloxide_supervisor::NoSpawnFactory,
    >::Lifecycle(LifecycleCommand::Start));
    let _ = counter_ref.send(counter_id, CounterMsg::Tick(Tick)).await;
    let _ = counter_ref.send(counter_id, CounterMsg::Tick(Tick)).await;
    #[cfg(not(feature = "dynamic"))]
    supervisor_task(sup_machine, (sup_notify_rx, sup_control_rx)).await;
    #[cfg(feature = "dynamic")]
    {
        let spawn_id = ::bloxide_tokio::next_actor_id!();
        let (_spawn_ref, spawn_rx) =
            <TokioRuntime as ::bloxide_core::capability::DynamicChannelCap>::channel::<
                NoSpawnRequest,
            >(spawn_id, 1);
        let sup_mailboxes = SupervisorMailboxes {
            child_rx: sup_notify_rx,
            control_rx: sup_control_rx,
            spawn_rx,
        };
        supervisor_task(sup_machine, sup_mailboxes).await;
    }
    println!("tokio-minimal-demo complete");
}
