// Copyright 2025 Bloxide, all rights reserved
// Auto-generated by bloxide-codegen. Do not edit manually.
use ::bloxide_core::capability::DynamicChannelCap;
use ::bloxide_core::lifecycle::LifecycleCommand;
use ::bloxide_supervisor::dynamic_mailboxes::SupervisorMailboxes;
use ::bloxide_supervisor::{NoSpawnFactory, NoSpawnRequest};
use ::bloxide_tokio::prelude::*;
use ::counter_blox::prelude::*;
use ::counter_demo_impl::CounterBehavior;
use ::counter_messages::CounterMsg;
use ::counter_messages::Tick;
::bloxide_tokio::actor_task_supervised!(counter_task, CounterSpec<CounterBehavior>);
::bloxide_tokio::root_task!(
    supervisor_task, ::bloxide_supervisor::SupervisorSpec < TokioRuntime, NoSpawnFactory >
);
#[tokio::main]
async fn main() {
    tracing_log::LogTracer::init().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init()
        .ok();
    let ((counter_ref,), counter_mbox) = ::bloxide_tokio::channels! {
        CounterMsg(16),
    };
    let counter_id = counter_ref.id();
    let counter_ctx = CounterCtx::new(counter_id, CounterBehavior::default());
    let counter_machine = ::bloxide_core::StateMachine::new(counter_ctx);
    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAnyDone);
    ::bloxide_tokio::spawn_child!(
        group,
        counter_task(counter_machine, counter_mbox, counter_id),
        ChildPolicy::Stop
    );
    let _sup_control_ref_0 = group.control_ref();
    let sup_notify = group.notify_ref();
    let _sup_kill_cap_0 = group.kill_cap().clone();
    let sup_id = ::bloxide_tokio::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();
    let spawn_id = ::bloxide_tokio::next_actor_id!();
    let (_spawn_ref, spawn_rx) =
        <TokioRuntime as DynamicChannelCap>::channel::<NoSpawnRequest>(spawn_id, 1);
    let sup_ctx =
        ::bloxide_supervisor::SupervisorCtx::new(children, sup_id, sup_notify, NoSpawnFactory);
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::SupervisorSpec<TokioRuntime, NoSpawnFactory>,
    >::new(sup_ctx);
    sup_machine.dispatch(::bloxide_supervisor::event::SupervisorEvent::<
        TokioRuntime,
        NoSpawnFactory,
    >::Lifecycle(LifecycleCommand::Start));
    let _ = counter_ref.send(counter_id, CounterMsg::Tick(Tick)).await;
    let _ = counter_ref.send(counter_id, CounterMsg::Tick(Tick)).await;
    let sup_mailboxes = SupervisorMailboxes {
        child_rx: sup_notify_rx,
        control_rx: sup_control_rx,
        spawn_rx,
    };
    supervisor_task(sup_machine, sup_mailboxes).await;
    println!("tokio-minimal-demo complete");
}
