// Auto-generated by bloxide-codegen. Do not edit manually.
::bloxide_embassy::timer_task!(timer_task);
use ::bloxide_embassy::prelude::*;
use ::bloxide_core::capability::StaticChannelCap;
use ::bloxide_core::lifecycle::LifecycleCommand;
use ::bloxide_supervisor::dynamic_mailboxes::SupervisorMailboxes;
use ::ping_blox::prelude::*;
use ::pong_blox::prelude::*;
use ::embassy_demo_impl::PingBehavior;
use ::bloxide_supervisor::{NoSpawnFactory, NoSpawnRequest};
use ::ping_pong_messages::PingPongMsg;
::bloxide_embassy::actor_task_supervised!(
    ping_task, PingSpec < EmbassyRuntime, PingBehavior >
);
::bloxide_embassy::actor_task_supervised!(pong_task, PongSpec < EmbassyRuntime >);
::bloxide_embassy::root_task!(
    supervisor_task, ::bloxide_supervisor::SupervisorSpec < EmbassyRuntime, NoSpawnFactory >,
    std::process::exit(0)
);
fn main() {
    static EXECUTOR: ::static_cell::StaticCell<::embassy_executor::Executor> = ::static_cell::StaticCell::new();
    let executor = EXECUTOR.init(::embassy_executor::Executor::new());
    executor.run(setup);
}
fn setup(spawner: ::embassy_executor::Spawner) {
    let timer_ref = ::bloxide_embassy::spawn_timer!(spawner, timer_task, 8);
    let ((ping_ref,), ping_mbox) = ::bloxide_embassy::channels! {
        PingPongMsg(16),
    };
    let ping_id = ping_ref.id();
    let ((pong_ref,), pong_mbox) = ::bloxide_embassy::channels! {
        PingPongMsg(16),
    };
    let pong_id = pong_ref.id();
    let ping_ctx = PingCtx::new(
        pong_ref.clone(),
        ping_ref.clone(),
        timer_ref.clone(),
        ping_id,
        PingBehavior::default(),
    );
    let pong_ctx = PongCtx::new(ping_ref.clone(), pong_id);
    let ping_machine = ::bloxide_core::StateMachine::new(ping_ctx);
    let pong_machine = ::bloxide_core::StateMachine::new(pong_ctx);
    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAnyDone);
    ::bloxide_embassy::spawn_child!(
        spawner, group, ping_task(ping_machine, ping_mbox, ping_id), ChildPolicy::Restart
        { max : 1u32 as usize }
    );
    ::bloxide_embassy::spawn_child!(
        spawner, group, pong_task(pong_machine, pong_mbox, pong_id), ChildPolicy::Stop
    );
    let _sup_control_ref_0 = group.control_ref();
    let sup_notify = group.notify_ref();
    let sup_id = ::bloxide_embassy::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();
    let spawn_id = ::bloxide_embassy::next_actor_id!();
    let (_spawn_ref, spawn_rx) =
        <EmbassyRuntime as StaticChannelCap>::channel::<NoSpawnRequest, 1>(spawn_id);
    let sup_ctx = ::bloxide_supervisor::SupervisorCtx::new(children, sup_id, sup_notify, NoSpawnFactory);
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::SupervisorSpec<EmbassyRuntime, NoSpawnFactory>,
    >::new(sup_ctx);
    sup_machine
        .dispatch(
            ::bloxide_supervisor::event::SupervisorEvent::<
                EmbassyRuntime,
                NoSpawnFactory,
            >::Lifecycle(LifecycleCommand::Start),
        );
    let sup_mailboxes = SupervisorMailboxes {
        child_rx: sup_notify_rx,
        control_rx: sup_control_rx,
        spawn_rx,
    };
    spawner.must_spawn(supervisor_task(sup_machine, sup_mailboxes));
    println!("embassy-demo complete");
}
