// Copyright 2025 Bloxide, all rights reserved
//! Lifecycle action functions for the supervisor state machine.
//!
//! These take the concrete event type `&SupervisorEvent<R>` directly. The
//! `SupervisorEvent` enum is generated by the codegen from the `[event]`
//! section in `blox.toml`.

use bloxide_core::{
    accessor::HasSelfId, lifecycle::ChildLifecycleEvent, messaging::Envelope,
    transition::ActionResult,
};
use bloxide_supervisor_context::{HasChildGroup, HasChildGroupMut, HasPending, SupervisorControl};

use crate::{SupervisorCtx, SupervisorEvent};

/// Start all children in the group.
pub fn start_children<R, C>(ctx: &mut C)
where
    R: bloxide_core::capability::BloxRuntime,
    C: HasSelfId + HasChildGroup<R>,
{
    ctx.children().start_all(ctx.self_id());
}

/// Stop all children in the group.
pub fn stop_all_children<R, C>(ctx: &mut C)
where
    R: bloxide_core::capability::BloxRuntime,
    C: HasSelfId + HasChildGroup<R>,
{
    ctx.children().stop_all(ctx.self_id());
}

/// Handle a Done or Failed child lifecycle event.
pub fn handle_done_or_failed<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Done { child_id }))
    | SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Failed { child_id })) = ev
    {
        let from = ctx.self_id();
        let action = ctx.children_mut().handle_done_or_failed(*child_id, from);
        ctx.set_pending(action);
    }
    ActionResult::Ok
}

/// Handle a Reset child lifecycle event.
pub fn handle_reset<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Reset { child_id })) = ev {
        let from = ctx.self_id();
        ctx.children_mut().handle_reset(*child_id, from);
    }
    ActionResult::Ok
}

/// Record a stopped child.
pub fn record_stopped<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { child_id })) = ev {
        ctx.children_mut().record_stopped(*child_id);
    }
    ActionResult::Ok
}

/// Record a started child.
pub fn record_started<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Started { child_id })) = ev {
        ctx.children_mut().handle_started(*child_id);
    }
    ActionResult::Ok
}

/// Record an alive child.
pub fn record_alive<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Alive { child_id })) = ev {
        ctx.children_mut().handle_alive(*child_id);
    }
    ActionResult::Ok
}

/// Register a new static child.
pub fn register_child<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Control(Envelope(_, SupervisorControl::RegisterChild(child))) = ev {
        let from = ctx.self_id();
        let (id, lifecycle_ref, policy) = (child.id, child.lifecycle_ref.clone(), child.policy);
        ctx.children_mut().add(id, lifecycle_ref, policy);
        ctx.children_mut().start_child(id, from);
    }
    ActionResult::Ok
}

/// Handle a `RegisterDynamicChild` control message.
///
/// Called when the supervisor receives a `SupervisorControl::RegisterDynamicChild`
/// from the `spawn_child` helper. Registers the child in the child group
/// (storing the `kill_ref` for the kill mailbox and the `abort_handle` for
/// the external abort ripcord) and sends a Start command.
///
/// The `abort_handle` is `Clone` (it's `R::AbortHandle`), so we can clone it
/// from `&Event` — the HSM engine passes `&Event` to action functions, not
/// `&mut Event`. This is the key advantage of `AbortHandle` over `TaskHandle`
/// (`JoinHandle<()>` is not `Clone`).
pub fn handle_register_dynamic_child<R>(
    ctx: &mut SupervisorCtx<R>,
    ev: &SupervisorEvent<R>,
) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Control(Envelope(_, SupervisorControl::RegisterDynamicChild(reg))) = ev
    {
        let from = ctx.self_id();
        let child_id = reg.id;
        ctx.children_mut().add_dynamic(
            child_id,
            reg.lifecycle_ref.clone(),
            reg.kill_ref.clone(),
            reg.abort_handle.clone(),
            reg.policy,
        );
        ctx.children_mut().start_child(child_id, from);
    }
    ActionResult::Ok
}

/// Handle a health-check tick.
pub fn handle_health_check<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Control(Envelope(_, SupervisorControl::HealthCheckTick)) = ev {
        let from = ctx.self_id();
        let action = ctx.children_mut().health_check_tick(from);
        ctx.set_pending(action);
    }
    ActionResult::Ok
}
