// Copyright 2025 Bloxide, all rights reserved
//! Lifecycle action functions for the supervisor state machine.
//!
//! These take the concrete event type `&SupervisorEvent<R>` directly. The
//! `SupervisorEvent` enum is generated by the codegen from the `[event]`
//! section in `blox.toml`.

use crate::SupervisorControl;
use bloxide_child_management::ChildAction;
use bloxide_core::{
    accessor::HasSelfId, lifecycle::ChildLifecycleEvent, messaging::Envelope,
    transition::ActionResult,
};

use crate::{SupervisorCtx, SupervisorEvent};

/// Start all children in the group and clear lifecycle counters.
///
/// This is the `on_entry` for the Running state. In the four-level lifecycle
/// model, `Guard::Reset` goes directly to `initial_state()` (Running) — it
/// does NOT fire `on_init_entry`. So counters must be cleared here, in the
/// Running on_entry, which fires both on initial Start and on Reset.
pub fn start_children<R>(ctx: &mut SupervisorCtx<R>)
where
    R: bloxide_core::capability::BloxRuntime,
{
    ctx.children.clear_counters();
    ctx.pending = ChildAction::default();
    ctx.children.start_all(ctx.self_id);
}

/// Stop all children in the group.
pub fn stop_all_children<R>(ctx: &mut SupervisorCtx<R>)
where
    R: bloxide_core::capability::BloxRuntime,
{
    ctx.children.stop_all(ctx.self_id);
}

/// Handle a Done or Failed child lifecycle event.
pub fn handle_done_or_failed<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Done { child_id }))
    | SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Failed { child_id })) = ev
    {
        let from = ctx.self_id();
        let action = ctx
            .children
            .handle_done_or_failed(*child_id, from, &ctx.child_notify);
        ctx.pending = action;
    }
    ActionResult::Ok
}

/// Record a started child.
///
/// In the four-level lifecycle model, `Started` covers both initial `Start`
/// and `Reset` (both go directly to `initial_state()`). The supervisor does
/// not need to send `Start` after `Reset`.
pub fn record_started<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Started { child_id })) = ev {
        ctx.children.handle_started(*child_id);
    }
    ActionResult::Ok
}

/// Record a stopped child.
pub fn record_stopped<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { child_id })) = ev {
        ctx.children.record_stopped(*child_id);
    }
    ActionResult::Ok
}

/// Record an aborted child.
///
/// Aborted means the child's task self-terminated cooperatively via
/// `AbortCommand`. The task is gone — restarting requires respawning.
pub fn record_aborted<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Aborted { child_id })) = ev {
        ctx.children.record_aborted(*child_id);
    }
    ActionResult::Ok
}

/// Record a killed child.
///
/// Killed means the child's task was destroyed externally via
/// `KillCapability::kill(handle)`. Permanently dead — cannot be restarted
/// without respawning the task.
pub fn record_killed<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Killed { child_id })) = ev {
        ctx.children.record_killed(*child_id);
    }
    ActionResult::Ok
}

/// Record an alive child.
pub fn record_alive<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Alive { child_id })) = ev {
        ctx.children.handle_alive(*child_id);
    }
    ActionResult::Ok
}

/// Register a new static child.
pub fn register_child<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Control(Envelope(_, SupervisorControl::RegisterChild(child))) = ev {
        let from = ctx.self_id();
        let (id, lifecycle_ref, policy) = (child.id, child.lifecycle_ref.clone(), child.policy);
        ctx.children.add(id, lifecycle_ref, policy);
        ctx.children.start_child(id, from);
    }
    ActionResult::Ok
}

/// Handle a `RegisterDynamicChild` control message.
///
/// Called when the supervisor receives a `SupervisorControl::RegisterDynamicChild`
/// from the `spawn_child` helper. Registers the child in the child group
/// (storing the `abort_ref` for the cooperative abort mailbox and the
/// `kill_handle` for the external kill ripcord) and sends a Start command.
pub fn handle_register_dynamic_child<R>(
    ctx: &mut SupervisorCtx<R>,
    ev: &SupervisorEvent<R>,
) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Control(Envelope(_, SupervisorControl::RegisterDynamicChild(reg))) = ev
    {
        let from = ctx.self_id();
        let child_id = reg.id;
        ctx.children.add_dynamic(
            child_id,
            reg.lifecycle_ref.clone(),
            reg.abort_ref.clone(),
            reg.kill_handle.clone(),
            reg.policy,
        );
        ctx.children.start_child(child_id, from);
    }
    ActionResult::Ok
}

/// Handle a health-check tick.
pub fn handle_health_check<R>(ctx: &mut SupervisorCtx<R>, ev: &SupervisorEvent<R>) -> ActionResult
where
    R: bloxide_core::capability::BloxRuntime,
{
    if let SupervisorEvent::Control(Envelope(_, SupervisorControl::HealthCheckTick)) = ev {
        let from = ctx.self_id();
        let action = ctx.children.health_check_tick(from, &ctx.child_notify);
        ctx.pending = action;
    }
    ActionResult::Ok
}
