// Copyright 2025 Bloxide, all rights reserved
//! Concrete supervisor spec for in-crate testing.
//!
//! The blox-crate-level `SupervisorSpec` (in `generated/spec_skeleton.rs`)
//! contains **stub** action closures — per invariant #18, concrete actions
//! are only linked at the system level via `system.toml` codegen.
//!
//! This module provides a `ConcreteSupervisorSpec<R>` that wires the real
//! platform action functions (`bloxide_child_management::actions::*`) with
//! payload extraction, so that in-crate tests can verify actual supervisor
//! behavior without needing a system.toml. System-level apps get their own
//! concrete spec generated by the codegen.

use crate::generated::topology::SupervisorState;
use crate::{SupervisorCtx, SupervisorEvent};
use bloxide_child_management::control::ChildCtrl;
use bloxide_child_management::ChildAction;
use bloxide_core::capability::BloxRuntime;
use bloxide_core::lifecycle::ChildLifecycleEvent;
use bloxide_core::messaging::Envelope;
use bloxide_core::spec::{MachineSpec, StateFns};
use bloxide_core::topology::LeafState;
use bloxide_core::transition::{ActionResult, Decision, StateRule};
use core::marker::PhantomData;

pub struct ConcreteSupervisorSpec<R: BloxRuntime> {
    _phantom: PhantomData<R>,
}

impl<R: BloxRuntime> ConcreteSupervisorSpec<R> {
    const RUNNING_FNS: StateFns<Self> = StateFns {
        on_entry: &[|ctx| {
            bloxide_child_management::actions::start_children(
                ctx.self_id,
                &mut ctx.children,
                &mut ctx.pending,
            );
        }],
        on_exit: &[],
        transitions: &[
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::handle_done_or_failed(
                            ctx.self_id,
                            &mut ctx.children,
                            &ctx.child_notify,
                            &mut ctx.pending,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.pending == ChildAction::BeginShutdown {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Failed { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::handle_done_or_failed(
                            ctx.self_id,
                            &mut ctx.children,
                            &ctx.child_notify,
                            &mut ctx.pending,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.pending == ChildAction::BeginShutdown {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Started { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::record_started(
                            &mut ctx.children,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Aborted { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::record_aborted(
                            &mut ctx.children,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Killed { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::record_killed(
                            &mut ctx.children,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Alive { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::record_alive(&mut ctx.children, payload);
                    }
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Done { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::deregister_done(
                            &mut ctx.children,
                            &mut ctx.pending,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.pending == ChildAction::BeginShutdown {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, ChildCtrl::RegisterChild(_)))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(ctrl) = ev.control_payload() {
                        bloxide_child_management::actions::register_child(
                            ctx.self_id,
                            &mut ctx.children,
                            ctrl,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, ChildCtrl::RegisterDynamicChild(_)))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(ctrl) = ev.control_payload() {
                        bloxide_child_management::actions::handle_register_dynamic_child(
                            ctx.self_id,
                            &mut ctx.children,
                            ctrl,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, ChildCtrl::HealthCheckTick))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(ctrl) = ev.control_payload() {
                        bloxide_child_management::actions::handle_health_check(
                            ctx.self_id,
                            &mut ctx.children,
                            &ctx.child_notify,
                            &mut ctx.pending,
                            ctrl,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.pending == ChildAction::BeginShutdown {
                        Decision::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Decision::Stay
                    }
                },
            },
            // Catch-all: any other Child event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Child(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            // Catch-all: any other Control event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Control(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
        ],
    };

    const SHUTTING_DOWN_FNS: StateFns<Self> = StateFns {
        on_entry: &[|ctx| {
            bloxide_child_management::actions::stop_all_children(ctx.self_id, &ctx.children);
        }],
        on_exit: &[],
        transitions: &[
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::record_stopped(
                            &mut ctx.children,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Done { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    if let Some(payload) = ev.child_payload() {
                        bloxide_child_management::actions::deregister_done(
                            &mut ctx.children,
                            &mut ctx.pending,
                            payload,
                        );
                    }
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Decision::Stop
                    } else {
                        Decision::Stay
                    }
                },
            },
            // Catch-all: any other Child event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Child(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
            // Catch-all: any Control event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Control(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Decision::Stay,
            },
        ],
    };
}

impl<R: BloxRuntime> MachineSpec for ConcreteSupervisorSpec<R> {
    type State = SupervisorState;
    type Event = SupervisorEvent<R>;
    type Ctx = SupervisorCtx<R>;
    type Mailboxes<Rt: BloxRuntime> = (Rt::Stream<ChildLifecycleEvent>, Rt::Stream<ChildCtrl<R>>);
    const HANDLER_TABLE: &'static [&'static StateFns<Self>] =
        &[&Self::RUNNING_FNS, &Self::SHUTTING_DOWN_FNS];
    fn initial_state() -> SupervisorState {
        SupervisorState::Running
    }
    fn is_error(_state: &SupervisorState) -> bool {
        false
    }
    fn on_init_entry(ctx: &mut Self::Ctx) {
        ctx.children.clear_counters();
        ctx.pending = ChildAction::default();
    }
}
