// Copyright 2025 Bloxide, all rights reserved
//! Concrete supervisor spec for in-crate testing.
//!
//! The blox-crate-level `SupervisorSpec` (in `generated/spec_skeleton.rs`)
//! contains **stub** action closures — per invariant #18, concrete actions
//! are only linked at the system level via `system.toml` codegen.
//!
//! This module provides a `ConcreteSupervisorSpec<R>` that wires the real
//! `crate::actions::*` functions, so that in-crate tests can verify actual
//! supervisor behavior without needing a system.toml. System-level apps get
//! their own concrete spec generated by the codegen.

use crate::control::SupervisorControl;
use crate::generated::topology::SupervisorState;
use crate::{SupervisorCtx, SupervisorEvent};
use bloxide_child_management::ChildAction;
use bloxide_core::capability::BloxRuntime;
use bloxide_core::lifecycle::ChildLifecycleEvent;
use bloxide_core::messaging::Envelope;
use bloxide_core::spec::{MachineSpec, StateFns};
use bloxide_core::topology::LeafState;
use bloxide_core::transition::{ActionResult, Guard, StateRule};
use core::marker::PhantomData;

pub struct ConcreteSupervisorSpec<R: BloxRuntime> {
    _phantom: PhantomData<R>,
}

impl<R: BloxRuntime> ConcreteSupervisorSpec<R> {
    const RUNNING_FNS: StateFns<Self> = StateFns {
        on_entry: &[|ctx| {
            crate::actions::start_children(ctx.self_id, &mut ctx.children, &mut ctx.pending);
        }],
        on_exit: &[],
        transitions: &[
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::handle_done_or_failed(
                        ctx.self_id,
                        &mut ctx.children,
                        &ctx.child_notify,
                        &mut ctx.pending,
                        ev,
                    );
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.pending == ChildAction::BeginShutdown {
                        Guard::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Guard::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Failed { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::handle_done_or_failed(
                        ctx.self_id,
                        &mut ctx.children,
                        &ctx.child_notify,
                        &mut ctx.pending,
                        ev,
                    );
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.pending == ChildAction::BeginShutdown {
                        Guard::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Guard::Stay
                    }
                },
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Started { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::record_started(&mut ctx.children, ev);
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Aborted { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::record_aborted(&mut ctx.children, ev);
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Killed { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::record_killed(&mut ctx.children, ev);
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Alive { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::record_alive(&mut ctx.children, ev);
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, SupervisorControl::RegisterChild(_)))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::register_child(ctx.self_id, &mut ctx.children, ev);
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(
                            _,
                            SupervisorControl::RegisterDynamicChild(_)
                        ))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::handle_register_dynamic_child(
                        ctx.self_id,
                        &mut ctx.children,
                        ev,
                    );
                    ActionResult::Ok
                }],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Control(Envelope(_, SupervisorControl::HealthCheckTick))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::handle_health_check(
                        ctx.self_id,
                        &mut ctx.children,
                        &ctx.child_notify,
                        &mut ctx.pending,
                        ev,
                    );
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.pending == ChildAction::BeginShutdown {
                        Guard::Transition(LeafState::new(SupervisorState::ShuttingDown))
                    } else {
                        Guard::Stay
                    }
                },
            },
            // Catch-all: any other Child event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Child(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            // Catch-all: any other Control event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Control(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
        ],
    };

    const SHUTTING_DOWN_FNS: StateFns<Self> = StateFns {
        on_entry: &[|ctx| {
            crate::actions::stop_all_children(ctx.self_id, &ctx.children);
        }],
        on_exit: &[],
        transitions: &[
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| {
                    matches!(
                        ev,
                        SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { .. }))
                    )
                },
                actions: &[|ctx, ev| {
                    crate::actions::record_stopped(&mut ctx.children, ev);
                    ActionResult::Ok
                }],
                guard: |ctx, _results, _ev| {
                    if ctx.all_children_stopped() {
                        Guard::Stop
                    } else {
                        Guard::Stay
                    }
                },
            },
            // Catch-all: any other Child event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CHILD_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Child(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
            // Catch-all: any Control event → absorb
            StateRule {
                event_tag: SupervisorEvent::<R>::CONTROL_TAG,
                matches: |ev| matches!(ev, SupervisorEvent::Control(_)),
                actions: &[],
                guard: |_ctx, _results, _ev| Guard::Stay,
            },
        ],
    };
}

impl<R: BloxRuntime> MachineSpec for ConcreteSupervisorSpec<R> {
    type State = SupervisorState;
    type Event = SupervisorEvent<R>;
    type Ctx = SupervisorCtx<R>;
    type Mailboxes<Rt: BloxRuntime> = (
        Rt::Stream<ChildLifecycleEvent>,
        Rt::Stream<SupervisorControl<R>>,
    );
    const HANDLER_TABLE: &'static [&'static StateFns<Self>] =
        &[&Self::RUNNING_FNS, &Self::SHUTTING_DOWN_FNS];
    fn initial_state() -> SupervisorState {
        SupervisorState::Running
    }
    fn is_error(_state: &SupervisorState) -> bool {
        false
    }
    fn on_init_entry(ctx: &mut Self::Ctx) {
        ctx.children.clear_counters();
        ctx.pending = ChildAction::default();
    }
}
