// Copyright 2025 Bloxide, all rights reserved
//! Generate event enums and their trait implementations from `EventConfig`.

use quote::{format_ident, quote};

use crate::schema::EventConfig;

const HEADER: &str = "// Auto-generated by bloxide-codegen. Do not edit manually.\n";

/// Convert PascalCase to snake_case.
fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

/// Convert PascalCase to UPPER_SNAKE_CASE.
fn to_upper_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

pub fn generate(config: &EventConfig) -> anyhow::Result<String> {
    let event_ident = format_ident!("{}", config.name);

    // Parse optional generics
    let generics = if let Some(ref g) = config.generics {
        syn::parse_str::<syn::Generics>(g)
            .map_err(|e| anyhow::anyhow!("invalid generics '{}': {}", g, e))?
    } else {
        syn::Generics::default()
    };
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();

    // Conditionally derive Debug
    let derive_debug = if config.debug == Some(false) {
        quote! {}
    } else {
        quote! { #[derive(Debug)] }
    };

    // Build use statements
    let mut use_statements = vec![quote! {
        use ::bloxide_core::messaging::Envelope;
    }];
    if config.generics.is_some() {
        use_statements.push(quote! {
            use ::bloxide_core::capability::BloxRuntime;
        });
    }

    // Enum variants
    let mut enum_variants = vec![quote! {
        /// Lifecycle command (Start/Reset/Stop/Ping).
        Lifecycle(::bloxide_core::lifecycle::LifecycleCommand)
    }];

    for mb in &config.mailboxes {
        let variant_ident = format_ident!("{}", mb.variant);
        let msg_type = if let Some(ref path) = mb.message_path {
            let path = syn::parse_str::<syn::Path>(path)
                .map_err(|e| anyhow::anyhow!("invalid message_path '{}': {}", path, e))?;
            quote! { #path }
        } else {
            let ident = format_ident!("{}", mb.message);
            quote! { #ident }
        };
        enum_variants.push(quote! {
            #variant_ident(Envelope<#msg_type>)
        });
    }

    let enum_def = quote! {
        #derive_debug
        pub enum #event_ident #generics {
            #(#enum_variants),*
        }
    };

    // From<Envelope<M>> impls
    let mut from_impls = Vec::new();
    for mb in &config.mailboxes {
        let variant_ident = format_ident!("{}", mb.variant);
        let msg_type = if let Some(ref path) = mb.message_path {
            let path = syn::parse_str::<syn::Path>(path)
                .map_err(|e| anyhow::anyhow!("invalid message_path '{}': {}", path, e))?;
            quote! { #path }
        } else {
            let ident = format_ident!("{}", mb.message);
            quote! { #ident }
        };
        from_impls.push(quote! {
            impl #impl_generics ::core::convert::From<Envelope<#msg_type>> for #event_ident #ty_generics #where_clause {
                fn from(envelope: Envelope<#msg_type>) -> Self {
                    #event_ident::#variant_ident(envelope)
                }
            }
        });
    }

    // From<LifecycleCommand>
    let from_lifecycle = quote! {
        impl #impl_generics ::core::convert::From<::bloxide_core::lifecycle::LifecycleCommand> for #event_ident #ty_generics #where_clause {
            fn from(cmd: ::bloxide_core::lifecycle::LifecycleCommand) -> Self {
                #event_ident::Lifecycle(cmd)
            }
        }
    };

    // EventTag impl
    let mut event_tag_arms = vec![quote! {
        Self::Lifecycle(..) => ::bloxide_core::event_tag::LIFECYCLE_TAG
    }];
    for (idx, mb) in config.mailboxes.iter().enumerate() {
        let variant_ident = format_ident!("{}", mb.variant);
        let tag = idx as u8;
        event_tag_arms.push(quote! {
            Self::#variant_ident(..) => #tag
        });
    }

    let event_tag_impl = quote! {
        impl #impl_generics ::bloxide_core::event_tag::EventTag for #event_ident #ty_generics #where_clause {
            #[inline]
            fn event_tag(&self) -> u8 {
                match self {
                    #(#event_tag_arms,)*
                }
            }
        }
    };

    // LifecycleEvent impl
    let lifecycle_impl = quote! {
        impl #impl_generics ::bloxide_core::event_tag::LifecycleEvent for #event_ident #ty_generics #where_clause {
            fn as_lifecycle_command(&self) -> ::core::option::Option<::bloxide_core::lifecycle::LifecycleCommand> {
                match self {
                    Self::Lifecycle(cmd) => ::core::option::Option::Some(*cmd),
                    _ => ::core::option::Option::None,
                }
            }
        }
    };

    // Tag constants and accessor methods
    let mut tag_constants = Vec::new();
    let mut accessor_methods = Vec::new();

    for (idx, mb) in config.mailboxes.iter().enumerate() {
        let variant_ident = format_ident!("{}", mb.variant);
        let msg_type = if let Some(ref path) = mb.message_path {
            let path = syn::parse_str::<syn::Path>(path)
                .map_err(|e| anyhow::anyhow!("invalid message_path '{}': {}", path, e))?;
            quote! { #path }
        } else {
            let ident = format_ident!("{}", mb.message);
            quote! { #ident }
        };
        let tag = idx as u8;

        let upper_snake = to_upper_snake_case(&mb.variant);
        let const_name = format_ident!("{}_TAG", upper_snake);

        tag_constants.push(quote! {
            /// Event tag for this variant, used for fast dispatch filtering.
            pub const #const_name: u8 = #tag;
        });

        let snake_name = to_snake_case(&mb.variant);
        let envelope_method = format_ident!("{}_envelope", snake_name);
        let payload_method = format_ident!("{}_payload", snake_name);

        accessor_methods.push(quote! {
            /// Returns the envelope if this event matches this variant.
            pub fn #envelope_method(&self) -> ::core::option::Option<&Envelope<#msg_type>> {
                match self { #event_ident::#variant_ident(ref e) => ::core::option::Option::Some(e), _ => ::core::option::Option::None }
            }
            /// Returns the message payload if this event matches this variant.
            pub fn #payload_method(&self) -> ::core::option::Option<&#msg_type> {
                match self { #event_ident::#variant_ident(ref e) => ::core::option::Option::Some(&e.1), _ => ::core::option::Option::None }
            }
        });
    }

    // Lifecycle helpers
    let lifecycle_helpers = quote! {
        /// Create a Start lifecycle event.
        pub fn start() -> Self {
            Self::Lifecycle(::bloxide_core::lifecycle::LifecycleCommand::Start)
        }

        /// Create a Reset lifecycle event.
        pub fn reset() -> Self {
            Self::Lifecycle(::bloxide_core::lifecycle::LifecycleCommand::Reset)
        }

        /// Create a Stop lifecycle event.
        pub fn stop() -> Self {
            Self::Lifecycle(::bloxide_core::lifecycle::LifecycleCommand::Stop)
        }

        /// Create a Ping lifecycle event.
        pub fn ping() -> Self {
            Self::Lifecycle(::bloxide_core::lifecycle::LifecycleCommand::Ping)
        }
    };

    let impl_block = quote! {
        impl #impl_generics #event_ident #ty_generics #where_clause {
            #(#tag_constants)*
            #(#accessor_methods)*
            #lifecycle_helpers
        }
    };

    let tokens = quote! {
        #(#use_statements)*
        #enum_def
        #(#from_impls)*
        #from_lifecycle
        #event_tag_impl
        #lifecycle_impl
        #impl_block
    };

    let raw = tokens.to_string();
    let file = syn::parse_str::<syn::File>(&raw)
        .map_err(|e| anyhow::anyhow!("syn parsing failed: {}", e))?;
    let formatted = prettyplease::unparse(&file);

    Ok(format!("{}{}", HEADER, formatted))
}
