// Copyright 2025 Bloxide, all rights reserved
//! Public API for bloxide-codegen — generate Rust source from blox.toml specs.

pub mod ctx;
mod events;
mod mailboxes;
mod messages;
pub mod schema;
pub mod spec_skeleton;
mod topology;

use schema::BloxConfig;
use std::path::Path;

/// Generate all artifacts from a parsed `BloxConfig`.
///
/// Returns a vector of `(filename, content)` pairs.
pub fn generate_all(
    config: &BloxConfig,
    crate_name: &str,
) -> anyhow::Result<Vec<(String, String)>> {
    let mut files = Vec::new();

    if let Some(messages) = &config.messages {
        for msg in messages {
            let code = messages::generate(msg)?;
            files.push((format!("messages_{}.rs", msg.name.to_lowercase()), code));
        }
    }

    if let Some(event) = &config.event {
        let code = events::generate(event)?;
        files.push(("events.rs".to_string(), code));
    }

    if let Some(topology) = &config.topology {
        let actor_name = config.actor.as_ref().map(|a| a.name.as_str());
        let code = topology::generate(topology, actor_name, crate_name)?;
        files.push(("topology.rs".to_string(), code));
    }

    if let Some(context) = &config.context {
        let code = ctx::generate(context, crate_name)?;
        files.push(("ctx.rs".to_string(), code));
    }

    if let (Some(actor), Some(topology), Some(event)) =
        (&config.actor, &config.topology, &config.event)
    {
        let msg_type = event
            .mailboxes
            .first()
            .map(|m| m.message.clone())
            .unwrap_or_default();
        let msg_path = event
            .mailboxes
            .first()
            .and_then(|m| m.message_path.clone())
            .unwrap_or_default();
        let code = spec_skeleton::generate(
            actor,
            topology,
            config.context.as_ref(),
            &event.name,
            &msg_type,
            &msg_path,
            crate_name,
        )?;
        files.push(("spec_skeleton.rs".to_string(), code));
    }

    if let Some(mailboxes) = &config.mailboxes {
        let code = mailboxes::generate(mailboxes)?;
        files.push(("mailboxes_impls.rs".to_string(), code));
    }

    // Generate mod.rs that re-exports all generated submodules
    if !files.is_empty() {
        let mod_rs = generate_mod_rs(&files);
        files.push(("mod.rs".to_string(), mod_rs));
    }

    Ok(files)
}

fn generate_mod_rs(files: &[(String, String)]) -> String {
    let mut lines = vec![
        "// Auto-generated module.".to_string(),
        "// Files in this directory are generated by bloxide-codegen.".to_string(),
    ];

    for (filename, _) in files {
        if filename == "mod.rs" {
            continue;
        }
        let stem = filename.strip_suffix(".rs").unwrap_or(filename);
        lines.push(format!("pub mod {stem};"));
        lines.push(format!("#[allow(unused_imports)] pub use {stem}::*;"));
    }

    lines.join("\n") + "\n"
}

/// Parse a `blox.toml` file and generate all artifacts.
///
/// The crate name is inferred from the parent directory name.
pub fn generate_from_toml(input_path: &Path) -> anyhow::Result<Vec<(String, String)>> {
    let content = std::fs::read_to_string(input_path)?;
    let config: BloxConfig = toml::from_str(&content)?;

    let crate_name = input_path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();

    generate_all(&config, &crate_name)
}

/// Generate artifacts and write them to a directory.
///
/// Files are written only if their content has changed, preserving mtime for
/// caching.
pub fn generate_to_dir(
    config: &BloxConfig,
    crate_name: &str,
    output_dir: &Path,
) -> anyhow::Result<Vec<String>> {
    std::fs::create_dir_all(output_dir)?;

    let files = generate_all(config, crate_name)?;
    let mut written = Vec::new();

    for (filename, content) in files {
        let path = output_dir.join(&filename);
        let needs_write = if path.exists() {
            std::fs::read_to_string(&path)? != content
        } else {
            true
        };

        if needs_write {
            std::fs::write(&path, &content)?;
            written.push(filename);
        }
    }

    Ok(written)
}
