// Copyright 2025 Bloxide, all rights reserved
//! Public API for bloxide-codegen — generate Rust source from blox.toml specs.

pub mod ctx;
mod events;
mod mailboxes;
mod messages;
pub mod schema;
pub mod spec_skeleton;
pub mod system_wiring;
mod topology;
pub mod util;
pub mod wiring;

use schema::{BloxConfig, SystemConfig};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

/// Generate all artifacts from a parsed `BloxConfig`.
///
/// Returns a vector of `(filename, content)` pairs.
pub fn generate_all(
    config: &BloxConfig,
    crate_name: &str,
) -> anyhow::Result<Vec<(String, String)>> {
    let mut files = Vec::new();

    if let Some(messages) = &config.messages {
        for msg in messages {
            let code = messages::generate(msg)?;
            files.push((format!("messages_{}.rs", msg.name.to_lowercase()), code));
        }
    }

    if let Some(event) = &config.event {
        let code = events::generate(event)?;
        files.push(("events.rs".to_string(), code));
    }

    if let Some(topology) = &config.topology {
        let actor_name = config.actor.as_ref().map(|a| a.name.as_str());
        let has_feature = config
            .context
            .as_ref()
            .and_then(|c| c.feature.as_ref())
            .is_some();
        let code = topology::generate(topology, actor_name, crate_name, has_feature)?;
        files.push(("topology.rs".to_string(), code));
    }

    if let Some(context) = &config.context {
        let code = ctx::generate(context, crate_name)?;
        files.push(("ctx.rs".to_string(), code));
    }

    // spec_skeleton requires actor + topology + context, plus event info.
    // Event info can come from an [event] section OR from the context config
    // (event_name/event_generics fields — used when the event enum is
    // hand-written in a separate crate).
    if let (Some(actor), Some(topology), Some(context)) =
        (&config.actor, &config.topology, &config.context)
    {
        if context.event_name.is_some() || config.event.is_some() {
            let code = spec_skeleton::generate(
                actor,
                topology,
                context,
                config.event.as_ref(),
                crate_name,
            )?;
            files.push(("spec_skeleton.rs".to_string(), code));
        }
    }

    if let Some(wiring) = &config.wiring {
        if !wiring.actors.is_empty() {
            let code = wiring::generate(wiring, crate_name)?;
            files.push(("wiring_main.rs".to_string(), code));
        }
    }

    if let Some(mailboxes) = &config.mailboxes {
        let code = mailboxes::generate(mailboxes)?;
        files.push(("mailboxes_impls.rs".to_string(), code));
    }

    // Generate mod.rs that re-exports all generated submodules
    if !files.is_empty() {
        let mod_rs = generate_mod_rs(&files);
        files.push(("mod.rs".to_string(), mod_rs));
    }

    Ok(files)
}

fn generate_mod_rs(files: &[(String, String)]) -> String {
    let mut lines = vec![
        "// Copyright 2025 Bloxide, all rights reserved".to_string(),
        "// Auto-generated module.".to_string(),
        "// Files in this directory are generated by bloxide-codegen.".to_string(),
    ];

    for (filename, _) in files {
        if filename == "mod.rs" {
            continue;
        }
        let stem = filename.strip_suffix(".rs").unwrap_or(filename);
        // topology.rs emits #[macro_export] macros (e.g. *_handler_table!).
        // #[macro_use] makes them available to sibling modules (spec_skeleton.rs).
        if stem == "topology" {
            lines.push("#[macro_use]".to_string());
        }
        lines.push(format!("pub mod {stem};"));
        lines.push(format!("#[allow(unused_imports)] pub use {stem}::*;"));
    }

    lines.join("\n") + "\n"
}

/// Parse a `blox.toml` file and generate all artifacts.
///
/// The crate name is inferred from the parent directory name.
pub fn generate_from_toml(input_path: &Path) -> anyhow::Result<Vec<(String, String)>> {
    let content = std::fs::read_to_string(input_path)?;
    let config: BloxConfig = toml::from_str(&content)?;

    let crate_name = input_path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();

    generate_all(&config, &crate_name)
}

/// Generate artifacts and write them to a directory.
///
/// Files are written only if their content has changed, preserving mtime for
/// caching.
pub fn generate_to_dir(
    config: &BloxConfig,
    crate_name: &str,
    output_dir: &Path,
) -> anyhow::Result<Vec<String>> {
    std::fs::create_dir_all(output_dir)?;

    let files = generate_all(config, crate_name)?;
    let mut written = Vec::new();

    for (filename, content) in files {
        let path = output_dir.join(&filename);
        let needs_write = if path.exists() {
            std::fs::read_to_string(&path)? != content
        } else {
            true
        };

        if needs_write {
            std::fs::write(&path, &content)?;
            written.push(filename);
        }
    }

    Ok(written)
}

pub fn generate_system_wiring_from_toml(
    system_path: &Path,
    workspace_root: &Path,
) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(system_path)?;
    let config: SystemConfig = toml::from_str(&content)?;

    // Discover all blox.toml files in the workspace.
    let mut blox_configs = BTreeMap::new();
    for entry in walkdir::WalkDir::new(workspace_root)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if entry.file_name() == "blox.toml" {
            let blox_content = std::fs::read_to_string(entry.path())?;
            let blox_config: BloxConfig = toml::from_str(&blox_content)?;
            // Use the parent directory name as the key (e.g. "ping" for crates/bloxes/ping/blox.toml)
            // But the system.toml references blox crates by their crate name (e.g. "ping-blox")
            // so we need to derive the crate name from the Cargo.toml in the same directory.
            let dir = entry.path().parent().unwrap();
            let cargo_toml_path = dir.join("Cargo.toml");
            let key = if cargo_toml_path.exists() {
                let cargo_content = std::fs::read_to_string(&cargo_toml_path)?;
                // Parse [package] name = "..." from Cargo.toml
                cargo_content
                    .lines()
                    .find_map(|line| {
                        let trimmed = line.trim();
                        if trimmed.starts_with("name = ") {
                            let name = trimmed
                                .strip_prefix("name = ")
                                .unwrap()
                                .trim()
                                .trim_matches('"');
                            Some(name.to_string())
                        } else {
                            None
                        }
                    })
                    .unwrap_or_else(|| dir.file_name().unwrap().to_string_lossy().to_string())
            } else {
                dir.file_name().unwrap().to_string_lossy().to_string()
            };
            blox_configs.insert(key, blox_config);
        }
    }

    // Infer active features from the system.toml + blox configs.
    //
    // When an actor has a `source = "factory"` injection and the blox's
    // blox.toml declares a `feature` (e.g. "dynamic"), that feature must be
    // enabled in the app's Cargo.toml for the generated code to compile.
    //
    // We also fall back to reading the existing Cargo.toml (if any) so that
    // manually-specified features are preserved during incremental regen.
    let inferred_features = infer_active_features(&config, &blox_configs);
    let existing_features = read_app_cargo_features(system_path)?;
    let active_features = merge_features(inferred_features, existing_features);

    let generated = system_wiring::generate(&config, &blox_configs, &active_features)?;
    Ok(generated)
}

/// Parse the Cargo.toml in the same directory as `system_path` and extract
/// the features enabled on each dependency.
///
/// Returns a map from crate name (e.g. `"pool-blox"`) to the set of enabled
/// feature names (e.g. `{"std", "dynamic"}`).
fn read_app_cargo_features(
    system_path: &Path,
) -> anyhow::Result<BTreeMap<String, BTreeSet<String>>> {
    let cargo_toml_path = system_path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("system.toml has no parent directory"))?
        .join("Cargo.toml");

    if !cargo_toml_path.exists() {
        // No Cargo.toml — assume all features are enabled (generous default).
        return Ok(BTreeMap::new());
    }

    let content = std::fs::read_to_string(&cargo_toml_path)?;
    let parsed: toml::Value = toml::from_str(&content)?;

    let mut result = BTreeMap::new();

    // Walk [dependencies] and [dev-dependencies] tables.
    for section in ["dependencies", "dev-dependencies"] {
        if let Some(deps) = parsed.get(section).and_then(|v| v.as_table()) {
            for (crate_name, dep_value) in deps {
                // Format: crate = { workspace = true, features = ["std", "dynamic"] }
                if let Some(features) = dep_value.get("features").and_then(|f| f.as_array()) {
                    let feature_set: BTreeSet<String> = features
                        .iter()
                        .filter_map(|f| f.as_str().map(|s| s.to_string()))
                        .collect();
                    if !feature_set.is_empty() {
                        result.insert(crate_name.clone(), feature_set);
                    }
                }
            }
        }
    }

    Ok(result)
}

/// Infer which Cargo features should be enabled on each blox dependency based
/// on the system.toml and the blox configs.
///
/// Currently this detects:
/// - `dynamic` feature: when an actor has a `source = "factory"` injection
///   and the blox's blox.toml declares `feature = "dynamic"`.
///
/// Returns a map from crate name (e.g. `"pool-blox"`) to the set of features.
fn infer_active_features(
    config: &SystemConfig,
    blox_configs: &BTreeMap<String, BloxConfig>,
) -> BTreeMap<String, BTreeSet<String>> {
    let mut result = BTreeMap::new();

    for actor in &config.actors {
        // Check if this actor has a factory injection.
        let has_factory = actor.inject.values().any(|src| src.source == "factory");

        if has_factory {
            if let Some(blox_config) = blox_configs.get(&actor.blox) {
                // Look for feature declarations in the blox config.
                // The `feature` field on context or event indicates a
                // feature-gated variant. We activate it.
                if let Some(ctx) = &blox_config.context {
                    if let Some(feat) = &ctx.feature {
                        result
                            .entry(actor.blox.clone())
                            .or_insert_with(BTreeSet::new)
                            .insert(feat.clone());
                    }
                }
                if let Some(event) = &blox_config.event {
                    if let Some(feat) = &event.feature {
                        result
                            .entry(actor.blox.clone())
                            .or_insert_with(BTreeSet::new)
                            .insert(feat.clone());
                    }
                }
            }
        }
    }

    result
}

/// Merge two feature maps. Values from `extra` are added to `base` without
/// removing existing entries.
fn merge_features(
    mut base: BTreeMap<String, BTreeSet<String>>,
    extra: BTreeMap<String, BTreeSet<String>>,
) -> BTreeMap<String, BTreeSet<String>> {
    for (k, v) in extra {
        base.entry(k).or_default().extend(v);
    }
    base
}

pub fn generate_cargo_toml(system_path: &Path, workspace_root: &Path) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(system_path)?;
    let config: SystemConfig = toml::from_str(&content)?;

    // Discover all blox.toml files (same logic as generate_system_wiring_from_toml).
    let mut blox_configs = BTreeMap::new();
    for entry in walkdir::WalkDir::new(workspace_root)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if entry.file_name() == "blox.toml" {
            let blox_content = std::fs::read_to_string(entry.path())?;
            let blox_config: BloxConfig = toml::from_str(&blox_content)?;
            let dir = entry.path().parent().unwrap();
            let cargo_toml_path = dir.join("Cargo.toml");
            let key = if cargo_toml_path.exists() {
                let cargo_content = std::fs::read_to_string(&cargo_toml_path)?;
                cargo_content
                    .lines()
                    .find_map(|line| {
                        let trimmed = line.trim();
                        if trimmed.starts_with("name = ") {
                            let name = trimmed
                                .strip_prefix("name = ")
                                .unwrap()
                                .trim()
                                .trim_matches('"');
                            Some(name.to_string())
                        } else {
                            None
                        }
                    })
                    .unwrap_or_else(|| dir.file_name().unwrap().to_string_lossy().to_string())
            } else {
                dir.file_name().unwrap().to_string_lossy().to_string()
            };
            blox_configs.insert(key, blox_config);
        }
    }

    // Infer active features.
    let inferred = infer_active_features(&config, &blox_configs);
    let existing = read_app_cargo_features(system_path)?;
    let active_features = merge_features(inferred, existing);

    // Collect dependencies.
    // Each entry is (crate_name, features, is_workspace_dep).
    // is_workspace_dep = true → use `{ workspace = true, features = [...] }`
    // is_workspace_dep = false → use inline version spec.
    let mut deps: BTreeMap<String, (Vec<String>, bool)> = BTreeMap::new();

    // ── Always-required deps ───────────────────────────────────────────────
    deps.insert("bloxide-core".to_string(), (vec!["std".to_string()], true));
    deps.insert("bloxide-log".to_string(), (vec!["log".to_string()], true));
    deps.insert(
        "bloxide-supervisor".to_string(),
        (vec!["std".to_string()], true),
    );

    // ── Runtime-specific deps ──────────────────────────────────────────────
    match config.system.runtime.as_str() {
        "tokio" => {
            deps.insert("bloxide-tokio".to_string(), (vec![], true));
            deps.insert("tokio".to_string(), (vec![], true));
            deps.insert("tracing".to_string(), (vec![], true));
            deps.insert("tracing-subscriber".to_string(), (vec![], true));
            deps.insert("tracing-log".to_string(), (vec![], true));
        }
        "embassy" => {
            deps.insert(
                "bloxide-embassy".to_string(),
                (vec!["std".to_string()], true),
            );
            // embassy crates are NOT workspace deps — inline version specs.
            deps.insert(
                "embassy-executor".to_string(),
                (
                    vec!["arch-std".to_string(), "executor-thread".to_string()],
                    false,
                ),
            );
            deps.insert("embassy-sync".to_string(), (vec![], false));
            deps.insert(
                "embassy-time".to_string(),
                (
                    vec!["std".to_string(), "generic-queue-8".to_string()],
                    false,
                ),
            );
            deps.insert(
                "critical-section".to_string(),
                (vec!["std".to_string()], false),
            );
            deps.insert("static_cell".to_string(), (vec![], true));
            deps.insert("tracing".to_string(), (vec![], true));
            deps.insert("tracing-subscriber".to_string(), (vec![], true));
        }
        "test" => {
            // Test runtime — minimal deps.
        }
        other => {
            eprintln!("bloxide: warning: unknown runtime '{}'", other);
        }
    }

    // ── Per-actor deps ─────────────────────────────────────────────────────
    for actor in &config.actors {
        let is_timer = actor.kind.as_deref() == Some("timer");

        // The blox crate itself.
        let blox_name = &actor.blox;
        let features = active_features
            .get(blox_name)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .collect::<Vec<_>>();
        deps.insert(blox_name.clone(), (features, true));

        if is_timer {
            // bloxide-timer is already added as the blox crate.
            // Ensure std feature is included.
            let entry = deps.get_mut("bloxide-timer").unwrap();
            if !entry.0.contains(&"std".to_string()) {
                entry.0.push("std".to_string());
            }
        }

        // Message crates: extract from the blox.toml's event.mailboxes[].message_path.
        if let Some(blox_config) = blox_configs.get(blox_name) {
            if let Some(event) = &blox_config.event {
                for mailbox in &event.mailboxes {
                    if let Some(path) = &mailbox.message_path {
                        // message_path is like "ping_pong_messages::PingPongMsg"
                        // Extract the crate name (first segment) and convert
                        // underscores to hyphens for Cargo.toml.
                        if let Some(crate_part) = path.split("::").next() {
                            let cargo_name = crate_part.replace('_', "-");
                            deps.entry(cargo_name).or_insert_with(|| (vec![], true));
                        }
                    }
                }
            }

            // Also check context.imports for message crate references.
            if let Some(ctx) = &blox_config.context {
                for imp in &ctx.imports {
                    // imports are like "ping_pong_messages::PingPongMsg"
                    // or "bloxide_timer::{TimerCommand, TimerId}"
                    if let Some(crate_part) = imp.split("::").next() {
                        // Skip std/alloc/bloxide_core etc — only add external
                        // message crates (they end with "_messages").
                        if crate_part.ends_with("_messages") {
                            let cargo_name = crate_part.replace('_', "-");
                            deps.entry(cargo_name).or_insert_with(|| (vec![], true));
                        }
                    }
                }
            }
        }

        // Behavior impl crate.
        if let Some(impl_crate) = &actor.behavior_impl {
            // behavior_impl is already in hyphen format (e.g. "ping-pong-impl").
            deps.entry(impl_crate.clone())
                .or_insert_with(|| (vec![], true));
        }

        // Factory injection crates.
        for src in actor.inject.values() {
            if src.source == "factory" {
                if let Some(crate_name) = &src.crate_name {
                    // crate_name uses underscores (e.g. "tokio_pool_demo_impl")
                    // — convert to hyphens for Cargo.toml.
                    let cargo_name = crate_name.replace('_', "-");
                    deps.entry(cargo_name).or_insert_with(|| (vec![], true));
                }
            }
        }
    }

    // ── Emit Cargo.toml ─────────────────────────────────────────────────────
    let app_name = config.system.name.clone().unwrap_or_else(|| {
        system_path
            .parent()
            .and_then(|p| p.file_name())
            .and_then(|n| n.to_str())
            .unwrap_or("bloxide-app")
            .to_string()
    });

    let mut out = String::new();
    out.push_str("# Copyright 2025 Bloxide, all rights reserved\n");
    out.push_str("# Auto-generated by `cargo blox generate` from system.toml.\n");
    out.push_str("# Do not edit manually — regenerate with `cargo blox generate`.\n\n");
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{}\"\n", app_name));
    out.push_str("version.workspace = true\n");
    out.push_str("edition.workspace = true\n");
    out.push_str("publish = false\n\n");
    out.push_str("[dependencies]\n");

    for (crate_name, (features, is_workspace)) in &deps {
        if *is_workspace {
            if features.is_empty() {
                out.push_str(&format!("{} = {{ workspace = true }}\n", crate_name));
            } else {
                let feat_list = features
                    .iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "{} = {{ workspace = true, features = [{}] }}\n",
                    crate_name, feat_list
                ));
            }
        } else {
            // Inline version specs for non-workspace deps (embassy crates).
            let feat_list = if features.is_empty() {
                String::new()
            } else {
                let items = features
                    .iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(", features = [{}]", items)
            };
            match crate_name.as_str() {
                "embassy-executor" => {
                    out.push_str(&format!(
                        "embassy-executor = {{ version = \"0.9\"{} }}\n",
                        feat_list
                    ));
                }
                "embassy-sync" => {
                    out.push_str(&format!(
                        "embassy-sync = {{ version = \"0.7\"{} }}\n",
                        feat_list
                    ));
                }
                "embassy-time" => {
                    out.push_str(&format!(
                        "embassy-time = {{ version = \"0.5\"{} }}\n",
                        feat_list
                    ));
                }
                "critical-section" => {
                    out.push_str(&format!(
                        "critical-section = {{ version = \"1.2\"{} }}\n",
                        feat_list
                    ));
                }
                _ => {
                    // Fallback: try workspace dep.
                    if features.is_empty() {
                        out.push_str(&format!("{} = {{ workspace = true }}\n", crate_name));
                    } else {
                        out.push_str(&format!(
                            "{} = {{ workspace = true, features = [{}] }}\n",
                            crate_name,
                            features
                                .iter()
                                .map(|f| format!("\"{}\"", f))
                                .collect::<Vec<_>>()
                                .join(", ")
                        ));
                    }
                }
            }
        }
    }

    Ok(out)
}
