// Copyright 2025 Bloxide, all rights reserved
//! Public API for bloxide-codegen — generate Rust source from blox.toml specs.

pub mod ctx;
mod events;
mod mailboxes;
mod messages;
pub mod schema;
pub mod spec_skeleton;
pub mod system_spec;
pub mod system_wiring;
mod topology;
pub mod util;

use schema::{BloxConfig, SystemConfig};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

/// Generate all artifacts from a parsed `BloxConfig`.
///
/// Returns a vector of `(filename, content)` pairs.
pub fn generate_all(
    config: &BloxConfig,
    crate_name: &str,
) -> anyhow::Result<Vec<(String, String)>> {
    let mut files = Vec::new();

    if let Some(messages) = &config.messages {
        for msg in messages {
            let code = messages::generate(msg)?;
            files.push((format!("messages_{}.rs", msg.name.to_lowercase()), code));
        }
    }

    if let Some(event) = &config.event {
        let code = events::generate(event)?;
        files.push(("events.rs".to_string(), code));
    }

    if let Some(topology) = &config.topology {
        let actor_name = config.actor.as_ref().map(|a| a.name.as_str());
        let has_feature = config
            .context
            .as_ref()
            .and_then(|c| c.feature.as_ref())
            .is_some();
        let code = topology::generate(topology, actor_name, crate_name, has_feature)?;
        files.push(("topology.rs".to_string(), code));
    }

    if let Some(context) = &config.context {
        let code = ctx::generate(context, crate_name)?;
        files.push(("ctx.rs".to_string(), code));
    }

    // spec_skeleton requires actor + topology + context, plus event info.
    // Event info can come from an [event] section OR from the context config
    // (event_name/event_generics fields — used when the event enum is
    // hand-written in a separate crate).
    if let (Some(actor), Some(topology), Some(context)) =
        (&config.actor, &config.topology, &config.context)
    {
        if context.event_name.is_some() || config.event.is_some() {
            // Blox-crate-level codegen ALWAYS produces stub spec_skeletons.
            // Concrete action closures are generated exclusively at the system
            // level from system.toml via generate_concrete_spec_files.
            let code = spec_skeleton::generate(
                actor,
                topology,
                context,
                config.event.as_ref(),
                crate_name,
                "crate",
                &spec_skeleton::resolve_action,
                None,
            )?;
            files.push(("spec_skeleton.rs".to_string(), code));
        }
    }

    if let Some(mailboxes) = &config.mailboxes {
        let code = mailboxes::generate(mailboxes)?;
        files.push(("mailboxes_impls.rs".to_string(), code));
    }

    // Generate mod.rs that re-exports all generated submodules
    if !files.is_empty() {
        let mod_rs = generate_mod_rs(&files);
        files.push(("mod.rs".to_string(), mod_rs));
    }

    Ok(files)
}

fn generate_mod_rs(files: &[(String, String)]) -> String {
    let mut lines = vec![
        "// Copyright 2025 Bloxide, all rights reserved".to_string(),
        "// Auto-generated module.".to_string(),
        "// Files in this directory are generated by bloxide-codegen.".to_string(),
    ];

    for (filename, _) in files {
        if filename == "mod.rs" {
            continue;
        }
        let stem = filename.strip_suffix(".rs").unwrap_or(filename);
        // topology.rs emits #[macro_export] macros (e.g. *_handler_table!).
        // #[macro_use] makes them available to sibling modules (spec_skeleton.rs).
        if stem == "topology" {
            lines.push("#[macro_use]".to_string());
        }
        lines.push(format!("pub mod {stem};"));
        lines.push(format!("#[allow(unused_imports)] pub use {stem}::*;"));
    }

    lines.join("\n") + "\n"
}

/// Parse a `blox.toml` file and generate all artifacts.
///
/// The crate name is inferred from the parent directory name.
pub fn generate_from_toml(input_path: &Path) -> anyhow::Result<Vec<(String, String)>> {
    let content = std::fs::read_to_string(input_path)?;
    let config: BloxConfig = toml::from_str(&content)?;

    let crate_name = input_path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();

    generate_all(&config, &crate_name)
}

pub fn generate_system_wiring_from_toml(
    system_path: &Path,
    workspace_root: &Path,
) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(system_path)?;
    let config: SystemConfig = toml::from_str(&content)?;

    // Discover all blox.toml files in the workspace (excluding target/).
    let blox_configs = util::discover_blox_configs(workspace_root)?;

    // Infer active features from the system.toml + blox configs.
    //
    // When an actor has a `source = "factory"` injection and the blox's
    // blox.toml declares a `feature` (e.g. "dynamic"), that feature must be
    // enabled in the app's Cargo.toml for the generated code to compile.
    //
    // We also fall back to reading the existing Cargo.toml (if any) so that
    // manually-specified features are preserved during incremental regen.
    let inferred_features = infer_active_features(&config, &blox_configs);
    let existing_features = read_app_cargo_features(system_path)?;
    let active_features = merge_features(inferred_features, existing_features);

    let generated = system_wiring::generate(&config, &blox_configs, &active_features)?;

    // Generate concrete spec_skeleton.rs files for each actor and write them
    // to the app's src/generated/ directory. Also generate a mod.rs that
    // declares all the spec modules.
    let app_dir = system_path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("system.toml has no parent directory"))?;
    let generated_dir = app_dir.join("src").join("generated");

    // Collect all spec files: actors + supervisors
    let mut all_spec_files = Vec::new();

    // Generate concrete specs for regular actors
    if !config.actors.is_empty() {
        let spec_files = system_spec::generate_concrete_spec_files(&blox_configs, &config.actors)?;
        all_spec_files.extend(spec_files);
    }

    // Generate concrete specs for supervisors referenced in [[supervision]]
    for sup in &config.supervision {
        let supervisor_crate = &sup.supervisor;
        if let Some(blox_config) = blox_configs.get(supervisor_crate) {
            let blox_crate_path = format!("::{}", supervisor_crate.replace('-', "_"));
            let code = system_spec::generate_concrete_spec_skeleton(
                blox_config,
                None, // supervisors don't have impl_crate
                supervisor_crate,
                &blox_crate_path,
                None, // no active feature for supervisor
            )?;
            // Use the supervisor crate name as the identifier (the loop
            // below appends the _spec_skeleton suffix).
            let module_name = supervisor_crate.replace('-', "_").to_lowercase();
            all_spec_files.push((module_name, code));
        }
    }

    if !all_spec_files.is_empty() {
        std::fs::create_dir_all(&generated_dir)?;
        let mut mod_content = String::from(
            "// Copyright 2025 Bloxide, all rights reserved\n\
             // Auto-generated module. Do not edit manually.\n",
        );
        for (actor_name, spec_code) in &all_spec_files {
            let module_name = actor_name.replace('-', "_").to_lowercase() + "_spec_skeleton";
            let filename = format!("{}.rs", module_name);
            std::fs::write(generated_dir.join(&filename), spec_code)?;
            mod_content.push_str(&format!("pub mod {};\n", module_name));
            mod_content.push_str(&format!(
                "#[allow(unused_imports)]\npub use {}::*;\n",
                module_name
            ));
        }
        std::fs::write(generated_dir.join("mod.rs"), &mod_content)?;
    }

    Ok(generated)
}

/// Parse the Cargo.toml in the same directory as `system_path` and extract
/// the features enabled on each dependency.
///
/// Returns a map from crate name (e.g. `"pool-blox"`) to the set of enabled
/// feature names (e.g. `{"std", "dynamic"}`).
fn read_app_cargo_features(
    system_path: &Path,
) -> anyhow::Result<BTreeMap<String, BTreeSet<String>>> {
    let cargo_toml_path = system_path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("system.toml has no parent directory"))?
        .join("Cargo.toml");

    if !cargo_toml_path.exists() {
        // No Cargo.toml — assume all features are enabled (generous default).
        return Ok(BTreeMap::new());
    }

    let content = std::fs::read_to_string(&cargo_toml_path)?;
    let parsed: toml::Value = toml::from_str(&content)?;

    let mut result = BTreeMap::new();

    // Walk [dependencies] and [dev-dependencies] tables.
    for section in ["dependencies", "dev-dependencies"] {
        if let Some(deps) = parsed.get(section).and_then(|v| v.as_table()) {
            for (crate_name, dep_value) in deps {
                // Format: crate = { workspace = true, features = ["std", "dynamic"] }
                if let Some(features) = dep_value.get("features").and_then(|f| f.as_array()) {
                    let feature_set: BTreeSet<String> = features
                        .iter()
                        .filter_map(|f| f.as_str().map(|s| s.to_string()))
                        .collect();
                    if !feature_set.is_empty() {
                        result.insert(crate_name.clone(), feature_set);
                    }
                }
            }
        }
    }

    Ok(result)
}

/// Infer which Cargo features should be enabled on each blox dependency based
/// on the system.toml and the blox configs.
///
/// Currently this detects:
/// - `dynamic` feature: when an actor has a `source = "factory"` injection
///   and the blox's blox.toml declares `feature = "dynamic"`.
///
/// Returns a map from crate name (e.g. `"pool-blox"`) to the set of features.
fn infer_active_features(
    config: &SystemConfig,
    blox_configs: &BTreeMap<String, BloxConfig>,
) -> BTreeMap<String, BTreeSet<String>> {
    let mut result = BTreeMap::new();

    for actor in &config.actors {
        // 1. Explicit features declared in system.toml.
        for feat in &actor.features {
            result
                .entry(actor.blox.clone())
                .or_insert_with(BTreeSet::new)
                .insert(feat.clone());
        }

        // 2. Inferred from factory injection: if the actor has a factory
        //    injection, activate the feature declared on the blox's context
        //    or event config. This is a convenience so simple cases don't
        //    need explicit features in system.toml.
        let has_factory = actor.inject.values().any(|src| src.source == "factory");

        if has_factory {
            if let Some(blox_config) = blox_configs.get(&actor.blox) {
                if let Some(ctx) = &blox_config.context {
                    if let Some(feat) = &ctx.feature {
                        result
                            .entry(actor.blox.clone())
                            .or_insert_with(BTreeSet::new)
                            .insert(feat.clone());
                    }
                }
                if let Some(event) = &blox_config.event {
                    if let Some(feat) = &event.feature {
                        result
                            .entry(actor.blox.clone())
                            .or_insert_with(BTreeSet::new)
                            .insert(feat.clone());
                    }
                }
            }
        }
    }

    result
}

/// Merge two feature maps. Values from `extra` are added to `base` without
/// removing existing entries.
fn merge_features(
    mut base: BTreeMap<String, BTreeSet<String>>,
    extra: BTreeMap<String, BTreeSet<String>>,
) -> BTreeMap<String, BTreeSet<String>> {
    for (k, v) in extra {
        base.entry(k).or_default().extend(v);
    }
    base
}

pub fn generate_cargo_toml(system_path: &Path, workspace_root: &Path) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(system_path)?;
    let config: SystemConfig = toml::from_str(&content)?;

    // Discover all blox.toml files (same logic as generate_system_wiring_from_toml).
    let blox_configs = util::discover_blox_configs(workspace_root)?;

    // Infer active features.
    let inferred = infer_active_features(&config, &blox_configs);
    let existing = read_app_cargo_features(system_path)?;
    let active_features = merge_features(inferred, existing);

    // Collect dependencies.
    // Each entry is (crate_name, features, is_workspace_dep).
    // is_workspace_dep = true → use `{ workspace = true, features = [...] }`
    // is_workspace_dep = false → use inline version spec.
    let mut deps: BTreeMap<String, (Vec<String>, bool)> = BTreeMap::new();

    // ── Always-required deps ───────────────────────────────────────────────
    deps.insert("bloxide-core".to_string(), (vec!["std".to_string()], true));
    deps.insert("bloxide-log".to_string(), (vec!["log".to_string()], true));
    deps.insert(
        "bloxide-supervisor".to_string(),
        (vec!["std".to_string()], true),
    );
    // The system-level generated supervisor spec imports types from
    // bloxide-child-management (ChildAction, ChildGroup), so it must be
    // a dependency of every app that uses the supervisor.
    deps.insert(
        "bloxide-child-management".to_string(),
        (vec!["std".to_string()], true),
    );

    // ── Runtime-specific deps ──────────────────────────────────────────────
    match config.system.runtime.as_str() {
        "tokio" => {
            deps.insert("bloxide-tokio".to_string(), (vec![], true));
            deps.insert("tokio".to_string(), (vec![], true));
            deps.insert("tracing".to_string(), (vec![], true));
            deps.insert("tracing-subscriber".to_string(), (vec![], true));
            deps.insert("tracing-log".to_string(), (vec![], true));
        }
        "embassy" => {
            deps.insert(
                "bloxide-embassy".to_string(),
                (vec!["std".to_string()], true),
            );
            // embassy crates are NOT workspace deps — inline version specs.
            deps.insert(
                "embassy-executor".to_string(),
                (
                    vec!["arch-std".to_string(), "executor-thread".to_string()],
                    false,
                ),
            );
            deps.insert("embassy-sync".to_string(), (vec![], false));
            deps.insert(
                "embassy-time".to_string(),
                (
                    vec!["std".to_string(), "generic-queue-8".to_string()],
                    false,
                ),
            );
            deps.insert(
                "critical-section".to_string(),
                (vec!["std".to_string()], false),
            );
            deps.insert("static_cell".to_string(), (vec![], true));
            deps.insert("tracing".to_string(), (vec![], true));
            deps.insert("tracing-subscriber".to_string(), (vec![], true));
        }
        "test" => {
            // Test runtime — minimal deps.
        }
        other => {
            eprintln!("bloxide: warning: unknown runtime '{}'", other);
        }
    }

    // ── Per-actor deps ─────────────────────────────────────────────────────
    for actor in &config.actors {
        let is_timer = actor.kind.as_deref() == Some("timer");

        // The blox crate itself.
        let blox_name = &actor.blox;
        let features = active_features
            .get(blox_name)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .collect::<Vec<_>>();
        deps.insert(blox_name.clone(), (features, true));

        if is_timer {
            // bloxide-timer is already added as the blox crate.
            // Ensure std feature is included.
            let entry = deps.get_mut("bloxide-timer").unwrap();
            if !entry.0.contains(&"std".to_string()) {
                entry.0.push("std".to_string());
            }
        }

        // Message crates: extract from the blox.toml's event.mailboxes[].message_path.
        // A message_path may reference multiple crates in nested generics, e.g.
        // "pool_messages::SpawnedWorker<bloxide_peers::PeerCtrl<...>, R>" — we
        // need all of them as Cargo.toml dependencies.
        if let Some(blox_config) = blox_configs.get(blox_name) {
            if let Some(event) = &blox_config.event {
                for mailbox in &event.mailboxes {
                    let path = mailbox.message_path.as_deref().unwrap_or(&mailbox.message);
                    for crate_part in system_wiring::extract_crates_from_path(path) {
                        let cargo_name = crate_part.replace('_', "-");
                        deps.entry(cargo_name).or_insert_with(|| (vec![], true));
                    }
                }
            }

            // Also check context.imports for message crate references.
            if let Some(ctx) = &blox_config.context {
                for imp in &ctx.imports {
                    // imports are like "ping_pong_messages::PingPongMsg"
                    // or "bloxide_timer::{TimerCommand, TimerId}"
                    if let Some(crate_part) = imp.split("::").next() {
                        // Skip std/alloc/bloxide_core etc — only add external
                        // message crates (they end with "_messages").
                        if crate_part.ends_with("_messages") {
                            let cargo_name = crate_part.replace('_', "-");
                            deps.entry(cargo_name).or_insert_with(|| (vec![], true));
                        }
                    }
                }

                // Add context action crates — these are the crates that
                // provide the concrete action functions referenced in the
                // generated spec_skeleton.rs (e.g. blox_ctx_rounds,
                // blox_ctx_ping_pong, bloxide_timer).
                for action in &ctx.actions {
                    if let Some(ref crate_name) = action.crate_name {
                        let cargo_name = crate_name.replace('_', "-");
                        deps.entry(cargo_name).or_insert_with(|| (vec![], true));
                    }
                }
            }
        }

        // Concrete action impl crate (Phase 3 system codegen).
        // Forward the actor's features to the impl crate so that
        // feature-gated action functions are compiled in.
        if let Some(impl_crate) = &actor.impl_crate {
            let cargo_name = impl_crate.replace('_', "-");
            let entry = deps.entry(cargo_name).or_insert_with(|| (vec![], true));
            for feat in &actor.features {
                if !entry.0.contains(feat) {
                    entry.0.push(feat.clone());
                }
            }
        }

        // Factory injection crates.
        for src in actor.inject.values() {
            if src.source == "factory" {
                if let Some(crate_name) = &src.crate_name {
                    // crate_name uses underscores (e.g. "tokio_pool_demo_impl")
                    // — convert to hyphens for Cargo.toml.
                    let cargo_name = crate_name.replace('_', "-");
                    deps.entry(cargo_name).or_insert_with(|| (vec![], true));
                }
            }
        }
    }

    // ── Emit Cargo.toml ─────────────────────────────────────────────────────
    let app_name = config.system.name.clone().unwrap_or_else(|| {
        system_path
            .parent()
            .and_then(|p| p.file_name())
            .and_then(|n| n.to_str())
            .unwrap_or("bloxide-app")
            .to_string()
    });

    let mut out = String::new();
    out.push_str("# Copyright 2025 Bloxide, all rights reserved\n");
    out.push_str("# Auto-generated by `cargo blox generate` from system.toml.\n");
    out.push_str("# Do not edit manually — regenerate with `cargo blox generate`.\n\n");
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{}\"\n", app_name));
    out.push_str("version.workspace = true\n");
    out.push_str("edition.workspace = true\n");
    out.push_str("publish = false\n\n");
    out.push_str("[dependencies]\n");

    for (crate_name, (features, is_workspace)) in &deps {
        if *is_workspace {
            if features.is_empty() {
                out.push_str(&format!("{} = {{ workspace = true }}\n", crate_name));
            } else {
                let feat_list = features
                    .iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "{} = {{ workspace = true, features = [{}] }}\n",
                    crate_name, feat_list
                ));
            }
        } else {
            // Inline version specs for non-workspace deps (embassy crates).
            let feat_list = if features.is_empty() {
                String::new()
            } else {
                let items = features
                    .iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(", features = [{}]", items)
            };
            match crate_name.as_str() {
                "embassy-executor" => {
                    out.push_str(&format!(
                        "embassy-executor = {{ version = \"0.9\"{} }}\n",
                        feat_list
                    ));
                }
                "embassy-sync" => {
                    out.push_str(&format!(
                        "embassy-sync = {{ version = \"0.7\"{} }}\n",
                        feat_list
                    ));
                }
                "embassy-time" => {
                    out.push_str(&format!(
                        "embassy-time = {{ version = \"0.5\"{} }}\n",
                        feat_list
                    ));
                }
                "critical-section" => {
                    out.push_str(&format!(
                        "critical-section = {{ version = \"1.2\"{} }}\n",
                        feat_list
                    ));
                }
                _ => {
                    // Fallback: try workspace dep.
                    if features.is_empty() {
                        out.push_str(&format!("{} = {{ workspace = true }}\n", crate_name));
                    } else {
                        out.push_str(&format!(
                            "{} = {{ workspace = true, features = [{}] }}\n",
                            crate_name,
                            features
                                .iter()
                                .map(|f| format!("\"{}\"", f))
                                .collect::<Vec<_>>()
                                .join(", ")
                        ));
                    }
                }
            }
        }
    }

    Ok(out)
}
