// Copyright 2025 Bloxide, all rights reserved.
//! Generate MachineSpec skeleton from actor, topology, context, and event config.
//!
//! When `context.feature` is set, emits paired `#[cfg]` variants with different
//! generics, event types, and mailboxes types. The StateFns are generated as
//! associated constants inside `impl` blocks using raw `StateRule { ... }` struct
//! literals emitted directly from TOML.

use quote::{format_ident, quote, ToTokens};

use crate::schema::{ActorConfig, ContextConfig, EventConfig, TopologyConfig};
use crate::util::to_snake_case;

const HEADER: &str = "// Copyright 2025 Bloxide, all rights reserved\n// Auto-generated by bloxide-codegen. Do not edit manually.\n";

/// Parameters for a single variant of the spec skeleton.
struct VariantParams {
    /// The cfg attribute string (e.g. "not(feature = \"dynamic\")" or "feature = \"dynamic\"").
    /// None when no feature-gating.
    cfg_attr: Option<String>,
    /// The spec generics for this variant (e.g. `<R: BloxRuntime>` or `<R: BloxRuntime, B: SomeTrait + 'static>`).
    spec_generics: syn::Generics,
    /// The ctx type for this variant (e.g. `SupervisorCtx<R>` or `SupervisorCtx<R, F>`).
    ctx_ty: proc_macro2::TokenStream,
    /// The event type for this variant (e.g. `SupervisorEvent<R>` or `SupervisorEvent<R, F>`).
    event_ty: proc_macro2::TokenStream,
    /// The mailboxes type for this variant.
    mailboxes_ty: proc_macro2::TokenStream,
    /// The event type params as a list of idents (e.g. `["R"]` or `["R", "F"]`).
    event_type_params: Vec<String>,
    /// The ctx type params as a list of idents (e.g. `["R"]` or `["R", "F"]`).
    ctx_type_params: Vec<String>,
    /// Feature filter: None = non-feature transitions, Some(feat) = feature transitions.
    feature_filter: Option<String>,
    /// Extra imports specific to this variant (raw use paths).
    extra_imports: Vec<String>,
}

/// Replace placeholders {R}, {Ctx}, {Event} in a string with variant-specific values.
pub(crate) fn replace_placeholders(
    s: &str,
    ctx_type_str: &str,
    event_type_str: &str,
    type_params: &[String],
) -> String {
    let result = s.replace("{Ctx}", ctx_type_str);
    let result = result.replace("{Event}", event_type_str);
    // {R} → first type param (or "R" if no type params)
    let first_param = type_params.first().map(|s| s.as_str()).unwrap_or("R");
    result.replace("{R}", first_param)
}

/// Resolve an action string to a token stream.
///
/// When the action string starts with `Self::` (e.g. `Self::increment_round`),
/// generate a stub no-op closure instead of a function path reference.
/// The stub closures are no-ops that will be replaced by real implementations
/// in the system-level codegen.
///
/// For transition actions: `|_ctx, _ev| { /* stub: <name> */ ::bloxide_core::transition::ActionResult::Ok }`
/// For entry/exit actions: `|_ctx| { /* stub: <name> */ }`
///
/// Action strings that do NOT start with `Self::` (e.g. `handle_work_done` or
/// `bloxide_child_management::start_children`) are parsed as function path
/// references — these are real functions imported via `spec_imports`.
pub(crate) fn resolve_action(
    action: &str,
    ctx_type_str: &str,
    event_type_str: &str,
    type_params: &[String],
    _event_pattern: Option<&str>,
    is_transition: bool,
) -> proc_macro2::TokenStream {
    let resolved = replace_placeholders(action, ctx_type_str, event_type_str, type_params);

    if resolved.starts_with("Self::") {
        // Self:: prefix indicates an action method on the spec struct.
        // In Phase 2, actions are stub no-op closures — the real action
        // implementations live in the blox crate's actions.rs (or context
        // crates) and are tested there, not through the generated spec.
        let name = resolved.strip_prefix("Self::").unwrap_or(&resolved);
        if is_transition {
            quote! {
                |_ctx, _ev| { /* stub: #name */ ::bloxide_core::transition::ActionResult::Ok }
            }
        } else {
            quote! {
                |_ctx| { /* stub: #name */ }
            }
        }
    } else {
        // Real function path reference — parse as a path.
        syn::parse_str::<syn::Path>(&resolved)
            .map(|p| p.to_token_stream())
            .unwrap_or_else(|_| {
                let ident = format_ident!("{}", resolved);
                quote! { #ident }
            })
    }
}

/// Generate the StateFns associated constants for a variant.
#[allow(clippy::too_many_arguments)]
pub(crate) fn generate_state_fns_impl(
    topology: &TopologyConfig,
    state_enum_ident: &syn::Ident,
    spec_ident: &syn::Ident,
    ctx_type_str: &str,
    event_type_str: &str,
    type_params: &[String],
    spec_impl_generics: proc_macro2::TokenStream,
    spec_ty_generics: proc_macro2::TokenStream,
    spec_where_clause: Option<&syn::WhereClause>,
    feature_filter: Option<&str>,
    action_resolver: &dyn Fn(
        &str,
        &str,
        &str,
        &[String],
        Option<&str>,
        bool,
    ) -> proc_macro2::TokenStream,
) -> anyhow::Result<proc_macro2::TokenStream> {
    use crate::schema::{EntryExitConfig, TransitionConfig};
    use crate::topology::generate_state_rule;
    use std::collections::HashMap;

    // Build lookup maps, filtering by feature
    let trans_by_state: HashMap<String, Vec<&TransitionConfig>> = {
        let mut map: HashMap<String, Vec<&TransitionConfig>> = HashMap::new();
        for t in &topology.transitions {
            // Non-feature variant: include transitions with no `feature` attribute.
            // Feature variant: include ALL transitions (both gated and non-gated).
            if match feature_filter {
                None => t.feature.is_none(),
                Some(_) => true,
            } {
                map.entry(t.state.clone()).or_default().push(t);
            }
        }
        map
    };
    let entry_by_state: HashMap<String, Vec<&EntryExitConfig>> = {
        let mut map: HashMap<String, Vec<&EntryExitConfig>> = HashMap::new();
        for e in &topology.entry {
            // Same feature filtering as transitions
            if match feature_filter {
                None => e.feature.is_none(),
                Some(_) => true,
            } {
                map.entry(e.state.clone()).or_default().push(e);
            }
        }
        map
    };
    let exit_by_state: HashMap<String, Vec<&EntryExitConfig>> = {
        let mut map: HashMap<String, Vec<&EntryExitConfig>> = HashMap::new();
        for e in &topology.exit {
            if match feature_filter {
                None => e.feature.is_none(),
                Some(_) => true,
            } {
                map.entry(e.state.clone()).or_default().push(e);
            }
        }
        map
    };

    let mut consts = Vec::new();
    for state in &topology.states {
        let fns_ident = format_ident!("{}_FNS", to_snake_case(&state.name).to_ascii_uppercase());
        let state_trans = trans_by_state
            .get(&state.name)
            .map(|v| v.as_slice())
            .unwrap_or(&[]);
        let state_entry = entry_by_state
            .get(&state.name)
            .map(|v| v.as_slice())
            .unwrap_or(&[]);
        let state_exit = exit_by_state
            .get(&state.name)
            .map(|v| v.as_slice())
            .unwrap_or(&[]);

        // on_entry actions
        let entry_tokens: Vec<proc_macro2::TokenStream> = state_entry
            .first()
            .map(|ee| {
                ee.actions
                    .iter()
                    .map(|a| {
                        action_resolver(a, ctx_type_str, event_type_str, type_params, None, false)
                    })
                    .collect()
            })
            .unwrap_or_default();

        // on_exit actions
        let exit_tokens: Vec<proc_macro2::TokenStream> = state_exit
            .first()
            .map(|ee| {
                ee.actions
                    .iter()
                    .map(|a| {
                        action_resolver(a, ctx_type_str, event_type_str, type_params, None, false)
                    })
                    .collect()
            })
            .unwrap_or_default();

        // Transition rules — raw StateRule { ... } literals
        let trans_tokens: proc_macro2::TokenStream = if state_trans.is_empty() {
            quote! { &[] }
        } else {
            let rules: Vec<proc_macro2::TokenStream> = state_trans
                .iter()
                .map(|t| {
                    generate_state_rule(
                        t,
                        state_enum_ident,
                        ctx_type_str,
                        event_type_str,
                        type_params,
                        action_resolver,
                    )
                })
                .collect::<anyhow::Result<Vec<_>>>()?;
            quote! { &[#(#rules),*] }
        };

        consts.push(quote! {
            #[allow(unused_variables)]
            const #fns_ident: ::bloxide_core::spec::StateFns<Self> = ::bloxide_core::spec::StateFns {
                on_entry: &[#(#entry_tokens),*],
                on_exit: &[#(#exit_tokens),*],
                transitions: #trans_tokens,
            };
        });
    }

    Ok(quote! {
        impl #spec_impl_generics #spec_ident #spec_ty_generics #spec_where_clause {
            #(#consts)*
        }
    })
}

pub fn generate(
    actor: &ActorConfig,
    topology: &TopologyConfig,
    context: &ContextConfig,
    event: Option<&EventConfig>,
    _crate_name: &str,
    blox_crate_path: &str,
    action_resolver: &dyn Fn(
        &str,
        &str,
        &str,
        &[String],
        Option<&str>,
        bool,
    ) -> proc_macro2::TokenStream,
) -> anyhow::Result<String> {
    let actor_name = &actor.name;
    let spec_ident = format_ident!("{}", format!("{}Spec", actor_name));
    let state_ident = format_ident!("{}", format!("{}State", actor_name));

    // Track whether this is a system-level spec (blox_crate_path starts with "::").
    // For blox-level generation this is "crate"; for system-level it's e.g. "::ping_blox".
    let is_system_level = blox_crate_path.starts_with("::");

    // Parse the blox_crate_path into a syn::Path for use in quote! macros.
    let blox_crate_path: syn::Path = syn::parse_str(blox_crate_path)
        .map_err(|e| anyhow::anyhow!("invalid blox_crate_path '{}': {}", blox_crate_path, e))?;

    // Helper: translate a spec_import path that starts with `crate::` to use
    // blox_crate_path instead. Only replaces the leading `crate::`, not
    // occurrences in the middle of a path.
    let translate_crate_import = |imp: &str| -> String {
        if imp.starts_with("crate::") {
            format!(
                "{}::{}",
                blox_crate_path.to_token_stream(),
                &imp["crate::".len()..]
            )
        } else if imp == "crate" {
            blox_crate_path.to_token_stream().to_string()
        } else {
            imp.to_string()
        }
    };

    let handler_macro_name_str = format!(
        "{}_handler_table",
        to_snake_case(&format!("{}State", actor_name))
    );
    let handler_macro_ident = format_ident!("{}", handler_macro_name_str);

    let ctx_ident = format_ident!("{}", context.name);

    // ── Determine if feature-gated ──────────────────────────────────────────
    let has_feature = context.feature.is_some();

    // ── Collect shared data ──────────────────────────────────────────────────
    let initial_state = topology
        .states
        .iter()
        .find(|s| s.initial.unwrap_or(false))
        .map(|s| s.name.clone())
        .or_else(|| {
            topology
                .states
                .iter()
                .find(|s| !s.composite.unwrap_or(false))
                .map(|s| s.name.clone())
        });
    let initial_state_ident = if let Some(ref name) = initial_state {
        format_ident!("{}", name)
    } else {
        format_ident!("Init")
    };

    let error_states: Vec<_> = topology
        .states
        .iter()
        .filter(|s| s.error.unwrap_or(false))
        .map(|s| format_ident!("{}", s.name))
        .collect();

    let (is_error_param, is_error_body) = if error_states.is_empty() {
        (quote! { _state }, quote! { false })
    } else {
        (
            quote! { state },
            quote! { ::core::matches!(state, #state_ident::#(#error_states)|*) },
        )
    };

    // on_init body
    let on_init_body: proc_macro2::TokenStream = if let Some(ref body) = context.on_init {
        body.parse::<proc_macro2::TokenStream>()
            .map_err(|e| anyhow::anyhow!("invalid on_init body '{}': {}", body, e))?
    } else {
        quote! {}
    };
    let on_init_fn = if on_init_body.is_empty() {
        quote! { fn on_init_entry(_ctx: &mut Self::Ctx) {} }
    } else {
        quote! {
            fn on_init_entry(ctx: &mut Self::Ctx) {
                #on_init_body
            }
        }
    };

    // ── Build imports ─────────────────────────────────────────────────────────
    let mut use_stmts = vec![quote! { use ::core::marker::PhantomData; }];

    // BloxRuntime import — needed when generics include it
    let context_has_runtime = context
        .generics
        .as_ref()
        .map(|g| g.contains("BloxRuntime"))
        .unwrap_or(false);
    let event_generics_str: Option<&str> = event
        .and_then(|e| e.generics.as_deref())
        .or(context.event_generics.as_deref());
    let event_has_runtime = event_generics_str
        .map(|g| g.contains("BloxRuntime"))
        .unwrap_or(false);
    if context_has_runtime || event_has_runtime {
        use_stmts.push(quote! { use ::bloxide_core::capability::BloxRuntime; });
    }
    use_stmts.push(quote! { use ::bloxide_core::spec::{MachineSpec, StateFns}; });
    use_stmts.push(quote! { use #blox_crate_path::#ctx_ident; });
    use_stmts.push(quote! { pub use #blox_crate_path::generated::topology::#state_ident; });

    // Import the handler table macro from the blox crate when generating
    // system-level specs. For blox-level specs, the macro is already in scope
    // via #[macro_use] mod topology.
    if is_system_level {
        use_stmts.push(quote! {
            #[allow(unused_imports)]
            use #blox_crate_path::#handler_macro_ident;
        });
    }

    // Event import
    let event_name_str = event
        .map(|e| e.name.clone())
        .or_else(|| context.event_name.clone())
        .ok_or_else(|| {
            anyhow::anyhow!(
                "spec_skeleton requires either an [event] section or context.event_name"
            )
        })?;
    let event_ident = format_ident!("{}", event_name_str);
    // The event is imported from the crate root, but for hand-written events
    // it may be in a different crate. We use `use crate::#event_ident` as the
    // default. The blox.toml can override this with explicit imports.
    // Actually, the old code had `use crate::{SupervisorCtx, SupervisorEvent};`
    // which means the event is re-exported at the crate root.
    // For hand-written events, the blox crate re-exports the event from the
    // context crate. We emit a combined import.
    use_stmts.push(quote! { use #blox_crate_path::#event_ident; });

    // Add spec_imports from topology (raw use statements for action functions)
    // Translate leading `crate::` prefix to blox_crate_path for system-level codegen.
    for imp in &topology.spec_imports {
        let translated = translate_crate_import(imp);
        let use_item: syn::ItemUse = syn::parse_str(&format!("use {};", translated))
            .map_err(|e| anyhow::anyhow!("invalid spec_import '{}': {}", translated, e))?;
        use_stmts.push(quote! {
            #[allow(unused_imports)]
            #use_item
        });
    }

    // Envelope is needed when FullEvent patterns match on Envelope-wrapped
    // variants (e.g. `SupervisorEvent::Child(Envelope(_, ChildLifecycleEvent::Stopped { .. }))`).
    // Always import it when there's an [event] section — it's harmless if unused.
    if event.is_some() {
        use_stmts.push(quote! {
            #[allow(unused_imports)]
            use ::bloxide_core::messaging::Envelope;
        });
    }

    // Add message type imports — the generated matches closures reference
    // message enum types (e.g. `CounterMsg::Tick(_)`) which must be in scope.
    // Collect unique crate-level import paths from mailbox message_path fields.
    let mut msg_import_paths: Vec<String> = Vec::new();
    if let Some(ev) = event {
        for mb in &ev.mailboxes {
            if let Some(ref mp) = mb.message_path {
                // message_path is like "counter_messages::CounterMsg" or
                // "pool_messages::WorkerCtrl<R>" — strip generics, take
                // the crate::path part as a single use statement.
                let base = mp.split('<').next().unwrap_or(mp).trim();
                if !msg_import_paths.iter().any(|p| p == base) {
                    msg_import_paths.push(base.to_string());
                }
            }
        }
    }
    for path in &msg_import_paths {
        let use_item: syn::ItemUse = syn::parse_str(&format!("use {};", path))
            .map_err(|e| anyhow::anyhow!("invalid message import '{}': {}", path, e))?;
        use_stmts.push(quote! {
            #[allow(unused_imports)]
            #use_item
        });
    }

    // ── Build variants ─────────────────────────────────────────────────────────
    let variants = if has_feature {
        let feat_name = context.feature.as_deref().unwrap();

        // Non-feature variant
        let base_generics =
            syn::parse_str::<syn::Generics>(context.generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid generics: {}", e))?;

        let base_event_generics = if let Some(ev) = event {
            syn::parse_str::<syn::Generics>(ev.generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid [event].generics: {}", e))?
        } else {
            syn::parse_str::<syn::Generics>(context.event_generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid event_generics: {}", e))?
        };

        let base_ctx_params: Vec<String> = base_generics
            .type_params()
            .map(|tp| tp.ident.to_string())
            .collect();
        let base_event_params: Vec<String> = base_event_generics
            .type_params()
            .map(|tp| tp.ident.to_string())
            .collect();

        let base_ctx_ty = if base_ctx_params.is_empty() {
            quote! { #ctx_ident }
        } else {
            let params: Vec<_> = base_generics.type_params().map(|tp| &tp.ident).collect();
            quote! { #ctx_ident<#(#params),*> }
        };

        let base_event_ty = if base_event_params.is_empty() {
            quote! { #event_ident }
        } else {
            let params: Vec<_> = base_event_generics
                .type_params()
                .map(|tp| &tp.ident)
                .collect();
            quote! { #event_ident<#(#params),*> }
        };

        // Derive base mailboxes type from [event] section when present,
        // falling back to context.mailboxes_type for hand-written events.
        let base_mailboxes_ty: proc_macro2::TokenStream = if let Some(ev) = event {
            let mailboxes_tys: Vec<_> = ev
                .mailboxes
                .iter()
                .filter(|mb| mb.feature.is_none())
                .map(|mb| {
                    let msg_type = if let Some(ref path) = mb.message_path {
                        syn::parse_str::<syn::Path>(path).map_err(|e| {
                            anyhow::anyhow!("invalid message_path '{}': {}", path, e)
                        })?
                    } else {
                        syn::parse_str::<syn::Path>(&mb.message).map_err(|e| {
                            anyhow::anyhow!("invalid message '{}': {}", mb.message, e)
                        })?
                    };
                    Ok::<_, anyhow::Error>(quote! { Rt::Stream<#msg_type> })
                })
                .collect::<anyhow::Result<Vec<_>>>()?;
            quote! { (#(#mailboxes_tys,)*) }
        } else {
            let base_mailboxes = context.mailboxes_type.as_deref().ok_or_else(|| {
                anyhow::anyhow!(
                    "context.mailboxes_type required for feature-gated specs without [event] section"
                )
            })?;
            base_mailboxes.parse().map_err(|e| {
                anyhow::anyhow!("invalid mailboxes_type '{}': {}", base_mailboxes, e)
            })?
        };

        // Build spec generics for base variant
        let mut base_spec_generics =
            syn::parse_str::<syn::Generics>(context.generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid generics: {}", e))?;
        // Add extra_where
        if !context.extra_where.is_empty() {
            let mut preds = syn::punctuated::Punctuated::new();
            if let Some(ref wc) = base_spec_generics.where_clause {
                for pred in wc.predicates.iter() {
                    let pred_str = pred.to_token_stream().to_string();
                    preds.push(
                        syn::parse_str::<syn::WherePredicate>(&pred_str)
                            .map_err(|e| anyhow::anyhow!("re-parse where predicate: {}", e))?,
                    );
                }
            }
            for w in &context.extra_where {
                preds.push(
                    syn::parse_str::<syn::WherePredicate>(w)
                        .map_err(|e| anyhow::anyhow!("invalid extra_where '{}': {}", w, e))?,
                );
            }
            base_spec_generics.where_clause = Some(syn::WhereClause {
                where_token: syn::Token![where](proc_macro2::Span::call_site()),
                predicates: preds,
            });
        }

        // Feature variant
        let feature_generics =
            syn::parse_str::<syn::Generics>(context.feature_generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid feature_generics: {}", e))?;

        let feature_event_generics = if let Some(ev) = event {
            syn::parse_str::<syn::Generics>(ev.feature_generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid [event].feature_generics: {}", e))?
        } else {
            syn::parse_str::<syn::Generics>(
                context.feature_event_generics.as_deref().unwrap_or("<>"),
            )
            .map_err(|e| anyhow::anyhow!("invalid feature_event_generics: {}", e))?
        };

        let feature_ctx_params: Vec<String> = feature_generics
            .type_params()
            .map(|tp| tp.ident.to_string())
            .collect();
        let feature_event_params: Vec<String> = feature_event_generics
            .type_params()
            .map(|tp| tp.ident.to_string())
            .collect();

        let feature_ctx_ty = if feature_ctx_params.is_empty() {
            quote! { #ctx_ident }
        } else {
            let params: Vec<_> = feature_generics.type_params().map(|tp| &tp.ident).collect();
            quote! { #ctx_ident<#(#params),*> }
        };

        let feature_event_ty = if feature_event_params.is_empty() {
            quote! { #event_ident }
        } else {
            let params: Vec<_> = feature_event_generics
                .type_params()
                .map(|tp| &tp.ident)
                .collect();
            quote! { #event_ident<#(#params),*> }
        };

        // Derive feature mailboxes type from [event] section when present
        // (all mailboxes, including feature-gated ones), falling back to
        // context.feature_mailboxes_type for hand-written events.
        let feature_mailboxes_ty: proc_macro2::TokenStream = if let Some(ev) = event {
            let mailboxes_tys: Vec<_> = ev
                .mailboxes
                .iter()
                .map(|mb| {
                    let msg_type = if let Some(ref path) = mb.message_path {
                        syn::parse_str::<syn::Path>(path).map_err(|e| {
                            anyhow::anyhow!("invalid message_path '{}': {}", path, e)
                        })?
                    } else {
                        syn::parse_str::<syn::Path>(&mb.message).map_err(|e| {
                            anyhow::anyhow!("invalid message '{}': {}", mb.message, e)
                        })?
                    };
                    Ok::<_, anyhow::Error>(quote! { Rt::Stream<#msg_type> })
                })
                .collect::<anyhow::Result<Vec<_>>>()?;
            quote! { (#(#mailboxes_tys,)*) }
        } else {
            let feature_mailboxes = context.feature_mailboxes_type.as_deref().ok_or_else(|| {
                anyhow::anyhow!("context.feature_mailboxes_type required for feature-gated specs")
            })?;
            feature_mailboxes.parse().map_err(|e| {
                anyhow::anyhow!(
                    "invalid feature_mailboxes_type '{}': {}",
                    feature_mailboxes,
                    e
                )
            })?
        };

        // Build spec generics for feature variant
        let mut feature_spec_generics =
            syn::parse_str::<syn::Generics>(context.feature_generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid feature_generics: {}", e))?;
        // Add 'static to feature-variant type params that need it.
        // Feature variants may need 'static bounds on extra type params
        // (beyond R: BloxRuntime). Use feature_where for this.
        if !context.feature_where.is_empty() {
            let mut preds = syn::punctuated::Punctuated::new();
            if let Some(ref wc) = feature_spec_generics.where_clause {
                for pred in wc.predicates.iter() {
                    let pred_str = pred.to_token_stream().to_string();
                    preds.push(
                        syn::parse_str::<syn::WherePredicate>(&pred_str)
                            .map_err(|e| anyhow::anyhow!("re-parse where predicate: {}", e))?,
                    );
                }
            }
            for w in &context.feature_where {
                preds.push(
                    syn::parse_str::<syn::WherePredicate>(w)
                        .map_err(|e| anyhow::anyhow!("invalid feature_where '{}': {}", w, e))?,
                );
            }
            feature_spec_generics.where_clause = Some(syn::WhereClause {
                where_token: syn::Token![where](proc_macro2::Span::call_site()),
                predicates: preds,
            });
        }

        vec![
            VariantParams {
                cfg_attr: Some(format!("not(feature = \"{}\")", feat_name)),
                spec_generics: base_spec_generics,
                ctx_ty: base_ctx_ty,
                event_ty: base_event_ty,
                mailboxes_ty: base_mailboxes_ty,
                event_type_params: base_event_params,
                ctx_type_params: base_ctx_params,
                feature_filter: None,
                extra_imports: Vec::new(),
            },
            VariantParams {
                cfg_attr: Some(format!("feature = \"{}\"", feat_name)),
                spec_generics: feature_spec_generics,
                ctx_ty: feature_ctx_ty,
                event_ty: feature_event_ty,
                mailboxes_ty: feature_mailboxes_ty,
                event_type_params: feature_event_params,
                ctx_type_params: feature_ctx_params,
                feature_filter: Some(feat_name.to_string()),
                extra_imports: topology
                    .feature_spec_imports
                    .iter()
                    .map(|imp| translate_crate_import(imp))
                    .collect(),
            },
        ]
    } else {
        // Single variant (no feature-gating)
        let ctx_generics = context
            .generics
            .as_ref()
            .map(|g| {
                syn::parse_str::<syn::Generics>(g)
                    .map_err(|e| anyhow::anyhow!("invalid context generics '{}': {}", g, e))
            })
            .transpose()?
            .unwrap_or_default();

        let event_generics = event_generics_str
            .map(|g| {
                syn::parse_str::<syn::Generics>(g)
                    .map_err(|e| anyhow::anyhow!("invalid event generics '{}': {}", g, e))
            })
            .transpose()?
            .unwrap_or_default();

        let (_event_impl_generics, event_ty_generics, _event_where_clause) =
            event_generics.split_for_impl();

        let ctx_params: Vec<String> = ctx_generics
            .type_params()
            .map(|tp| tp.ident.to_string())
            .collect();
        let event_params: Vec<String> = event_generics
            .type_params()
            .map(|tp| tp.ident.to_string())
            .collect();

        let ctx_ty = if ctx_generics.type_params().count() > 0 {
            let (_impl_g, ty_g, _where_g) = ctx_generics.split_for_impl();
            quote! { #ctx_ident #ty_g }
        } else {
            quote! { #ctx_ident }
        };

        let event_ty = if event_generics.type_params().count() > 0 {
            quote! { #event_ident #event_ty_generics }
        } else {
            quote! { #event_ident }
        };

        // Mailboxes
        let mailboxes_ty = if let Some(event) = event {
            let mailboxes_tys: Vec<_> = event
                .mailboxes
                .iter()
                .map(|mb| {
                    let msg_type = if let Some(ref path) = mb.message_path {
                        syn::parse_str::<syn::Path>(path).map_err(|e| {
                            anyhow::anyhow!("invalid message_path '{}': {}", path, e)
                        })?
                    } else {
                        syn::parse_str::<syn::Path>(&mb.message).map_err(|e| {
                            anyhow::anyhow!("invalid message '{}': {}", mb.message, e)
                        })?
                    };
                    Ok(quote! { Rt::Stream<#msg_type> })
                })
                .collect::<anyhow::Result<Vec<_>>>()?;
            quote! { (#(#mailboxes_tys,)*) }
        } else if let Some(ref mb_type) = context.mailboxes_type {
            syn::parse_str::<proc_macro2::TokenStream>(mb_type)
                .map_err(|e| anyhow::anyhow!("invalid mailboxes_type '{}': {}", mb_type, e))?
        } else {
            anyhow::bail!(
                "spec_skeleton requires either [event].mailboxes or context.mailboxes_type"
            )
        };

        // Build spec generics
        let mut spec_generics =
            syn::parse_str::<syn::Generics>(context.generics.as_deref().unwrap_or("<>"))
                .map_err(|e| anyhow::anyhow!("invalid generics: {}", e))?;
        // Add extra_where
        if !context.extra_where.is_empty() {
            let mut preds = syn::punctuated::Punctuated::new();
            if let Some(ref wc) = spec_generics.where_clause {
                for pred in wc.predicates.iter() {
                    let pred_str = pred.to_token_stream().to_string();
                    preds.push(
                        syn::parse_str::<syn::WherePredicate>(&pred_str)
                            .map_err(|e| anyhow::anyhow!("re-parse where predicate: {}", e))?,
                    );
                }
            }
            for w in &context.extra_where {
                preds.push(
                    syn::parse_str::<syn::WherePredicate>(w)
                        .map_err(|e| anyhow::anyhow!("invalid extra_where '{}': {}", w, e))?,
                );
            }
            spec_generics.where_clause = Some(syn::WhereClause {
                where_token: syn::Token![where](proc_macro2::Span::call_site()),
                predicates: preds,
            });
        }

        vec![VariantParams {
            cfg_attr: None,
            spec_generics,
            ctx_ty,
            event_ty,
            mailboxes_ty,
            event_type_params: event_params,
            ctx_type_params: ctx_params,
            feature_filter: None,
            extra_imports: Vec::new(),
        }]
    };

    // ── Generate each variant ─────────────────────────────────────────────────
    let mut variant_tokens = Vec::new();

    for var in &variants {
        let (spec_impl_generics, spec_ty_generics, spec_where_clause) =
            var.spec_generics.split_for_impl();

        // PhantomData type
        let phantom_types = if var.ctx_type_params.is_empty() {
            quote! { () }
        } else if var.ctx_type_params.len() == 1 {
            let p = format_ident!("{}", var.ctx_type_params[0]);
            quote! { #p }
        } else {
            let params: Vec<_> = var
                .ctx_type_params
                .iter()
                .map(|s| format_ident!("{}", s))
                .collect();
            quote! { (#(#params),*) }
        };

        // Ctx and Event type strings for placeholder replacement
        let ctx_type_str = var.ctx_ty.to_token_stream().to_string();
        let event_type_str = var.event_ty.to_token_stream().to_string();
        // Clean up whitespace from to_string()
        let ctx_type_str = ctx_type_str.replace(" ", "");
        let event_type_str = event_type_str.replace(" ", "");

        // Spec struct
        let struct_def = quote! {
            pub struct #spec_ident #spec_impl_generics #spec_where_clause {
                _phantom: PhantomData<#phantom_types>,
            }
        };

        // StateFns associated constants — always generated as associated constants
        // inside the impl block using raw StateRule literals. This handles both
        // feature-gated and non-feature-gated specs uniformly.
        let state_fns_impl = generate_state_fns_impl(
            topology,
            &state_ident,
            &spec_ident,
            &ctx_type_str,
            &event_type_str,
            &var.event_type_params,
            spec_impl_generics.to_token_stream(),
            spec_ty_generics.to_token_stream(),
            spec_where_clause,
            var.feature_filter.as_deref(),
            action_resolver,
        )?;

        // MachineSpec impl
        let var_event_ty = &var.event_ty;
        let var_ctx_ty = &var.ctx_ty;
        let var_mailboxes_ty = &var.mailboxes_ty;
        let impl_block = quote! {
            impl #spec_impl_generics MachineSpec for #spec_ident #spec_ty_generics #spec_where_clause {
                type State = #state_ident;
                type Event = #var_event_ty;
                type Ctx = #var_ctx_ty;
                type Mailboxes<Rt: ::bloxide_core::capability::BloxRuntime> = #var_mailboxes_ty;

                const HANDLER_TABLE: &'static [&'static StateFns<Self>] = #handler_macro_ident!(Self);

                fn initial_state() -> #state_ident {
                    #state_ident::#initial_state_ident
                }

                fn is_error(#is_error_param: &#state_ident) -> bool {
                    #is_error_body
                }

                #on_init_fn
            }
        };

        // Extra imports for this variant
        let extra_import_tokens: Vec<proc_macro2::TokenStream> = var
            .extra_imports
            .iter()
            .map(|imp| {
                let use_item: syn::ItemUse = syn::parse_str(&format!("use {};", imp))
                    .unwrap_or_else(|_| panic!("invalid extra_import: {}", imp));
                quote! {
                    #[allow(unused_imports)]
                    #use_item
                }
            })
            .collect();

        // Wrap each item in #[cfg] if needed (#[cfg] only applies to the
        // immediately following item, not a sequence of items)
        let wrapped = if let Some(ref cfg) = var.cfg_attr {
            let cfg_ts: proc_macro2::TokenStream = cfg
                .parse()
                .map_err(|e| anyhow::anyhow!("invalid cfg attr '{}': {}", cfg, e))?;
            quote! {
                #[cfg(#cfg_ts)]
                #(#extra_import_tokens)*
                #[cfg(#cfg_ts)]
                #struct_def
                #[cfg(#cfg_ts)]
                #state_fns_impl
                #[cfg(#cfg_ts)]
                #impl_block
            }
        } else {
            quote! {
                #(#extra_import_tokens)*
                #struct_def
                #state_fns_impl
                #impl_block
            }
        };

        variant_tokens.push(wrapped);
    }

    // ── Assemble final output ─────────────────────────────────────────────────
    let tokens = quote! {
        #(#use_stmts)*
        #(#variant_tokens)*
    };

    let raw = tokens.to_string();
    let file = syn::parse_str::<syn::File>(&raw)
        .map_err(|e| anyhow::anyhow!("syn parsing failed: {}", e))?;
    let formatted = prettyplease::unparse(&file);

    Ok(format!("{}{}", HEADER, formatted))
}
