// Copyright 2025 Bloxide, all rights reserved
//! Generate MachineSpec skeleton from actor, topology, context, and event config.

use quote::{format_ident, quote};

use crate::schema::{ActorConfig, ContextConfig, TopologyConfig};

const HEADER: &str = "// Auto-generated by bloxide-codegen. Do not edit manually.\n";

fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

fn derive_actions_crate(crate_name: &str) -> String {
    let base = crate_name.trim_end_matches("-blox");
    base.replace("-", "_") + "_actions"
}

pub fn generate(
    actor: &ActorConfig,
    topology: &TopologyConfig,
    context: Option<&ContextConfig>,
    event_name: &str,
    _message_type: &str,
    message_path: &str,
    crate_name: &str,
) -> anyhow::Result<String> {
    let actor_name = &actor.name;

    let spec_ident = format_ident!("{}Spec", actor_name);
    let state_ident = format_ident!("{}State", actor_name);
    let event_ident = format_ident!("{}", event_name);

    let handler_macro_name_str = format!(
        "{}_handler_table",
        to_snake_case(&format!("{}State", actor_name))
    );
    let handler_macro_ident = format_ident!("{}", handler_macro_name_str);

    let ctx_ident = if let Some(ctx) = context {
        format_ident!("{}", ctx.name)
    } else {
        format_ident!("{}Ctx", actor_name)
    };

    let delegate_traits: Vec<String> = if let Some(ctx) = context {
        let mut traits = Vec::new();
        for field in &ctx.fields {
            if let Some(ref d) = field.delegates {
                for tr in d {
                    if !traits.contains(tr) {
                        traits.push(tr.clone());
                    }
                }
            }
        }
        traits
    } else {
        Vec::new()
    };

    let has_runtime_generic = context
        .map(|c| {
            c.generics
                .as_ref()
                .map(|g| g.contains("BloxRuntime"))
                .unwrap_or(false)
        })
        .unwrap_or(false);

    let phantom_types = if has_runtime_generic {
        quote! { (R, B) }
    } else {
        quote! { B }
    };

    let b_bounds = if delegate_traits.is_empty() {
        quote! { 'static }
    } else {
        let trait_idents: Vec<_> =
            delegate_traits.iter().map(|t| format_ident!("{}", t)).collect();
        quote! { #(#trait_idents)+* + 'static }
    };

    let (spec_generics, spec_where, ty_generics) = if has_runtime_generic {
        (
            quote! { <R, B> },
            quote! { where R: ::bloxide_core::capability::BloxRuntime, B: #b_bounds },
            quote! { <R, B> },
        )
    } else {
        (
            quote! { <B> },
            quote! { where B: #b_bounds },
            quote! { <B> },
        )
    };

    let msg_path = syn::parse_str::<syn::Path>(message_path)
        .map_err(|e| anyhow::anyhow!("invalid message_path '{}': {}", message_path, e))?;

    let msg_short_ident = msg_path
        .segments
        .last()
        .map(|seg| seg.ident.clone())
        .unwrap_or_else(|| format_ident!("Msg"));

    let initial_state = topology
        .states
        .iter()
        .find(|s| s.initial.unwrap_or(false))
        .map(|s| s.name.clone())
        .or_else(|| {
            topology
                .states
                .iter()
                .find(|s| !s.composite.unwrap_or(false))
                .map(|s| s.name.clone())
        });

    let initial_state_ident = if let Some(ref name) = initial_state {
        format_ident!("{}", name)
    } else {
        format_ident!("Init")
    };

    let terminal_states: Vec<_> = topology
        .states
        .iter()
        .filter(|s| s.terminal.unwrap_or(false))
        .map(|s| format_ident!("{}", s.name))
        .collect();

    let error_states: Vec<_> = topology
        .states
        .iter()
        .filter(|s| s.error.unwrap_or(false))
        .map(|s| format_ident!("{}", s.name))
        .collect();

    let is_terminal_body = if terminal_states.is_empty() {
        quote! { false }
    } else {
        quote! {
            ::core::matches!(state, #state_ident::#(#terminal_states)|*)
        }
    };

    let is_error_body = if error_states.is_empty() {
        quote! { false }
    } else {
        quote! {
            ::core::matches!(state, #state_ident::#(#error_states)|*)
        }
    };

    let ctx_ty = quote! { #ctx_ident<B> };

    let mut use_stmts = vec![quote! {
        use ::core::marker::PhantomData;
    }];

    if has_runtime_generic {
        use_stmts.push(quote! {
            use ::bloxide_core::capability::BloxRuntime;
        });
    }

    use_stmts.push(quote! {
        use ::bloxide_core::spec::{MachineSpec, StateFns};
    });

    if context.is_some() {
        use_stmts.push(quote! {
            use crate::{#ctx_ident, #event_ident};
        });
    } else {
        use_stmts.push(quote! {
            use crate::#event_ident;
        });
    }

    use_stmts.push(quote! {
        pub use crate::generated::topology::#state_ident;
    });

    use_stmts.push(quote! {
        use crate::#handler_macro_ident;
    });

    if !delegate_traits.is_empty() {
        let actions_crate = context
            .and_then(|c| c.actions_crate.clone())
            .unwrap_or_else(|| derive_actions_crate(crate_name));
        let actions_crate_ident = format_ident!("{}", actions_crate);
        let trait_idents: Vec<_> =
            delegate_traits.iter().map(|t| format_ident!("{}", t)).collect();
        use_stmts.push(quote! {
            use #actions_crate_ident::{#(#trait_idents),*};
        });
    }

    if msg_path.segments.len() > 1 {
        use_stmts.push(quote! {
            use #msg_path;
        });
    }

    let struct_def = quote! {
        pub struct #spec_ident #spec_generics #spec_where {
            _phantom: PhantomData<#phantom_types>,
        }
    };

    let mailboxes_ty = if msg_path.segments.len() > 1 {
        quote! { (Rt::Stream<#msg_short_ident>,) }
    } else {
        quote! { (Rt::Stream<#msg_path>,) }
    };

    let impl_block = quote! {
        impl #spec_generics MachineSpec for #spec_ident #ty_generics #spec_where {
            type State = #state_ident;
            type Event = #event_ident;
            type Ctx = #ctx_ty;
            type Mailboxes<Rt: ::bloxide_core::capability::BloxRuntime> = #mailboxes_ty;

            const HANDLER_TABLE: &'static [&'static StateFns<Self>] = #handler_macro_ident!(Self);

            fn initial_state() -> #state_ident {
                #state_ident::#initial_state_ident
            }

            fn is_terminal(state: &#state_ident) -> bool {
                #is_terminal_body
            }

            fn is_error(state: &#state_ident) -> bool {
                #is_error_body
            }

            fn on_init_entry(_ctx: &mut Self::Ctx) {}
        }
    };

    let tokens = quote! {
        #(#use_stmts)*
        #struct_def
        #impl_block
    };

    let raw = tokens.to_string();
    let file = syn::parse_str::<syn::File>(&raw)
        .map_err(|e| anyhow::anyhow!("syn parsing failed: {}", e))?;
    let formatted = prettyplease::unparse(&file);

    Ok(format!("{}{}", HEADER, formatted))
}
