// Copyright 2025 Bloxide, all rights reserved
//! Generate state topology enum and `StateTopology` implementation.

use quote::{format_ident, quote};
use std::collections::HashMap;

use crate::schema::TopologyConfig;

const HEADER: &str = "// Auto-generated by bloxide-codegen. Do not edit manually.\n";

/// Convert PascalCase to snake_case for identifiers.
fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

/// Capitalize the first letter of a string.
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
    }
}

pub fn generate(
    config: &TopologyConfig,
    actor_name: Option<&str>,
    crate_name: &str,
) -> anyhow::Result<String> {
    let enum_name_str = actor_name
        .map(|n| format!("{}State", n))
        .unwrap_or_else(|| {
            let base = crate_name.trim_end_matches("-blox");
            let base = base.replace("-", "_");
            let parts: Vec<_> = base.split('_').map(capitalize).collect();
            format!("{}State", parts.join(""))
        });
    let enum_ident = format_ident!("{}", enum_name_str);

    let state_count = config.states.len();

    // Build name -> index map
    let name_to_index: HashMap<String, usize> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| (s.name.clone(), i))
        .collect();

    // Validate parents exist
    for state in &config.states {
        if let Some(ref parent) = state.parent {
            if !name_to_index.contains_key(parent) {
                anyhow::bail!(
                    "state '{}' references unknown parent '{}'",
                    state.name,
                    parent
                );
            }
        }
    }

    // Validate no cycles
    for state in &config.states {
        let mut visited = std::collections::HashSet::new();
        let mut cursor = state.parent.as_ref();
        while let Some(ref cur_name) = cursor {
            if !visited.insert(cur_name.to_string()) {
                anyhow::bail!("cycle detected in parent chain for '{}'", state.name);
            }
            let parent_idx = name_to_index[*cur_name];
            cursor = config.states[parent_idx].parent.as_ref();
        }
    }

    // Enum variants with discriminant
    let enum_variants: Vec<_> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let ident = format_ident!("{}", s.name);
            let idx = i as u8;
            quote! { #ident = #idx }
        })
        .collect();

    let enum_def = quote! {
        #[derive(Copy, Clone, Eq, PartialEq, Debug)]
        #[repr(u8)]
        pub enum #enum_ident {
            #(#enum_variants),*
        }
    };

    // parent() arms
    let parent_arms: Vec<_> = config
        .states
        .iter()
        .map(|s| {
            let ident = format_ident!("{}", s.name);
            match &s.parent {
                None => quote! { Self::#ident => ::core::option::Option::None },
                Some(p) => {
                    let parent_ident = format_ident!("{}", p);
                    quote! { Self::#ident => ::core::option::Option::Some(Self::#parent_ident) }
                }
            }
        })
        .collect();

    // is_leaf() arms — composite states are not leaves
    let is_leaf_arms: Vec<_> = config
        .states
        .iter()
        .map(|s| {
            let ident = format_ident!("{}", s.name);
            let is_leaf = !s.composite.unwrap_or(false);
            quote! { Self::#ident => #is_leaf }
        })
        .collect();

    // Compute paths (root-first, ending at self)
    let paths: Vec<Vec<usize>> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let mut chain = Vec::new();
            chain.push(i);
            let mut cursor = s.parent.as_ref();
            while let Some(ref cur_name) = cursor {
                let parent_idx = name_to_index[*cur_name];
                chain.push(parent_idx);
                cursor = config.states[parent_idx].parent.as_ref();
            }
            chain.reverse();
            chain
        })
        .collect();

    // path() static arrays and match arms
    let mut path_statics = Vec::new();
    let mut path_arms = Vec::new();

    for (state, path) in config.states.iter().zip(paths.iter()) {
        let vname = format_ident!("{}", state.name);
        let const_name = format_ident!(
            "__PATH_{}",
            state.name.to_ascii_uppercase()
        );
        let path_idents: Vec<_> = path
            .iter()
            .map(|&idx| {
                let name = format_ident!("{}", config.states[idx].name);
                quote! { #enum_ident::#name }
            })
            .collect();
        let len = path.len();
        path_statics.push(quote! {
            static #const_name: [#enum_ident; #len] = [#(#path_idents),*];
        });
        path_arms.push(quote! {
            Self::#vname => &#const_name
        });
    }

    // as_index() arms
    let as_index_arms: Vec<_> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let ident = format_ident!("{}", s.name);
            quote! { Self::#ident => #i }
        })
        .collect();

    let topology_impl = quote! {
        impl ::bloxide_core::topology::StateTopology for #enum_ident {
            const STATE_COUNT: usize = #state_count;

            #[inline]
            fn parent(self) -> ::core::option::Option<Self> {
                match self {
                    #(#parent_arms,)*
                }
            }

            #[inline]
            fn is_leaf(self) -> bool {
                match self {
                    #(#is_leaf_arms,)*
                }
            }

            fn path(self) -> &'static [Self] {
                #(#path_statics)*
                match self {
                    #(#path_arms,)*
                }
            }

            #[inline]
            fn as_index(self) -> usize {
                match self {
                    #(#as_index_arms,)*
                }
            }
        }
    };

    // Optional handler table macro
    let helper_macro = if let Some(ref fns) = config.handler_fns {
        if fns.len() != state_count {
            anyhow::bail!(
                "handler_fns must list exactly {} entries (one per variant), got {}",
                state_count,
                fns.len()
            );
        }

        let macro_name_str = format!("{}_handler_table", to_snake_case(&enum_name_str));
        let macro_name = format_ident!("{}", macro_name_str);

        let fn_idents: Vec<_> = fns
            .iter()
            .map(|f| format_ident!("{}", f))
            .collect();

        quote! {
            #[doc(hidden)]
            #[macro_export]
            macro_rules! #macro_name {
                ($ty:ty) => {
                    &[#(&<$ty>::#fn_idents),*]
                };
            }
        }
    } else {
        quote! {}
    };

    let tokens = quote! {
        #enum_def
        #topology_impl
        #helper_macro
    };

    let raw = tokens.to_string();
    let file = syn::parse_str::<syn::File>(&raw)
        .map_err(|e| anyhow::anyhow!("syn parsing failed: {}", e))?;
    let formatted = prettyplease::unparse(&file);

    Ok(format!("{}{}", HEADER, formatted))
}
