// Copyright 2025 Bloxide, all rights reserved
//! Generate state topology enum and `StateTopology` implementation.
//! When declarative transitions are present in the TOML, also generates
//! complete `StateFns` constants with raw `StateRule { ... }` struct literals.

use quote::{format_ident, quote, ToTokens};
use std::collections::HashMap;

use crate::schema::{TopologyConfig, TransitionConfig};
use crate::spec_skeleton::replace_placeholders;
use crate::util::{to_snake_case, to_upper_snake_case};

const HEADER: &str = "// Copyright 2025 Bloxide, all rights reserved\n// Auto-generated by bloxide-codegen. Do not edit manually.\n";

/// Capitalize the first letter of a string.
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
    }
}

// ── Pattern classification ──────────────────────────────────────────────────
//
// The event pattern string from TOML (e.g. "PingPongMsg::Ping(_)" or
// "SupervisorEvent::Child(ChildLifecycleEvent::Done { .. })") is classified
// to determine how the `matches` closure and `event_tag` field are generated.
//
// **Full-event patterns** — match the entire event directly.
//   Examples: "SupervisorEvent::Child(ChildLifecycleEvent::Done { .. })", "_"
//   Tag: extracted from the pattern path (e.g. SupervisorEvent::CHILD_TAG)
//   Matches: |__ev| matches!(__ev, <pattern>)
//
// **Msg shorthand** — ident ending with "Msg", matching via msg_payload().
//   Tag: WILDCARD_TAG
//   Matches: |__ev| __ev.msg_payload().is_some_and(|__m| matches!(__m, <pattern>))
//
// **Ctrl shorthand** — ident ending with "Ctrl", matching via ctrl_payload().
//   Tag: WILDCARD_TAG
//   Matches: |__ev| __ev.ctrl_payload().is_some_and(|__m| matches!(__m, <pattern>))

#[derive(Copy, Clone, Debug)]
enum PatternKind {
    FullEvent,
    MsgShorthand,
    CtrlShorthand,
}

/// Classify a pattern string from TOML into the kind of matching it needs.
///
/// Assumes the pattern starts with an identifier (letter or underscore).
/// Patterns starting with `(` (tuple struct) or `{` (struct pattern) are
/// not currently produced by the TOML schema and would misclassify as
/// `FullEvent` — this is acceptable since all valid TOML event patterns
/// begin with an enum/variant name.
fn classify_pattern_str(event: &str) -> PatternKind {
    // Find the first identifier in the pattern string.
    // If it ends with "Msg" → MsgShorthand, "Ctrl" → CtrlShorthand, else FullEvent.
    let trimmed = event.trim();

    // Extract the first identifier from the pattern.
    // An identifier starts with a letter or underscore, followed by
    // alphanumeric or underscore characters.
    let first_ident: String = trimmed
        .chars()
        .skip_while(|c| !c.is_alphabetic() && *c != '_')
        .take_while(|c| c.is_alphanumeric() || *c == '_')
        .collect();

    if first_ident.ends_with("Msg") {
        return PatternKind::MsgShorthand;
    }
    if first_ident.ends_with("Ctrl") {
        return PatternKind::CtrlShorthand;
    }
    PatternKind::FullEvent
}

/// Check if the event pattern string contains a `::` path separator,
/// indicating a variant-specific pattern like `PeerCtrl::AddPeer(...)`
/// vs a catch-all `PeerCtrl(...)`.
fn has_path_separator_str(event: &str) -> bool {
    event.contains("::")
}

/// Strip bindings from a shorthand pattern, replacing `(...)` with `(_)`.
/// E.g. "PingPongMsg::Pong(pong)" → "PingPongMsg::Pong(_)"
///
/// Nested patterns inside `(...)` are replaced with `_` — only the outer
/// variant is matched. For example, `Foo::Bar(Baz(a, b))` → `Foo::Bar(_)`.
/// This is intentional: the `matches!` closure only needs to distinguish
/// the outer variant, not inspect inner fields.
fn strip_bindings_from_pattern(event: &str) -> String {
    // Find the first `(` and replace everything inside it with `_`.
    if let Some(open) = event.find('(') {
        let before = &event[..open];
        format!("{before}(_)")
    } else {
        event.to_string()
    }
}

/// Extract the event tag expression from a pattern string.
///
/// For full-event patterns like "Enum::Variant(...)":
///   → `Enum::VARIANT_TAG`
/// For wildcard `_`:
///   → `::bloxide_core::event_tag::WILDCARD_TAG`
/// For or-patterns (containing `|`):
///   → `::bloxide_core::event_tag::WILDCARD_TAG`
/// For Msg/Ctrl shorthand:
///   → `::bloxide_core::event_tag::WILDCARD_TAG`
fn extract_event_tag_str(
    event: &str,
    kind: PatternKind,
    type_params: &[String],
) -> proc_macro2::TokenStream {
    // Shorthand patterns always use WILDCARD_TAG
    if !matches!(kind, PatternKind::FullEvent) {
        return quote! { ::bloxide_core::event_tag::WILDCARD_TAG };
    }

    let trimmed = event.trim();

    // Wildcard
    if trimmed == "_" {
        return quote! { ::bloxide_core::event_tag::WILDCARD_TAG };
    }

    // Or-patterns
    if trimmed.contains('|') {
        return quote! { ::bloxide_core::event_tag::WILDCARD_TAG };
    }

    // Try to parse as a path: EnumName::VariantName(...)
    // Extract the path segments before the first `(`
    let path_part = if let Some(open) = trimmed.find('(') {
        &trimmed[..open]
    } else {
        trimmed
    };

    let segments: Vec<&str> = path_part.split("::").map(|s| s.trim()).collect();
    if segments.len() < 2 {
        return quote! { ::bloxide_core::event_tag::WILDCARD_TAG };
    }

    // Last segment is the variant name → convert to UPPER_SNAKE_TAG
    let variant_name = segments.last().unwrap();
    let upper_snake = to_upper_snake_case(variant_name);
    let tag_const = format_ident!("{}_TAG", upper_snake);

    // Build the enum path as a token stream: Segment1 :: Segment2 :: ... :: TAG_CONST
    let enum_segments: Vec<proc_macro2::Ident> = segments[..segments.len() - 1]
        .iter()
        .map(|s| format_ident!("{}", s))
        .collect();

    // Add turbofish for the enum's type parameters if any.
    // E.g. SupervisorEvent::<R>::CHILD_TAG instead of SupervisorEvent::CHILD_TAG
    if type_params.is_empty() {
        quote! { #(#enum_segments ::)* #tag_const }
    } else {
        let param_idents: Vec<proc_macro2::Ident> =
            type_params.iter().map(|s| format_ident!("{}", s)).collect();
        let first = &enum_segments[0];
        let rest = &enum_segments[1..];
        quote! { #first ::<#(#param_idents),*> :: #(#rest ::)* #tag_const }
    }
}

/// Generate the `matches` closure from a pattern string.
fn generate_matches_closure(
    event: &str,
    kind: PatternKind,
) -> anyhow::Result<proc_macro2::TokenStream> {
    let pat_ts: proc_macro2::TokenStream = event
        .parse()
        .map_err(|e| anyhow::anyhow!("invalid event pattern '{}': {}", event, e))?;

    match kind {
        PatternKind::FullEvent => Ok(quote! { |__ev| ::core::matches!(__ev, #pat_ts) }),
        PatternKind::MsgShorthand => {
            let pat_stripped = strip_bindings_from_pattern(event);
            let pat_ts: proc_macro2::TokenStream = pat_stripped
                .parse()
                .map_err(|e| anyhow::anyhow!("invalid msg pattern '{}': {}", pat_stripped, e))?;
            Ok(quote! {
                |__ev| __ev.msg_payload().is_some_and(|__m| ::core::matches!(__m, #pat_ts))
            })
        }
        PatternKind::CtrlShorthand => {
            if has_path_separator_str(event) {
                let pat_stripped = strip_bindings_from_pattern(event);
                let pat_ts: proc_macro2::TokenStream = pat_stripped.parse().map_err(|e| {
                    anyhow::anyhow!("invalid ctrl pattern '{}': {}", pat_stripped, e)
                })?;
                Ok(quote! {
                    |__ev| __ev.ctrl_payload().is_some_and(|__m| ::core::matches!(__m, #pat_ts))
                })
            } else {
                Ok(quote! { |__ev| __ev.ctrl_payload().is_some() })
            }
        }
    }
}

/// Resolve a target string to a Guard expression token stream.
/// "stay" => Guard::Stay, "reset" => Guard::Reset, "fail" => Guard::Fail,
/// "StateName" => Guard::Transition(LeafState::new(StateEnum::StateName))
fn target_to_guard(target: &str, state_enum_ident: &syn::Ident) -> proc_macro2::TokenStream {
    match target {
        "stay" => quote! { ::bloxide_core::transition::Guard::Stay },
        "reset" => quote! { ::bloxide_core::transition::Guard::Reset },
        "fail" => quote! { ::bloxide_core::transition::Guard::Fail },
        state_name => {
            let ident = format_ident!("{}", state_name);
            quote! {
                ::bloxide_core::transition::Guard::Transition(
                    ::bloxide_core::topology::LeafState::new(#state_enum_ident::#ident)
                )
            }
        }
    }
}

/// Generate a guard closure from TOML guards.
///
/// If no guards: returns a simple closure `|_, _, _| Guard::X`.
/// If guards present: generates an if/else-if/else chain.
fn generate_guard_closure(
    trans: &TransitionConfig,
    state_enum_ident: &syn::Ident,
) -> anyhow::Result<proc_macro2::TokenStream> {
    // Separate wildcard guards (condition == "_") from real guards.
    // Wildcard guards provide the fallback target; if present, they override
    // the transition's top-level `target` as the else-branch fallback.
    let mut wildcard_target: Option<proc_macro2::TokenStream> = None;
    let real_guards: Vec<&crate::schema::GuardConfig> = trans
        .guards
        .iter()
        .filter(|g| {
            if g.condition.trim() == "_" {
                wildcard_target = Some(target_to_guard(&g.target, state_enum_ident));
                false
            } else {
                true
            }
        })
        .collect();

    let fallback_target =
        wildcard_target.unwrap_or_else(|| target_to_guard(&trans.target, state_enum_ident));

    if real_guards.is_empty() {
        // No real guards — simple closure
        return Ok(quote! { |ctx, results, _ev| #fallback_target });
    }

    // Build if/else-if/else chain from real guard conditions.
    // Parameters are named so guard conditions can reference ctx and results.
    let mut chain = proc_macro2::TokenStream::new();

    for guard in real_guards {
        let cond_ts: proc_macro2::TokenStream = guard
            .condition
            .parse()
            .map_err(|e| anyhow::anyhow!("invalid guard condition '{}': {}", guard.condition, e))?;
        let guard_target = target_to_guard(&guard.target, state_enum_ident);

        if chain.is_empty() {
            chain = quote! { if #cond_ts { #guard_target } };
        } else {
            chain = quote! { #chain else if #cond_ts { #guard_target } };
        }
    }

    // Add the fallback `else { fallback_target }`
    chain = quote! { #chain else { #fallback_target } };

    Ok(quote! { |ctx, results, _ev| { #chain } })
}

/// Generate a single `StateRule { ... }` struct literal from a TransitionConfig.
pub(crate) fn generate_state_rule(
    trans: &TransitionConfig,
    state_enum_ident: &syn::Ident,
    ctx_type_str: &str,
    event_type_str: &str,
    type_params: &[String],
) -> anyhow::Result<proc_macro2::TokenStream> {
    let kind = classify_pattern_str(&trans.event);
    let event_tag_ts = extract_event_tag_str(&trans.event, kind, type_params);
    let matches_ts = generate_matches_closure(&trans.event, kind)?;
    let guard_ts = generate_guard_closure(trans, state_enum_ident)?;

    // Parse action function paths (with placeholder replacement)
    let action_tokens: Vec<proc_macro2::TokenStream> = trans
        .actions
        .iter()
        .map(|a| {
            let resolved = replace_placeholders(a, ctx_type_str, event_type_str, type_params);
            syn::parse_str::<syn::Path>(&resolved)
                .map(|p| p.to_token_stream())
                .unwrap_or_else(|_| {
                    let ident = format_ident!("{}", resolved);
                    quote! { #ident }
                })
        })
        .collect();

    let actions_ts = if action_tokens.is_empty() {
        quote! { &[] }
    } else {
        quote! { &[#(#action_tokens),*] }
    };

    let rule = quote! {
        ::bloxide_core::transition::StateRule {
            event_tag: #event_tag_ts,
            matches: #matches_ts,
            actions: #actions_ts,
            guard: #guard_ts,
        }
    };

    // Emit #[cfg(feature = "...")] on the individual StateRule literal
    Ok(if let Some(ref feat) = trans.feature {
        quote! {
            #[cfg(feature = #feat)]
            #rule
        }
    } else {
        rule
    })
}

pub fn generate(
    config: &TopologyConfig,
    actor_name: Option<&str>,
    crate_name: &str,
    _has_feature: bool,
) -> anyhow::Result<String> {
    let enum_name_str = actor_name
        .map(|n| format!("{}State", n))
        .unwrap_or_else(|| {
            let base = crate_name.trim_end_matches("-blox");
            let base = base.replace("-", "_");
            let parts: Vec<_> = base.split('_').map(capitalize).collect();
            format!("{}State", parts.join(""))
        });
    let enum_ident = format_ident!("{}", enum_name_str);

    let state_count = config.states.len();

    // Build name -> index map
    let name_to_index: HashMap<String, usize> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| (s.name.clone(), i))
        .collect();

    // Validate parents exist
    for state in &config.states {
        if let Some(ref parent) = state.parent {
            if !name_to_index.contains_key(parent) {
                anyhow::bail!(
                    "state '{}' references unknown parent '{}'",
                    state.name,
                    parent
                );
            }
        }
    }

    // Validate no cycles
    for state in &config.states {
        let mut visited = std::collections::HashSet::new();
        let mut cursor = state.parent.as_ref();
        while let Some(ref cur_name) = cursor {
            if !visited.insert(cur_name.to_string()) {
                anyhow::bail!("cycle detected in parent chain for '{}'", state.name);
            }
            let parent_idx = name_to_index[*cur_name];
            cursor = config.states[parent_idx].parent.as_ref();
        }
    }

    // Validate transition targets reference valid states
    let valid_targets = ["stay", "reset", "fail"];
    for trans in &config.transitions {
        if !name_to_index.contains_key(&trans.state) {
            anyhow::bail!("transition references unknown state '{}'", trans.state);
        }
        // Validate main target
        let target = &trans.target;
        if !valid_targets.contains(&target.as_str()) && !name_to_index.contains_key(target) {
            anyhow::bail!(
                "transition in state '{}' references unknown target state '{}'",
                trans.state,
                target
            );
        }
        // Validate guard targets
        for guard in &trans.guards {
            let gtarget = &guard.target;
            if !valid_targets.contains(&gtarget.as_str()) && !name_to_index.contains_key(gtarget) {
                anyhow::bail!(
                    "guard in state '{}' references unknown target state '{}'",
                    trans.state,
                    gtarget
                );
            }
        }
    }

    // Validate entry/exit reference valid states
    for ee in config.entry.iter().chain(config.exit.iter()) {
        if !name_to_index.contains_key(&ee.state) {
            anyhow::bail!("entry/exit references unknown state '{}'", ee.state);
        }
    }

    // Enum variants with discriminant
    let enum_variants: Vec<_> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let ident = format_ident!("{}", s.name);
            let idx = i as u8;
            quote! { #ident = #idx }
        })
        .collect();

    let enum_def = quote! {
        #[derive(Copy, Clone, Eq, PartialEq, Debug)]
        #[repr(u8)]
        pub enum #enum_ident {
            #(#enum_variants),*
        }
    };

    // parent() arms
    let parent_arms: Vec<_> = config
        .states
        .iter()
        .map(|s| {
            let ident = format_ident!("{}", s.name);
            match &s.parent {
                None => quote! { Self::#ident => ::core::option::Option::None },
                Some(p) => {
                    let parent_ident = format_ident!("{}", p);
                    quote! { Self::#ident => ::core::option::Option::Some(Self::#parent_ident) }
                }
            }
        })
        .collect();

    // is_leaf() arms — composite states are not leaves
    let is_leaf_arms: Vec<_> = config
        .states
        .iter()
        .map(|s| {
            let ident = format_ident!("{}", s.name);
            let is_leaf = !s.composite.unwrap_or(false);
            quote! { Self::#ident => #is_leaf }
        })
        .collect();

    // Compute paths (root-first, ending at self)
    let paths: Vec<Vec<usize>> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let mut chain = Vec::new();
            chain.push(i);
            let mut cursor = s.parent.as_ref();
            while let Some(cur_name) = cursor {
                let parent_idx = name_to_index[cur_name];
                chain.push(parent_idx);
                cursor = config.states[parent_idx].parent.as_ref();
            }
            chain.reverse();
            chain
        })
        .collect();

    // path() static arrays and match arms
    let mut path_statics = Vec::new();
    let mut path_arms = Vec::new();

    for (state, path) in config.states.iter().zip(paths.iter()) {
        let vname = format_ident!("{}", state.name);
        let const_name = format_ident!("__PATH_{}", state.name.to_ascii_uppercase());
        let path_idents: Vec<_> = path
            .iter()
            .map(|&idx| {
                let name = format_ident!("{}", config.states[idx].name);
                quote! { #enum_ident::#name }
            })
            .collect();
        let len = path.len();
        path_statics.push(quote! {
            static #const_name: [#enum_ident; #len] = [#(#path_idents),*];
        });
        path_arms.push(quote! {
            Self::#vname => &#const_name
        });
    }

    // as_index() arms
    let as_index_arms: Vec<_> = config
        .states
        .iter()
        .enumerate()
        .map(|(i, s)| {
            let ident = format_ident!("{}", s.name);
            quote! { Self::#ident => #i }
        })
        .collect();

    let topology_impl = quote! {
        impl ::bloxide_core::topology::StateTopology for #enum_ident {
            const STATE_COUNT: usize = #state_count;

            #[inline]
            fn parent(self) -> ::core::option::Option<Self> {
                match self {
                    #(#parent_arms,)*
                }
            }

            #[inline]
            fn is_leaf(self) -> bool {
                match self {
                    #(#is_leaf_arms,)*
                }
            }

            fn path(self) -> &'static [Self] {
                #(#path_statics)*
                match self {
                    #(#path_arms,)*
                }
            }

            #[inline]
            fn as_index(self) -> usize {
                match self {
                    #(#as_index_arms,)*
                }
            }
        }
    };

    // The handler_table macro is always generated when there are states.
    // StateFns associated constants are generated by spec_skeleton.rs
    // (inside the MachineSpec impl block). Here we emit the
    // handler_table macro that references those associated constants.

    let fns_idents: Vec<_> = config
        .states
        .iter()
        .map(|s| format_ident!("{}_FNS", to_snake_case(&s.name).to_ascii_uppercase()))
        .collect();

    let macro_name_str = format!("{}_handler_table", to_snake_case(&enum_name_str));
    let macro_name = format_ident!("{}", macro_name_str);

    let handler_code = quote! {
        #[doc(hidden)]
        #[macro_export]
        macro_rules! #macro_name {
            ($ty:ty) => {
                &[#(&<$ty>::#fns_idents),*]
            };
        }
    };

    let tokens = quote! {
        #enum_def
        #topology_impl
        #handler_code
    };

    let raw = tokens.to_string();
    let file = syn::parse_str::<syn::File>(&raw)
        .map_err(|e| anyhow::anyhow!("syn parsing failed: {}", e))?;
    let formatted = prettyplease::unparse(&file);

    Ok(format!("{}{}", HEADER, formatted))
}
