// Copyright 2025 Bloxide, all rights reserved
//! Shared utilities for codegen modules.
//!
//! These functions are used by `events.rs`, `topology.rs`, `spec_skeleton.rs`
//! to convert between PascalCase, snake_case, and UPPER_SNAKE_CASE, and by
//! `lib.rs` for shared workspace discovery logic.

use crate::schema::BloxConfig;
use std::collections::BTreeMap;
use std::path::Path;

/// Standard copyright + auto-generated header for emitted files.
pub const HEADER: &str =
    "// Copyright 2025 Bloxide, all rights reserved\n// Auto-generated by bloxide-codegen. Do not edit manually.\n";

/// Extract the `[package] name = "..."` value from a Cargo.toml file.
pub fn parse_package_name(cargo_toml_path: &Path) -> Option<String> {
    let content = std::fs::read_to_string(cargo_toml_path).ok()?;
    content.lines().find_map(|line| {
        let trimmed = line.trim();
        if trimmed.starts_with("name = ") {
            let name = trimmed
                .strip_prefix("name = ")
                .unwrap()
                .trim()
                .trim_matches('"');
            Some(name.to_string())
        } else {
            None
        }
    })
}

/// Discover all `blox.toml` files under `workspace_root` (excluding `target/`),
/// parse each, and return a map keyed by the crate name from the sibling
/// `Cargo.toml` (falling back to the directory name).
pub fn discover_blox_configs(
    workspace_root: &Path,
) -> anyhow::Result<BTreeMap<String, BloxConfig>> {
    let mut blox_configs = BTreeMap::new();
    for entry in walkdir::WalkDir::new(workspace_root)
        .into_iter()
        .filter_entry(|e| e.file_name() != "target")
        .filter_map(|e| e.ok())
    {
        if entry.file_name() == "blox.toml" {
            let blox_content = std::fs::read_to_string(entry.path())?;
            let blox_config: BloxConfig = toml::from_str(&blox_content)?;
            let dir = entry.path().parent().unwrap();
            let cargo_toml_path = dir.join("Cargo.toml");
            let key = if cargo_toml_path.exists() {
                parse_package_name(&cargo_toml_path)
                    .unwrap_or_else(|| dir.file_name().unwrap().to_string_lossy().to_string())
            } else {
                dir.file_name().unwrap().to_string_lossy().to_string()
            };
            blox_configs.insert(key, blox_config);
        }
    }
    Ok(blox_configs)
}

/// Convert PascalCase to snake_case.
pub fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

/// Convert PascalCase to UPPER_SNAKE_CASE.
pub fn to_upper_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let chars: Vec<char> = s.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev_lower = chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit();
            let next_lower = chars.get(i + 1).is_some_and(|c| c.is_lowercase());
            if prev_lower || (chars[i - 1].is_uppercase() && next_lower) {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}
