// Copyright 2025 Bloxide, all rights reserved
// Auto-generated by bloxide-codegen. Do not edit manually.
use ::bloxide_core::lifecycle::LifecycleCommand;
#[cfg(feature = "dynamic")]
use ::bloxide_supervisor::dynamic_mailboxes::SupervisorMailboxes;
use ::bloxide_tokio::prelude::*;
use ::pool_blox::prelude::*;
use ::pool_messages::PoolMsg;
use ::pool_messages::SpawnWorker;
use ::tokio_pool_demo_impl::AppSpawnFactory;
::bloxide_tokio::actor_task_supervised!(pool_task, PoolSpec<TokioRuntime>);
#[cfg(not(feature = "dynamic"))]
::bloxide_tokio::root_task!(
    supervisor_task,
    ::bloxide_supervisor::supervisor::SupervisorSpec<TokioRuntime>
);
#[cfg(feature = "dynamic")]
::bloxide_tokio::root_task!(
    supervisor_task, ::bloxide_supervisor::supervisor::SupervisorSpec < TokioRuntime,
    AppSpawnFactory >
);
#[tokio::main]
async fn main() {
    tracing_log::LogTracer::init().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init()
        .ok();
    let ((pool_ref, spawn_reply_ref), pool_mbox) = ::bloxide_tokio::channels! {
        pool_messages::PoolMsg(16), pool_messages::SpawnedWorker < TokioRuntime > (16),
    };
    let pool_id = pool_ref.id();
    let spawn_id = ::bloxide_tokio::next_actor_id!();
    let (spawn_ref, spawn_rx) =
        <TokioRuntime as ::bloxide_core::capability::DynamicChannelCap>::channel::<
            AppSpawnRequest<TokioRuntime>,
        >(spawn_id, 16);
    let factory = AppSpawnFactory::new(pool_ref.clone());
    let pool_ctx = PoolCtx::new(
        pool_ref.clone(),
        pool_id,
        spawn_ref.clone(),
        spawn_reply_ref.clone(),
    );
    let pool_machine = ::bloxide_core::StateMachine::new(pool_ctx);
    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAllDone);
    ::bloxide_tokio::spawn_child!(
        group,
        pool_task(pool_machine, pool_mbox, pool_id),
        ChildPolicy::Stop
    );
    let _sup_control_ref_0 = group.control_ref();
    let sup_notify_0 = group.notify_ref();
    let _sup_kill_cap_0 = group.kill_cap().clone();
    let sup_id = ::bloxide_tokio::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();
    #[cfg(not(feature = "dynamic"))]
    let sup_ctx =
        ::bloxide_supervisor::supervisor::SupervisorCtx::new(children, sup_id, sup_notify_0);
    #[cfg(not(feature = "dynamic"))]
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::supervisor::SupervisorSpec<TokioRuntime>,
    >::new(sup_ctx);
    #[cfg(not(feature = "dynamic"))]
    sup_machine.dispatch(
        ::bloxide_supervisor::event::SupervisorEvent::<TokioRuntime>::Lifecycle(
            LifecycleCommand::Start,
        ),
    );
    #[cfg(feature = "dynamic")]
    let sup_ctx = ::bloxide_supervisor::supervisor::SupervisorCtx::new(
        children,
        sup_id,
        sup_notify_0,
        factory,
    );
    #[cfg(feature = "dynamic")]
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::supervisor::SupervisorSpec<TokioRuntime, AppSpawnFactory>,
    >::new(sup_ctx);
    #[cfg(feature = "dynamic")]
    sup_machine.dispatch(::bloxide_supervisor::event::SupervisorEvent::<
        TokioRuntime,
        AppSpawnFactory,
    >::Lifecycle(LifecycleCommand::Start));
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 0 }))
        .await;
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 1 }))
        .await;
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 2 }))
        .await;
    #[cfg(not(feature = "dynamic"))]
    supervisor_task(sup_machine, (sup_notify_rx, sup_control_rx)).await;
    #[cfg(feature = "dynamic")]
    {
        let sup_mailboxes = SupervisorMailboxes {
            child_rx: sup_notify_rx,
            control_rx: sup_control_rx,
            spawn_rx: spawn_rx,
        };
        supervisor_task(sup_machine, sup_mailboxes).await;
    }
    println!("tokio-pool-demo complete");
}
