// Auto-generated by bloxide-codegen. Do not edit manually.
use ::bloxide_core::capability::DynamicChannelCap;
use ::bloxide_tokio::prelude::*;
use ::bloxide_core::lifecycle::LifecycleCommand;
use ::pool_blox::prelude::*;
use ::pool_messages::SpawnWorker;
use ::pool_messages::PoolMsg;
use ::tokio_pool_demo_impl::AppSpawnFactory;
use ::bloxide_supervisor::dynamic_mailboxes::SupervisorMailboxes;

::bloxide_tokio::actor_task_supervised!(pool_task, PoolSpec < TokioRuntime >);
::bloxide_tokio::root_task!(
    supervisor_task,
    ::bloxide_supervisor::supervisor::SupervisorSpec < TokioRuntime, AppSpawnFactory >
);

#[tokio::main]
async fn main() {
    tracing_log::LogTracer::init().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init()
        .ok();

    // Pool domain channel + spawn reply channel (second stream of Pool mailboxes).
    let ((pool_ref, spawn_reply_ref), (pool_mbox_rx, spawn_reply_rx)) = ::bloxide_tokio::channels! {
        PoolMsg(16),
        SpawnedWorker<TokioRuntime>(16),
    };
    let pool_id = pool_ref.id();

    // Supervisor spawn request channel.
    let spawn_id = ::bloxide_tokio::next_actor_id!();
    let (spawn_ref, spawn_rx) =
        <TokioRuntime as DynamicChannelCap>::channel::<AppSpawnRequest<TokioRuntime>>(spawn_id, 16);

    // Build the supervisor's child group and wire the pool as a supervised child.
    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAnyDone);

    let factory = AppSpawnFactory::new(pool_ref.clone());

    let pool_ctx = PoolCtx::new(
        pool_ref.clone(),
        pool_id,
        spawn_ref.clone(),
        spawn_reply_ref.clone(),
    );
    let pool_machine = ::bloxide_core::StateMachine::new(pool_ctx);
    ::bloxide_tokio::spawn_child!(
        group,
        pool_task(pool_machine, (pool_mbox_rx, spawn_reply_rx), pool_id),
        ChildPolicy::Stop
    );

    // Supervisor references.
    let notify_ref = group.notify_ref();
    let _control_ref = group.control_ref();
    let _kill_cap = group.kill_cap().clone();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();

    // Create the dynamic supervisor.
    let sup_id = ::bloxide_tokio::next_actor_id!();
    let sup_ctx = ::bloxide_supervisor::supervisor::SupervisorCtx::new(
        children,
        sup_id,
        notify_ref,
        factory,
    );
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::supervisor::SupervisorSpec<TokioRuntime, AppSpawnFactory>,
    >::new(sup_ctx);
    sup_machine.dispatch(
        ::bloxide_supervisor::event::SupervisorEvent::<
            TokioRuntime,
            AppSpawnFactory,
        >::Lifecycle(LifecycleCommand::Start),
    );

    // Send work to the pool; each SpawnWorker triggers a 2-phase spawn via the supervisor.
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 0 }))
        .await;
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 1 }))
        .await;
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 2 }))
        .await;

    // Run the supervisor root task.
    let sup_mailboxes = SupervisorMailboxes {
        child_rx: sup_notify_rx,
        control_rx: sup_control_rx,
        spawn_rx,
    };
    supervisor_task(sup_machine, sup_mailboxes).await;
    println!("tokio-pool-demo complete");
}
