// Copyright 2025 Bloxide, all rights reserved
// Auto-generated by bloxide-codegen. Do not edit manually.
use ::bloxide_core::lifecycle::LifecycleCommand;
use ::bloxide_tokio::prelude::*;
use ::pool_blox::prelude::*;
use ::pool_messages::PoolMsg;
use ::pool_messages::SpawnWorker;
::bloxide_tokio::actor_task_supervised!(pool_task, PoolSpec<TokioRuntime>);
::bloxide_tokio::root_task!(
    supervisor_task,
    ::bloxide_supervisor::SupervisorSpec<TokioRuntime>
);
#[tokio::main]
async fn main() {
    tracing_log::LogTracer::init().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init()
        .ok();
    let ((pool_ref, spawn_reply_ref), pool_mbox) = ::bloxide_tokio::channels! {
        pool_messages::PoolMsg(16), pool_messages::SpawnedWorker < TokioRuntime > (16),
    };
    let pool_id = pool_ref.id();
    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAllDone);
    let sup_control_ref_0 = group.control_ref();
    let sup_notify_ref_0 = group.notify_ref();
    let pool_ctx = PoolCtx::new(
        pool_ref.clone(),
        pool_id,
        ::tokio_pool_demo_impl::spawn_worker as _,
        sup_control_ref_0.clone(),
        sup_notify_ref_0.clone(),
        spawn_reply_ref.clone(),
    );
    let pool_machine = ::bloxide_core::StateMachine::new(pool_ctx);
    ::bloxide_tokio::spawn_child!(
        group,
        pool_task(pool_machine, pool_mbox, pool_id),
        ChildPolicy::Stop
    );
    let sup_id = ::bloxide_tokio::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();
    let sup_ctx = ::bloxide_supervisor::SupervisorCtx::new(children, sup_id, sup_notify_ref_0);
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::SupervisorSpec<TokioRuntime>,
    >::new(sup_ctx);
    sup_machine.dispatch(
        ::bloxide_supervisor::SupervisorEvent::<TokioRuntime>::Lifecycle(LifecycleCommand::Start),
    );
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 0 }))
        .await;
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 1 }))
        .await;
    let _ = pool_ref
        .send(pool_id, PoolMsg::SpawnWorker(SpawnWorker { task_id: 2 }))
        .await;
    supervisor_task(sup_machine, (sup_notify_rx, sup_control_rx)).await;
    println!("tokio-pool-demo complete");
}
