#!/bin/bash
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"
cargo build -p cargo-blox --quiet

BLOX="$REPO_ROOT/target/debug/cargo-blox blox"

DEMO="demo/embassy"
rm -rf "$REPO_ROOT/$DEMO"
mkdir -p "$REPO_ROOT/$DEMO"
cd "$REPO_ROOT/$DEMO"

cat > Cargo.toml <<'INITIAL'
[workspace]
members = [
]
resolver = "2"

[workspace.package]
version = "0.0.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/bloxide-com/bloxide"

[workspace.dependencies]
INITIAL

# ── Layer 1: Messages ────────────────────────────────────────────────────────
$BLOX new-messages ping-pong
$BLOX add-message ping_pong-messages Ping round:u32
$BLOX add-message ping_pong-messages Pong round:u32
$BLOX add-message ping_pong-messages Resume

# ── Layer 2: Actions ────────────────────────────────────────────────────────
$BLOX new-actions ping-pong

# ── Layer 4: Blox — Ping ───────────────────────────────────────────────────
# Don't use --actions here; we manually define the full [context] section below
$BLOX new ping --messages ping_pong-messages
$BLOX add-state ping Operating --composite
$BLOX add-state ping Active --parent Operating
$BLOX add-state ping Paused --parent Operating
$BLOX add-state ping Done --terminal
$BLOX add-state ping Error --error

# ── Layer 4: Blox — Pong ───────────────────────────────────────────────────
$BLOX new pong --messages ping_pong-messages
$BLOX add-state pong Ready

# ── Patch Ping blox.toml: add mailboxes, context, state flags ──────────────
# Remove default [context] and [[event.mailboxes]] added by `cargo blox new` so we can replace them
python3 -c "
import re
with open('crates/bloxes/ping/blox.toml') as f:
    txt = f.read()
# Remove default [context] section
txt = re.sub(r'\[context\]\n[^\[]+', '', txt, count=1)
# Remove default [[event.mailboxes]]
txt = re.sub(r'\[\[event\.mailboxes\]\]\n[^\[]+', '', txt, count=1)
with open('crates/bloxes/ping/blox.toml', 'w') as f:
    f.write(txt)
"
cat >> crates/bloxes/ping/blox.toml <<'PING_TOML'

[context]
name = "PingCtx"
generics = "<R: BloxRuntime, B: HasCurrentTimer + CountsRounds>"
actions_crate = "ping_pong_actions"

[[context.fields]]
name = "self_id"
ty = "ActorId"

[[context.fields]]
name = "peer_ref"
ty = "ActorRef<PingPongMsg, R>"

[[context.fields]]
name = "self_ref"
ty = "ActorRef<PingPongMsg, R>"

[[context.fields]]
name = "timer_ref"
ty = "ActorRef<TimerCommand, R>"

[[context.fields]]
name = "behavior"
ty = "B"
delegates = ["HasCurrentTimer", "CountsRounds"]

[[event.mailboxes]]
variant = "Msg"
message = "PingPongMsg"
message_path = "ping_pong_messages::PingPongMsg"
PING_TOML

python3 -c "
import re
with open('crates/bloxes/ping/blox.toml') as f:
    txt = f.read()
# Add initial = true after 'parent = \"Operating\"' in the Active state block
txt = re.sub(
    r'(\[\[topology\.states\]\]\nname = \"Active\"\nparent = \"Operating\")',
    r'\1\ninitial = true',
    txt
)
with open('crates/bloxes/ping/blox.toml', 'w') as f:
    f.write(txt)
"

# ── Patch Pong blox.toml: add mailboxes, context, state flags ──────────────
python3 -c "
import re
with open('crates/bloxes/pong/blox.toml') as f:
    txt = f.read()
txt = re.sub(r'\[context\]\n[^\[]+', '', txt, count=1)
txt = re.sub(r'\[\[event\.mailboxes\]\]\n[^\[]+', '', txt, count=1)
with open('crates/bloxes/pong/blox.toml', 'w') as f:
    f.write(txt)
"
cat >> crates/bloxes/pong/blox.toml <<'PONG_TOML'

[context]
name = "PongCtx"
generics = "<R: BloxRuntime>"
actions_crate = "ping_pong_actions"

[[context.fields]]
name = "self_id"
ty = "ActorId"

[[context.fields]]
name = "peer_ref"
ty = "ActorRef<PingPongMsg, R>"

[[event.mailboxes]]
variant = "Msg"
message = "PingPongMsg"
message_path = "ping_pong_messages::PingPongMsg"
PONG_TOML

python3 -c "
import re
with open('crates/bloxes/pong/blox.toml') as f:
    txt = f.read()
# Add initial = true after 'name = \"Ready\"' in the Ready state block
txt = re.sub(
    r'(\[\[topology\.states\]\]\nname = \"Ready\")',
    r'\1\ninitial = true',
    txt
)
with open('crates/bloxes/pong/blox.toml', 'w') as f:
    f.write(txt)
"

# ── Generate all boilerplate from TOML ───────────────────────────────────────
$BLOX generate

# ── Fix generated spec_skeleton.rs — overwrite with correct generics ─────────
cat > crates/bloxes/ping/src/generated/spec_skeleton.rs <<'PING_SPEC'
// Auto-generated by bloxide-codegen. Do not edit manually.
use core::marker::PhantomData;
use bloxide_core::{
    capability::BloxRuntime,
    spec::{MachineSpec, StateFns},
    HasSelfId,
};
use ping_pong_actions::{HasCurrentTimer, CountsRounds};
use ping_pong_messages::PingPongMsg;

use crate::{PingCtx, PingEvent};
pub use crate::generated::topology::PingState;

pub struct PingSpec<R: BloxRuntime, B: HasCurrentTimer + CountsRounds>(PhantomData<(R, B)>);

impl<R, B> MachineSpec for PingSpec<R, B>
where
    R: BloxRuntime,
    B: HasCurrentTimer + CountsRounds + Default + 'static,
    B::Round: Into<u32>,
{
    type State = PingState;
    type Event = PingEvent;
    type Ctx = PingCtx<R, B>;
    type Mailboxes<Rt: BloxRuntime> = (Rt::Stream<PingPongMsg>,);

    const HANDLER_TABLE: &'static [&'static StateFns<Self>] = ping_state_handler_table!(Self);

    fn initial_state() -> PingState {
        PingState::Active
    }

    fn is_terminal(state: &PingState) -> bool {
        matches!(state, PingState::Done)
    }

    fn is_error(state: &PingState) -> bool {
        matches!(state, PingState::Error)
    }

    fn on_init_entry(ctx: &mut PingCtx<R, B>) {
        ctx.behavior = B::default();
        bloxide_log::blox_log_info!(ctx.self_id(), "reset — behavior cleared");
    }
}
PING_SPEC

cat > crates/bloxes/pong/src/generated/spec_skeleton.rs <<'PONG_SPEC'
// Auto-generated by bloxide-codegen. Do not edit manually.
use core::marker::PhantomData;
use bloxide_core::{
    capability::BloxRuntime,
    spec::{MachineSpec, StateFns},
};
use ping_pong_messages::PingPongMsg;

use crate::{PongCtx, PongEvent};
pub use crate::generated::topology::PongState;

pub struct PongSpec<R: BloxRuntime>(PhantomData<R>);

impl<R: BloxRuntime> MachineSpec for PongSpec<R> {
    type State = PongState;
    type Event = PongEvent;
    type Ctx = PongCtx<R>;
    type Mailboxes<Rt: BloxRuntime> = (Rt::Stream<PingPongMsg>,);

    const HANDLER_TABLE: &'static [&'static StateFns<Self>] = pong_state_handler_table!(Self);

    fn initial_state() -> PongState {
        PongState::Ready
    }

    fn on_init_entry(_ctx: &mut PongCtx<R>) {}
}
PONG_SPEC

# ── Fix generated ctx.rs — overwrite with correct imports ────────────────────
cat > crates/bloxes/ping/src/generated/ctx.rs <<'PING_CTX'
// Auto-generated by bloxide-codegen. Do not edit manually.
use bloxide_core::{ActorId, capability::BloxRuntime, messaging::ActorRef};
use bloxide_macros::BloxCtx;
use bloxide_timer::{HasTimerRef, TimerCommand, TimerId};
use ping_pong_actions::{
    CountsRounds, HasCurrentTimer, HasPeerRef, HasSelfRef,
    __delegate_CountsRounds, __delegate_HasCurrentTimer,
};
use ping_pong_messages::PingPongMsg;

#[derive(BloxCtx)]
pub struct PingCtx<R: BloxRuntime, B: HasCurrentTimer + CountsRounds> {
    pub self_id: ActorId,
    pub peer_ref: ActorRef<PingPongMsg, R>,
    pub self_ref: ActorRef<PingPongMsg, R>,
    pub timer_ref: ActorRef<TimerCommand, R>,
    #[delegates(HasCurrentTimer, CountsRounds)]
    pub behavior: B,
}
PING_CTX

cat > crates/bloxes/pong/src/generated/ctx.rs <<'PONG_CTX'
// Auto-generated by bloxide-codegen. Do not edit manually.
use bloxide_core::{capability::BloxRuntime, ActorId, ActorRef};
use bloxide_macros::BloxCtx;
use ping_pong_actions::HasPeerRef;
use ping_pong_messages::PingPongMsg;

#[derive(BloxCtx)]
pub struct PongCtx<R: BloxRuntime> {
    pub self_id: ActorId,
    pub peer_ref: ActorRef<PingPongMsg, R>,
}
PONG_CTX

# ── Patch blox Cargo.toml files — add missing dependencies ──────────────────
cat > crates/bloxes/ping/Cargo.toml <<'PING_CARGO'
[package]
name = "ping-blox"
version.workspace = true
edition.workspace = true
description = "Ping actor blox — runtime-agnostic"
repository.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["bloxide-core/std", "bloxide-log/log"]

[dependencies]
bloxide-core   = { workspace = true, features = ["alloc"] }
bloxide-macros = { workspace = true }
bloxide-log    = { workspace = true }
bloxide-timer  = { workspace = true, features = ["alloc"] }
ping_pong-messages = { workspace = true }
ping_pong-actions  = { workspace = true }
PING_CARGO

cat > crates/bloxes/pong/Cargo.toml <<'PONG_CARGO'
[package]
name = "pong-blox"
version.workspace = true
edition.workspace = true
description = "Pong actor blox — runtime-agnostic"
repository.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["bloxide-core/std", "bloxide-log/log"]

[dependencies]
bloxide-core   = { workspace = true, features = ["alloc"] }
bloxide-macros = { workspace = true }
bloxide-log    = { workspace = true }
ping_pong-messages = { workspace = true }
ping_pong-actions  = { workspace = true }
PONG_CARGO

# ── Patch actions crate Cargo.toml — add missing dependencies ─────────────────
cat > crates/actions/ping_pong-actions/Cargo.toml <<'ACTIONS_CARGO'
[package]
name = "ping_pong-actions"
version.workspace = true
edition.workspace = true
description = "Action traits and generic functions for PingPong"
repository.workspace = true
license.workspace = true

[dependencies]
bloxide-core   = { workspace = true, features = ["alloc"] }
bloxide-macros = { workspace = true }
bloxide-timer  = { workspace = true, features = ["alloc"] }
ping_pong-messages = { workspace = true }
ACTIONS_CARGO

# ── Write ping-pong-actions (trait + generic functions) ──────────────────────
cat > crates/actions/ping_pong-actions/src/lib.rs <<'ACTIONS'
#![no_std]

use bloxide_core::{
    accessor::HasSelfId, capability::BloxRuntime, messaging::ActorRef, transition::ActionResult,
};
use bloxide_macros::delegatable;
use bloxide_timer::{cancel_timer, set_timer, HasTimerRef, TimerId};
use ping_pong_messages::{Ping, PingPongMsg, Pong, Resume};

pub trait HasPeerRef<R: BloxRuntime> {
    fn peer_ref(&self) -> &ActorRef<PingPongMsg, R>;
}

pub trait HasSelfRef<R: BloxRuntime> {
    fn self_ref(&self) -> &ActorRef<PingPongMsg, R>;
}

#[delegatable]
pub trait CountsRounds {
    type Round: Copy + PartialEq + PartialOrd
        + core::ops::Add<Output = Self::Round>
        + From<u8> + core::fmt::Display;
    fn round(&self) -> Self::Round;
    fn set_round(&mut self, round: Self::Round);
}

#[delegatable]
pub trait HasCurrentTimer {
    fn current_timer(&self) -> Option<TimerId>;
    fn set_current_timer(&mut self, timer: Option<TimerId>);
}

pub fn increment_round<C: CountsRounds>(ctx: &mut C) {
    let one = C::Round::from(1);
    ctx.set_round(ctx.round() + one);
}

pub fn send_initial_ping<R, C>(ctx: &mut C)
where
    R: BloxRuntime,
    C: HasSelfId + HasPeerRef<R> + CountsRounds,
    C::Round: Into<u32>,
{
    if ctx.round() == C::Round::from(1) {
        let _ = ctx.peer_ref().try_send(
            ctx.self_id(),
            PingPongMsg::Ping(Ping { round: ctx.round().into() }),
        );
    }
}

pub fn send_ping<R, C>(ctx: &mut C) -> ActionResult
where
    R: BloxRuntime,
    C: HasSelfId + HasPeerRef<R> + CountsRounds,
    C::Round: Into<u32>,
{
    ActionResult::from(ctx.peer_ref().try_send(
        ctx.self_id(),
        PingPongMsg::Ping(Ping { round: ctx.round().into() }),
    ))
}

pub fn send_pong<R, C>(ctx: &mut C, ping: &Ping) -> ActionResult
where
    R: BloxRuntime,
    C: HasSelfId + HasPeerRef<R>,
{
    ActionResult::from(
        ctx.peer_ref()
            .try_send(ctx.self_id(), PingPongMsg::Pong(Pong { round: ping.round })),
    )
}

pub fn schedule_resume<R, C>(ctx: &mut C, duration_ms: u64)
where
    R: BloxRuntime,
    C: HasSelfRef<R> + HasTimerRef<R> + HasSelfId + HasCurrentTimer,
{
    let id = set_timer::<R, C, PingPongMsg>(
        ctx, duration_ms, ctx.self_ref(), PingPongMsg::Resume(Resume),
    );
    ctx.set_current_timer(Some(id));
}

pub fn cancel_current_timer<R, C>(ctx: &mut C)
where
    R: BloxRuntime,
    C: HasSelfId + HasTimerRef<R> + HasCurrentTimer,
{
    if let Some(id) = ctx.current_timer() {
        cancel_timer::<R, C>(ctx, id);
        ctx.set_current_timer(None);
    }
}
ACTIONS

# ── Write Ping actions ──────────────────────────────────────────────────────
cat > crates/bloxes/ping/src/actions.rs <<'PING_ACTIONS'
use crate::{PingCtx, PingEvent, PingSpec, PingState, MAX_ROUNDS, PAUSE_AT_ROUND, PAUSE_DURATION_MS};
use bloxide_core::{
    capability::BloxRuntime, spec::StateFns, transition::ActionResult, transitions, HasSelfId,
};
use ping_pong_actions::{
    cancel_current_timer, increment_round, schedule_resume, send_initial_ping, send_ping,
    CountsRounds, HasCurrentTimer,
};
use ping_pong_messages::PingPongMsg;

impl<R, B> PingSpec<R, B>
where
    R: BloxRuntime,
    B: HasCurrentTimer + CountsRounds + Default + 'static,
    B::Round: Into<u32>,
{
    fn forward_ping(ctx: &mut PingCtx<R, B>, _ev: &PingEvent) -> ActionResult {
        send_ping::<R, _>(ctx)
    }

    fn schedule_pause_timer(ctx: &mut PingCtx<R, B>) {
        schedule_resume::<R, _>(ctx, PAUSE_DURATION_MS);
        bloxide_log::blox_log_info!(
            ctx.self_id(),
            "paused — resuming in {}ms",
            PAUSE_DURATION_MS
        );
    }

    fn cancel_pause_timer(ctx: &mut PingCtx<R, B>) {
        cancel_current_timer::<R, _>(ctx);
    }

    fn log_round(ctx: &mut PingCtx<R, B>) {
        bloxide_log::blox_log_info!(ctx.self_id(), "round {} — sending Ping", ctx.round());
    }

    fn log_done(ctx: &mut PingCtx<R, B>) {
        bloxide_log::blox_log_info!(ctx.self_id(), "done after {} rounds", ctx.round());
    }

    pub(crate) const OPERATING_FNS: StateFns<Self> = StateFns {
        on_entry: &[],
        on_exit: &[],
        transitions: transitions![
            PingPongMsg::Pong(_) => stay,
        ],
    };

    pub(crate) const ACTIVE_FNS: StateFns<Self> = StateFns {
        on_entry: &[increment_round, Self::log_round, send_initial_ping],
        on_exit: &[],
        transitions: transitions![
            PingPongMsg::Pong(_) => {
                actions [Self::forward_ping]
                guard(ctx, _results) {
                    ctx.round() >= B::Round::from(MAX_ROUNDS)     => PingState::Done,
                    ctx.round() == B::Round::from(PAUSE_AT_ROUND) => PingState::Paused,
                    _                                             => PingState::Active,
                }
            },
        ],
    };

    pub(crate) const PAUSED_FNS: StateFns<Self> = StateFns {
        on_entry: &[Self::schedule_pause_timer],
        on_exit: &[Self::cancel_pause_timer],
        transitions: transitions![
            PingPongMsg::Resume(_resume) => {
                actions [Self::forward_ping]
                transition PingState::Active
            },
        ],
    };

    pub(crate) const DONE_FNS: StateFns<Self> = StateFns {
        on_entry: &[Self::log_done],
        on_exit: &[],
        transitions: &[],
    };

    pub(crate) const ERROR_FNS: StateFns<Self> = StateFns {
        on_entry: &[],
        on_exit: &[],
        transitions: &[],
    };
}
PING_ACTIONS

# ── Write Ping lib.rs ───────────────────────────────────────────────────────
cat > crates/bloxes/ping/src/lib.rs <<'PING_LIB'
#![no_std]

#[cfg(feature = "std")]
extern crate std;

pub mod generated;
pub mod actions;
pub mod prelude;

#[cfg(all(test, feature = "std"))]
mod tests;

pub use generated::*;

pub const MAX_ROUNDS: u8 = 5;
pub const PAUSE_AT_ROUND: u8 = 2;
pub const PAUSE_DURATION_MS: u64 = 150;
PING_LIB

# ── Write Pong actions ──────────────────────────────────────────────────────
cat > crates/bloxes/pong/src/actions.rs <<'PONG_ACTIONS'
use crate::prelude::*;
use bloxide_core::{capability::BloxRuntime, spec::StateFns, transition::ActionResult, transitions};
use ping_pong_actions::send_pong;
use ping_pong_messages::PingPongMsg;

impl<R: BloxRuntime> PongSpec<R> {
    fn reply_pong_action(ctx: &mut PongCtx<R>, ev: &PongEvent) -> ActionResult {
        if let Some(PingPongMsg::Ping(ping)) = ev.msg_payload() {
            return send_pong::<R, _>(ctx, &ping);
        }
        ActionResult::Ok
    }

    pub const READY_FNS: StateFns<Self> = StateFns {
        on_entry: &[],
        on_exit: &[],
        transitions: transitions![
            PingPongMsg::Ping(_) => {
                actions [Self::reply_pong_action]
                stay
            },
        ],
    };
}
PONG_ACTIONS

# ── Rewrite workspace Cargo.toml with full deps + binary ───────────────────
cat > Cargo.toml <<'WORKSPACE'
[workspace]
members = [
    "crates/messages/ping_pong-messages",
    "crates/actions/ping_pong-actions",
    "crates/bloxes/ping",
    "crates/bloxes/pong",
    "apps/embassy-demo",
]
resolver = "2"

[workspace.package]
version = "0.0.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/bloxide-com/bloxide"

[workspace.dependencies]
bloxide-core         = { path = "../../crates/bloxide-core" }
bloxide-embassy      = { path = "../../runtimes/bloxide-embassy", features = ["std"] }
bloxide-macros       = { path = "../../crates/bloxide-macros" }
bloxide-log          = { path = "../../crates/bloxide-log", features = ["log"] }
bloxide-timer        = { path = "../../crates/bloxide-timer" }
ping_pong-messages   = { path = "crates/messages/ping_pong-messages" }
ping_pong-actions    = { path = "crates/actions/ping_pong-actions" }
ping-blox            = { path = "crates/bloxes/ping" }
pong-blox            = { path = "crates/bloxes/pong" }
embassy-executor     = { version = "0.9", features = ["arch-std", "executor-thread"] }
embassy-sync        = { version = "0.7" }
embassy-time        = { version = "0.5", features = ["std", "generic-queue-8"] }
critical-section    = { version = "1.2", features = ["std"] }
static_cell         = "2"
log                 = "0.4"
env_logger          = "0.11"

[profile.dev]
panic = "abort"
WORKSPACE

# ── Layer 5: Binary (Embassy) ───────────────────────────────────────────────
mkdir -p apps/embassy-demo/src

cat > apps/embassy-demo/Cargo.toml <<'CRATE'
[package]
name = "embassy-demo"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bloxide-core       = { workspace = true, features = ["std"] }
bloxide-embassy    = { workspace = true }
bloxide-log        = { workspace = true }
bloxide-timer      = { workspace = true, features = ["std"] }
ping-blox          = { workspace = true }
pong-blox          = { workspace = true }
ping_pong-messages = { workspace = true }
ping_pong-actions  = { workspace = true }
embassy-executor   = { workspace = true }
embassy-sync       = { workspace = true }
embassy-time       = { workspace = true }
critical-section   = { workspace = true }
static_cell        = { workspace = true }
log                = { workspace = true }
env_logger         = { workspace = true }
CRATE

cat > apps/embassy-demo/src/main.rs <<'MAIN'
use bloxide_embassy::prelude::*;
use bloxide_core::lifecycle::LifecycleCommand;
use bloxide_timer::TimerId;
use ping_blox::prelude::*;
use ping_pong_actions::{CountsRounds, HasCurrentTimer};
use ping_pong_messages::prelude::*;
use pong_blox::prelude::*;

#[derive(Debug, Default, Clone)]
struct DemoBehavior {
    round: u32,
    current_timer: Option<TimerId>,
}

impl CountsRounds for DemoBehavior {
    type Round = u32;
    fn round(&self) -> u32 { self.round }
    fn set_round(&mut self, round: u32) { self.round = round; }
}

impl HasCurrentTimer for DemoBehavior {
    fn current_timer(&self) -> Option<TimerId> { self.current_timer }
    fn set_current_timer(&mut self, timer: Option<TimerId>) { self.current_timer = timer; }
}

bloxide_embassy::timer_task!(timer_task);
bloxide_embassy::root_task!(
    supervisor_task,
    SupervisorSpec<EmbassyRuntime>,
    std::process::exit(0)
);
bloxide_embassy::actor_task_supervised!(ping_task, PingSpec<EmbassyRuntime, DemoBehavior>);
bloxide_embassy::actor_task_supervised!(pong_task, PongSpec<EmbassyRuntime>);

static EXECUTOR: static_cell::StaticCell<embassy_executor::Executor> =
    static_cell::StaticCell::new();

fn main() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let executor = EXECUTOR.init(embassy_executor::Executor::new());
    executor.run(setup);
}

fn setup(spawner: Spawner) {
    let timer_ref = bloxide_embassy::spawn_timer!(spawner, timer_task, 8);

    let ((ping_ref,), ping_mbox) = bloxide_embassy::channels! {
        PingPongMsg(16),
    };
    let ping_id = ping_ref.id();

    let ((pong_ref,), pong_mbox) = bloxide_embassy::channels! {
        PingPongMsg(16),
    };
    let pong_id = pong_ref.id();

    log::info!("setup: ping_id={} pong_id={}", ping_id, pong_id);

    let ping_ctx = PingCtx::new(
        ping_id,
        pong_ref.clone(),
        ping_ref.clone(),
        timer_ref,
        DemoBehavior::default(),
    );
    let pong_ctx = PongCtx::new(pong_id, ping_ref);

    let ping_machine = StateMachine::new(ping_ctx);
    let pong_machine = StateMachine::new(pong_ctx);

    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAnyDone);
    bloxide_embassy::spawn_child!(
        spawner,
        group,
        ping_task(ping_machine, ping_mbox, ping_id),
        ChildPolicy::Restart { max: 1 }
    );
    bloxide_embassy::spawn_child!(
        spawner,
        group,
        pong_task(pong_machine, pong_mbox, pong_id),
        ChildPolicy::Stop
    );
    let _sup_control_ref = group.control_ref();
    let sup_id = bloxide_embassy::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();

    log::info!("supervisor setup: sup_id={}", sup_id);

    let sup_ctx = SupervisorCtx::new(sup_id, children);
    let mut sup_machine = StateMachine::new(sup_ctx);
    sup_machine.dispatch(SupervisorEvent::<EmbassyRuntime>::Lifecycle(
        LifecycleCommand::Start,
    ));

    spawner.must_spawn(supervisor_task(
        sup_machine,
        (sup_notify_rx, sup_control_rx),
    ));
}
MAIN

cargo run -p embassy-demo
