#!/bin/bash
set -e

# Build the cargo-blox tool first
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"
cargo build -p cargo-blox --quiet

BLOX="cargo run -p cargo-blox --quiet -- blox"

DEMO="demo/tokio-pool"
rm -rf "$REPO_ROOT/$DEMO"
mkdir -p "$REPO_ROOT/$DEMO"
cd "$REPO_ROOT/$DEMO"

# ── Workspace Cargo.toml ────────────────────────────────────────────────────
cat > Cargo.toml <<'WORKSPACE'
[workspace]
members = [
    "crates/messages/pool-messages",
    "crates/actions/pool-actions",
    "crates/bloxes/pool",
    "apps/tokio-pool",
]
resolver = "2"

[workspace.package]
version = "0.0.3"
edition = "2021"

[workspace.dependencies]
bloxide-core      = { path = "../../../crates/bloxide-core" }
bloxide-tokio     = { path = "../../../runtimes/bloxide-tokio" }
bloxide-macros    = { path = "../../../crates/bloxide-macros" }
bloxide-log       = { path = "../../../crates/bloxide-log", features = ["log"] }
pool-messages     = { path = "crates/messages/pool-messages" }
pool-actions      = { path = "crates/actions/pool-actions" }
pool-blox         = { path = "crates/bloxes/pool" }

[profile.dev]
panic = "abort"
WORKSPACE

# ── Layer 1: Messages ─────────────────────────────────────────────────────
$BLOX new-messages pool
$BLOX add-message pool-messages SpawnWorker task_id:u32
$BLOX add-message pool-messages WorkDone task_id:u32

# ── Layer 2: Actions ────────────────────────────────────────────────────────
$BLOX new-actions pool

# Overwrite scaffolded actions with pool-specific trait and functions
cat > crates/actions/pool-actions/src/lib.rs <<'ACTIONS_LIB'
// Copyright 2025 Bloxide, all rights reserved
#![no_std]

use bloxide_macros::delegatable;

pub mod prelude {
    pub use crate::*;
}

#[delegatable]
pub trait HasPendingCount {
    fn pending(&self) -> u32;
    fn set_pending(&mut self, count: u32);
}

pub fn increment_pending<C: HasPendingCount>(ctx: &mut C) {
    ctx.set_pending(ctx.pending() + 1);
}

pub fn decrement_pending<C: HasPendingCount>(ctx: &mut C) {
    if ctx.pending() > 0 {
        ctx.set_pending(ctx.pending() - 1);
    }
}
ACTIONS_LIB

# ── Layer 4: Pool blox ──────────────────────────────────────────────────────
$BLOX new pool --messages pool-messages --actions pool-actions

# Add states (these update blox.toml, which we then overwrite with the
# complete spec including mailboxes, context, and initial/terminal flags)
$BLOX add-state pool Idle
$BLOX add-state pool Active
$BLOX add-state pool AllDone

# Overwrite blox.toml with the full spec — the CLI scaffolds structure but
# does not yet generate [[event.mailboxes]] or [context] sections automatically.
cat > crates/bloxes/pool/blox.toml <<'BLOX_TOML'
[actor]
name = "Pool"

[event]
name = "PoolEvent"

[[event.mailboxes]]
variant = "Msg"
message = "PoolMsg"
message_path = "pool_messages::PoolMsg"

[context]
name = "PoolCtx"
generics = "<B: HasPendingCount>"
actions_crate = "pool_actions"

[[context.fields]]
name = "self_id"
ty = "ActorId"

[[context.fields]]
name = "behavior"
ty = "B"
delegates = ["HasPendingCount"]

[topology]
handler_fns = ["IDLE_FNS", "ACTIVE_FNS", "ALL_DONE_FNS"]

[[topology.states]]
name = "Idle"
initial = true

[[topology.states]]
name = "Active"

[[topology.states]]
name = "AllDone"
terminal = true
BLOX_TOML

# Generate boilerplate from TOML
$BLOX generate

# Fix generated spec_skeleton — codegen currently emits "B: 'static" instead
# of the full trait bound needed by the action functions.
cat > crates/bloxes/pool/src/generated/spec_skeleton.rs <<'SPEC'
// Auto-generated by bloxide-codegen. Do not edit manually.
use core::marker::PhantomData;

use ::bloxide_core::capability::BloxRuntime;
use ::bloxide_core::spec::{MachineSpec, StateFns};
use pool_actions::HasPendingCount;

use super::ctx::PoolCtx;
use super::events::PoolEvent;
use super::topology::PoolState;
use crate::pool_state_handler_table;

pub struct PoolSpec<R, B>(PhantomData<(R, B)>)
where
    R: BloxRuntime,
    B: HasPendingCount + 'static;

impl<R, B> MachineSpec for PoolSpec<R, B>
where
    R: BloxRuntime,
    B: HasPendingCount + 'static,
{
    type State = PoolState;
    type Event = PoolEvent;
    type Ctx = PoolCtx<B>;
    type Mailboxes<Rt: ::bloxide_core::capability::BloxRuntime> =
        (Rt::Stream<pool_messages::PoolMsg>,);

    const HANDLER_TABLE: &'static [&'static StateFns<Self>] = pool_state_handler_table!(Self);

    fn initial_state() -> PoolState {
        PoolState::Idle
    }

    fn is_terminal(state: &PoolState) -> bool {
        matches!(state, PoolState::AllDone)
    }

    fn on_init_entry(_ctx: &mut PoolCtx<B>) {}
}
SPEC

# ── Write pool action functions (the only user-edited blox file) ─────────────
cat > crates/bloxes/pool/src/actions.rs <<'ACTIONS'
// Copyright 2025 Bloxide, all rights reserved
use crate::prelude::*;
use bloxide_core::{
    capability::BloxRuntime, spec::StateFns, transition::ActionResult, transitions,
    HasSelfId,
};
use pool_actions::{decrement_pending, increment_pending, HasPendingCount};
use pool_messages::PoolMsg;

impl<R: BloxRuntime, B: HasPendingCount + 'static> PoolSpec<R, B> {
    fn handle_spawn_worker(ctx: &mut PoolCtx<B>, ev: &PoolEvent) -> ActionResult {
        if let Some(PoolMsg::SpawnWorker(_sw)) = ev.msg_payload() {
            increment_pending(ctx);
        }
        ActionResult::Ok
    }

    fn handle_work_done(ctx: &mut PoolCtx<B>, ev: &PoolEvent) -> ActionResult {
        if let Some(PoolMsg::WorkDone(_wd)) = ev.msg_payload() {
            decrement_pending(ctx);
        }
        ActionResult::Ok
    }

    fn on_all_done(ctx: &mut PoolCtx<B>) {
        ctx.set_pending(0);
    }
}

impl<R: BloxRuntime, B: HasPendingCount + 'static> PoolSpec<R, B> {
    pub const IDLE_FNS: StateFns<Self> = StateFns {
        on_entry: &[],
        on_exit: &[],
        transitions: transitions![
            PoolMsg::SpawnWorker(_) => {
                actions [Self::handle_spawn_worker]
                transition PoolState::Active
            },
        ],
    };

    pub const ACTIVE_FNS: StateFns<Self> = StateFns {
        on_entry: &[],
        on_exit: &[],
        transitions: transitions![
            PoolMsg::SpawnWorker(_) => {
                actions [Self::handle_spawn_worker]
                stay
            },
            PoolMsg::WorkDone(_) => {
                actions [Self::handle_work_done]
                guard(ctx, _results) {
                    ctx.pending() == 0 => PoolState::AllDone,
                    _ => stay,
                }
            },
        ],
    };

    pub const ALL_DONE_FNS: StateFns<Self> = StateFns {
        on_entry: &[Self::on_all_done],
        on_exit: &[],
        transitions: &[],
    };
}
ACTIONS

# ── Layer 5: Binary ─────────────────────────────────────────────────────────
mkdir -p apps/tokio-pool/src

cat > apps/tokio-pool/Cargo.toml <<'CRATE'
[package]
name = "tokio-pool"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bloxide-core      = { workspace = true, features = ["std"] }
bloxide-tokio     = { workspace = true }
bloxide-log       = { workspace = true }
pool-blox         = { workspace = true, features = ["std"] }
pool-messages     = { workspace = true }
pool-actions      = { workspace = true }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.2"
CRATE

cat > apps/tokio-pool/src/main.rs <<'MAIN'
use bloxide_core::lifecycle::LifecycleCommand;
use bloxide_tokio::prelude::*;
use pool_blox::prelude::*;
use pool_messages::prelude::*;

#[derive(Default)]
struct DemoBehavior {
    pending: u32,
}

impl pool_actions::HasPendingCount for DemoBehavior {
    fn pending(&self) -> u32 {
        self.pending
    }
    fn set_pending(&mut self, count: u32) {
        self.pending = count;
    }
}

bloxide_tokio::actor_task_supervised!(pool_task, PoolSpec<TokioRuntime, DemoBehavior>);
bloxide_tokio::root_task!(supervisor_task, SupervisorSpec<TokioRuntime>);

#[tokio::main]
async fn main() {
    tracing_log::LogTracer::init().ok();
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::new("info"))
        .try_init()
        .ok();

    let ((pool_ref,), pool_mbox) = bloxide_tokio::channels! {
        PoolMsg(32),
    };
    let pool_id = pool_ref.id();

    let machine =
        StateMachine::<PoolSpec<TokioRuntime, DemoBehavior>>::new(
            PoolCtx::new(pool_id, DemoBehavior::default()),
        );

    let mut group =
        ChildGroupBuilder::new(GroupShutdown::WhenAnyDone);
    bloxide_tokio::spawn_child!(
        group,
        pool_task(machine, pool_mbox, pool_id),
        ChildPolicy::Stop
    );
    let _sup_control_ref = group.control_ref();
    let _sup_notify = group.notify_sender();
    let sup_id = bloxide_tokio::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();

    let sup_ctx = SupervisorCtx::new(sup_id, children);
    let mut sup_machine =
        StateMachine::<SupervisorSpec<TokioRuntime>>::new(sup_ctx);
    sup_machine.dispatch(SupervisorEvent::<TokioRuntime>::Lifecycle(
        LifecycleCommand::Start,
    ));

    tracing::info!(pool_id, sup_id, "pool and supervisor created");

    // Send 3 SpawnWorker messages → Idle transitions to Active
    for task_id in 0..3u32 {
        pool_ref
            .try_send(
                pool_id,
                PoolMsg::SpawnWorker(SpawnWorker { task_id }),
            )
            .expect("pool mailbox should accept SpawnWorker");
    }

    // Send 3 WorkDone messages → Active transitions to AllDone
    for task_id in 0..3u32 {
        pool_ref
            .try_send(
                pool_id,
                PoolMsg::WorkDone(WorkDone { task_id }),
            )
            .expect("pool mailbox should accept WorkDone");
    }

    supervisor_task(sup_machine, (sup_notify_rx, sup_control_rx)).await;

    println!("tokio-pool-demo complete");
}
MAIN

cargo run -p tokio-pool
