// Copyright 2025 Bloxide, all rights reserved
// Auto-generated by bloxide-codegen. Do not edit manually.
use ::bloxide_tokio::prelude::*;
use ::bloxide_core::lifecycle::LifecycleCommand;
use ::ping_blox::prelude::*;
use ::pong_blox::prelude::*;
use ::embassy_demo_impl::PingBehavior;
::bloxide_tokio::actor_task_supervised!(
    ping_task, PingSpec < TokioRuntime, PingBehavior >
);
::bloxide_tokio::actor_task_supervised!(pong_task, PongSpec < TokioRuntime >);
::bloxide_tokio::root_task!(
    supervisor_task, ::bloxide_supervisor::supervisor::SupervisorSpec < TokioRuntime >
);
#[tokio::main]
async fn main() {
    tracing_log::LogTracer::init().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init()
        .ok();
    let timer_ref = ::bloxide_tokio::spawn_timer!(8);
    let ((ping_ref,), ping_mbox) = ::bloxide_tokio::channels! {
        ping_pong_messages::PingPongMsg(16),
    };
    let ping_id = ping_ref.id();
    let ((pong_ref,), pong_mbox) = ::bloxide_tokio::channels! {
        ping_pong_messages::PingPongMsg(16),
    };
    let pong_id = pong_ref.id();
    let ping_ctx = PingCtx::new(
        pong_ref.clone(),
        ping_ref.clone(),
        timer_ref.clone(),
        ping_id,
        PingBehavior::default(),
    );
    let pong_ctx = PongCtx::new(ping_ref.clone(), pong_id);
    let ping_machine = ::bloxide_core::StateMachine::new(ping_ctx);
    let pong_machine = ::bloxide_core::StateMachine::new(pong_ctx);
    let mut group = ChildGroupBuilder::new(GroupShutdown::WhenAnyDone);
    ::bloxide_tokio::spawn_child!(
        group, ping_task(ping_machine, ping_mbox, ping_id), ChildPolicy::Restart { max :
        1u32 as usize }
    );
    ::bloxide_tokio::spawn_child!(
        group, pong_task(pong_machine, pong_mbox, pong_id), ChildPolicy::Stop
    );
    let _sup_control_ref_0 = group.control_ref();
    let sup_notify_0 = group.notify_ref();
    let sup_id = ::bloxide_tokio::next_actor_id!();
    let (children, sup_notify_rx, sup_control_rx) = group.finish();
    let sup_ctx = ::bloxide_supervisor::supervisor::SupervisorCtx::new(
        children,
        sup_id,
        sup_notify_0,
    );
    let mut sup_machine = ::bloxide_core::StateMachine::<
        ::bloxide_supervisor::supervisor::SupervisorSpec<TokioRuntime>,
    >::new(sup_ctx);
    sup_machine
        .dispatch(
            ::bloxide_supervisor::event::SupervisorEvent::<
                TokioRuntime,
            >::Lifecycle(LifecycleCommand::Start),
        );
    supervisor_task(sup_machine, (sup_notify_rx, sup_control_rx)).await;
    println!("tokio-demo complete");
}
