// Copyright 2025 Bloxide, all rights reserved
use core::task::{Context, Poll};

// ── Mailboxes trait ───────────────────────────────────────────────────────────

/// A set of typed mailboxes that together produce a unified event stream.
///
/// `poll_next` returns:
/// - `Poll::Ready(Some(event))` when any stream has a message.
/// - `Poll::Ready(None)` when all streams have closed. This signals graceful
///   shutdown for the actor; callers should stop polling and return.
/// - `Poll::Pending` when no message is ready but at least one stream is still
///   open.
///
/// Implementations poll their constituent streams in **priority order**: the
/// first stream in the tuple is always polled first. When it has a message,
/// that message is returned immediately without checking later streams.
///
/// # Priority Convention
///
/// Place the highest-priority message type at index 0. For actors supervised
/// by the runtime, lifecycle commands (Start, Reset, Stop) flow through
/// `dispatch()` at the VirtualRoot level — they are intercepted before
/// reaching user-declared states. Order domain streams by descending urgency.
///
/// # Return Semantics
///
/// `poll_next` returns `Poll::Ready(None)` when every constituent stream has
/// returned `Poll::Ready(None)`. This is the normal end-of-stream signal and
/// lets the actor shut down gracefully. Individual streams may close early
/// (for example, if a peer drops its `ActorRef`); the first closed stream
/// causes `poll_next` to return `Poll::Ready(None)` immediately so the actor
/// can exit instead of hanging.
///
/// # Channel Lifetime
///
/// When a stream returns `Poll::Ready(None)` (channel closed), the blanket
/// tuple impls propagate it immediately as `Poll::Ready(None)` for the whole
/// mailbox set. This converts a closed channel into a graceful shutdown signal
/// rather than an actor hang. Callers that receive `Ready(None)` should stop
/// polling and exit.
///
/// # Blanket implementations
/// Generated by `bloxide-codegen` into `src/generated/mailboxes_impls.rs`
/// for 1- through 16-element tuples of `Stream`s where `E: From<stream::Item>`
/// for each element.
pub trait Mailboxes<E: Send + 'static>: Send + 'static + Unpin {
    fn poll_next(&mut self, cx: &mut Context<'_>) -> Poll<Option<E>>;
}

// ── NoMailboxes ───────────────────────────────────────────────────────────────

/// A mailbox set that never produces an event.
///
/// Use as `type Mailboxes<R: BloxRuntime> = NoMailboxes` for `MachineSpec`
/// implementations that are driven directly via `machine.dispatch(event)`
/// rather than through `run_actor` (e.g., in unit tests).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct NoMailboxes;

impl<E: Send + 'static> Mailboxes<E> for NoMailboxes {
    fn poll_next(&mut self, _cx: &mut Context<'_>) -> Poll<Option<E>> {
        Poll::Pending
    }
}

// ── Tuple blanket impls (1-16) ────────────────────────────────────────────────
//
// Generated by `bloxide-codegen` into `src/generated/mailboxes_impls.rs`.
// Each generated impl polls streams in priority order (index 0 first) and
// collects the first ready item. `Poll::Ready(None)` propagates as graceful shutdown.

// Tuple mailbox impls (1-16) are generated by bloxide-codegen in src/generated/mailboxes_impls.rs

#[cfg(all(test, feature = "std"))]
mod tests {
    use super::*;
    use core::pin::Pin;
    use futures_core::Stream;

    struct ClosedStream;
    impl Stream for ClosedStream {
        type Item = u32;
        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<u32>> {
            Poll::Ready(None)
        }
    }

    struct YieldThenClose {
        yielded: bool,
    }
    impl Stream for YieldThenClose {
        type Item = u32;
        fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<u32>> {
            if !self.yielded {
                self.get_mut().yielded = true;
                Poll::Ready(Some(42))
            } else {
                Poll::Ready(None)
            }
        }
    }

    #[derive(Debug, Clone, Copy)]
    struct TestEvent(u32);

    impl From<u32> for TestEvent {
        fn from(v: u32) -> Self {
            TestEvent(v)
        }
    }

    #[test]
    fn mailbox_close_returns_ready_none() {
        // A single closed stream → poll_next should return Ready(None) immediately.
        let mut mailboxes: (ClosedStream,) = (ClosedStream,);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result = <(ClosedStream,) as Mailboxes<TestEvent>>::poll_next(&mut mailboxes, &mut cx);
        assert!(
            matches!(result, Poll::Ready(None)),
            "closed stream must produce Ready(None), got {:?}",
            result
        );
    }

    #[test]
    fn mailbox_close_in_pair_returns_ready_none() {
        // When one stream in a tuple is closed, poll_next should return Ready(None).
        let mut mailboxes: (ClosedStream, ClosedStream) = (ClosedStream, ClosedStream);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result = <(ClosedStream, ClosedStream) as Mailboxes<TestEvent>>::poll_next(
            &mut mailboxes,
            &mut cx,
        );
        assert!(
            matches!(result, Poll::Ready(None)),
            "closed stream in pair must produce Ready(None), got {:?}",
            result
        );
    }

    #[test]
    fn mailbox_yields_item_then_closes() {
        // First poll returns Ready(Some(event)), second returns Ready(None).
        let mut mailboxes: (YieldThenClose,) = (YieldThenClose { yielded: false },);
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);

        let first = <(YieldThenClose,) as Mailboxes<TestEvent>>::poll_next(&mut mailboxes, &mut cx);
        assert!(
            matches!(first, Poll::Ready(Some(TestEvent(42)))),
            "first poll must yield the item, got {:?}",
            first
        );

        let second =
            <(YieldThenClose,) as Mailboxes<TestEvent>>::poll_next(&mut mailboxes, &mut cx);
        assert!(
            matches!(second, Poll::Ready(None)),
            "second poll after close must return Ready(None), got {:?}",
            second
        );
    }

    #[test]
    fn no_mailboxes_always_pending() {
        let mut mb = NoMailboxes;
        let waker = futures_task_waker();
        let mut cx = Context::from_waker(&waker);
        let result: Poll<Option<TestEvent>> = mb.poll_next(&mut cx);
        assert!(
            matches!(result, Poll::Pending),
            "NoMailboxes must always be Pending, got {:?}",
            result
        );
    }

    /// Create a no-op waker for polling in tests.
    fn futures_task_waker() -> std::task::Waker {
        use std::task::{RawWaker, RawWakerVTable, Waker};
        static VTABLE: RawWakerVTable = RawWakerVTable::new(
            |_| RawWaker::new(std::ptr::null(), &VTABLE),
            |_| {},
            |_| {},
            |_| {},
        );
        unsafe { Waker::from_raw(RawWaker::new(std::ptr::null(), &VTABLE)) }
    }
}
