// Copyright 2025 Bloxide, all rights reserved
use core::task::{Context, Poll};

// ── Mailboxes trait ───────────────────────────────────────────────────────────

/// A set of typed mailboxes that together produce a unified event stream.
///
/// Implementations poll their constituent streams in **priority order**: the
/// first stream in the tuple is always polled first. When it has a message,
/// that message is returned immediately without checking later streams.
///
/// # Priority Convention
///
/// Place the highest-priority message type at index 0. For actors supervised
/// by the runtime, lifecycle is managed externally via `machine.start()` and
/// `machine.reset()` — no lifecycle stream is needed in the domain mailboxes
/// tuple. Order domain streams by descending urgency.
///
/// # Channel Lifetime Invariant
///
/// Every actor **must retain a clone of its own sender** (`ActorRef`) for each
/// mailbox it owns. This guarantees that the underlying channel can never close
/// during normal operation — there is always at least one sender alive.
///
/// The blanket tuple impls below rely on this invariant: a stream returning
/// `Poll::Ready(None)` (channel closed) is treated as a violated invariant
/// and will trigger a `debug_assert!` in debug builds. In release builds the
/// closed stream is silently treated as empty (`Poll::Pending`).
///
/// Future runtimes with dynamically closeable channels must either:
/// - Uphold the self-sender invariant (retain a clone in `Ctx`), or
/// - Provide a custom `Mailboxes` impl that maps `Ready(None)` to a sentinel
///   `ChannelClosed` event variant.
///
/// # Blanket implementations
/// Generated by `bloxide_macros::mailboxes_impls!(16)` for 1- through 16-element
/// tuples of `Stream`s where `E: From<stream::Item>` for each element.
pub trait Mailboxes<E: Send + 'static>: Send + 'static + Unpin {
    fn poll_next(&mut self, cx: &mut Context<'_>) -> Poll<E>;
}

// ── NoMailboxes ───────────────────────────────────────────────────────────────

/// A mailbox set that never produces an event.
///
/// Use as `type Mailboxes<R: BloxRuntime> = NoMailboxes` for `MachineSpec`
/// implementations that are driven directly via `machine.dispatch(event)`
/// rather than through `run_actor` (e.g., in unit tests).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct NoMailboxes;

impl<E: Send + 'static> Mailboxes<E> for NoMailboxes {
    fn poll_next(&mut self, _cx: &mut Context<'_>) -> Poll<E> {
        Poll::Pending
    }
}

// ── Tuple blanket impls (1-16) ────────────────────────────────────────────────
//
// Generated by the `mailboxes_impls!(16)` proc macro from `bloxide-macros`.
// Each generated impl polls streams in priority order (index 0 first) and
// collects the first ready item. `Poll::Ready(None)` triggers a debug_assert.

bloxide_macros::mailboxes_impls!(16);
