// Copyright 2025 Bloxide, all rights reserved
use crate::capability::BloxRuntime;
use crate::event_tag::EventTag;
use crate::mailboxes::Mailboxes;
use crate::topology::StateTopology;
use crate::transition::StateRule;

/// Static handler table for a single state.
/// All function pointers are resolved at compile time.
pub struct StateFns<S: MachineSpec> {
    /// Called (in order) when entering this state during a transition. Infallible.
    /// Use `&[]` for no-op. Multiple actions are composed by listing them in the slice.
    pub on_entry: &'static [fn(&mut S::Ctx)],
    /// Called (in order) when exiting this state during a transition. Infallible.
    /// Use `&[]` for no-op. Multiple actions are composed by listing them in the slice.
    pub on_exit: &'static [fn(&mut S::Ctx)],
    /// Ordered transition rules. The engine evaluates these in declaration
    /// order; the first matching rule wins. If no rule matches, the event
    /// bubbles implicitly to the parent state.
    pub transitions: &'static [StateRule<S>],
}

/// The core trait every state machine must implement.
///
/// Implementations provide the state topology, initial state, and handler tables.
/// All of these are pure, stateless functions — no runtime-specific imports allowed.
///
/// # Engine-implicit Init and Root
///
/// Neither `Root` nor `Init` appear in the user's `State` enum:
///
/// - **Root** is engine-implicit. Top-level user states return `None` from
///   `StateTopology::parent()`. The engine prepends a virtual root when building
///   state paths for LCA computation — it is never entered or exited.
///
/// - **Init** is engine-implicit. The engine calls `on_init_entry` only
///   after a `Reset` (Terminate) — **not** at initial construction. It calls
///   `on_init_exit` when `is_start` returns `true` for an incoming event.
///   All events received while in Init that do not satisfy `is_start` are
///   silently dropped.
pub trait MachineSpec: Sized + 'static {
    /// State identifiers. MUST implement `StateTopology`.
    ///
    /// Use `#[derive(StateTopology)]` with `#[repr(u8)]` on the state enum.
    /// Do NOT include a `Root` or `Init` variant — both are engine-managed.
    type State: StateTopology;

    /// Event type. Must implement `EventTag` for fast dispatch pre-filtering.
    ///
    /// Use `#[blox_event]` on the event enum to auto-generate `EventTag`,
    /// `From<Envelope<M>>` impls, and payload accessor methods.
    type Event: EventTag + Send + 'static;

    /// The actor's mutable context, owned by the `StateMachine`.
    ///
    /// Intentionally does **not** require `Send`. Contexts may hold synchronous
    /// peripheral state (e.g. GPIO handles) that is not `Send`. Runtimes that
    /// move machines across execution contexts should add `Send` bounds at the
    /// runtime level; blox authors targeting such runtimes add `Send` to their
    /// own `Ctx` type.
    type Ctx: 'static;

    /// The set of typed mailbox streams for this actor, parameterized over the
    /// runtime `R`. Domain message streams for this actor. Index 0 has highest
    /// poll priority.
    ///
    /// Use `NoMailboxes` when driving the machine directly via `dispatch()`
    /// (e.g., in unit tests).
    type Mailboxes<R: BloxRuntime>: Mailboxes<Self::Event>;

    /// Compile-time handler table indexed by `state.as_index()`.
    ///
    /// Declare entries in the same order as the state enum variants so that
    /// `state.as_index()` correctly indexes into this slice. Use the helper
    /// macro generated by `#[handler_fns(...)]` on the state enum to guarantee
    /// alignment automatically:
    ///
    /// ```ignore
    /// // Doc test ignored: imports not resolvable in rustdoc compilation context
    /// // On the state enum:
    /// #[derive(StateTopology)]
    /// #[repr(u8)]
    /// #[handler_fns(OPERATING_FNS, ACTIVE_FNS, PAUSED_FNS, DONE_FNS)]
    /// pub enum PingState { Operating, Active, Paused, Done }
    ///
    /// // In MachineSpec impl:
    /// const HANDLER_TABLE: &'static [&'static StateFns<Self>] =
    ///     ping_state_handler_table!(Self);
    /// ```
    const HANDLER_TABLE: &'static [&'static StateFns<Self>];

    /// The first operational leaf state entered after the actor leaves Init
    /// (i.e., after `is_start` returns `true`). MUST return a leaf state.
    fn initial_state() -> Self::State;

    /// Called when the machine re-enters engine-implicit Init after a Reset.
    /// This fires both when the runtime calls `machine.reset()` (e.g. on
    /// Terminate) and when a state-level guard returns `Guard::Reset`.
    ///
    /// The engine guarantees the full LCA exit chain (on_exit for every state
    /// from leaf to topmost ancestor) fires before this method is called.
    ///
    /// **NOT called at initial construction** — construction is silent.
    fn on_init_entry(ctx: &mut Self::Ctx);

    /// Called when leaving engine-implicit Init: when `is_start` returns `true`.
    ///
    /// The default implementation is a no-op. Override only when you need to
    /// perform work specifically on the transition out of Init.
    fn on_init_exit(_ctx: &mut Self::Ctx) {}

    /// Returns `true` if `event` is the signal that should transition the actor
    /// out of Init into its first operational state (`initial_state()`).
    ///
    /// This is part of the core dispatch path — `dispatch()` checks `is_start`
    /// to detect a start event and enter the initial operational state. The
    /// runtime bypasses `is_start` by calling `machine.start()` directly;
    /// `is_start` is for cases where the start signal arrives as a domain event
    /// through `dispatch()`.
    ///
    /// Default: returns `false`. Override whenever the start signal is delivered
    /// via `dispatch()` rather than by calling `start()` directly.
    fn is_start(_event: &Self::Event) -> bool {
        false
    }

    /// Returns `true` if `state` is a terminal state — one from which the
    /// actor will not transition to another operational state under normal
    /// circumstances.
    ///
    /// The runtime checks this after DispatchOutcome::Transition(s) and
    /// DispatchOutcome::Started(s) to generate ChildLifecycleEvent::Done for
    /// the supervisor.
    ///
    /// Default: `false`. Override in specs that have terminal states.
    fn is_terminal(_state: &Self::State) -> bool {
        false
    }

    /// Returns `true` if `state` represents a failure condition.
    ///
    /// The runtime checks this after DispatchOutcome::Transition(s) and
    /// DispatchOutcome::Started(s) to generate ChildLifecycleEvent::Failed
    /// for the supervisor. `is_error` takes precedence over `is_terminal` —
    /// if both return true for the same state, only `Failed` is reported.
    ///
    /// Default: `false`. Override in specs that have error/fault states.
    fn is_error(_state: &Self::State) -> bool {
        false
    }

    /// Root-level transition rules. Evaluated when an event bubbles past all
    /// user-declared ancestor states. Rules are evaluated in declaration order;
    /// first match wins. If no rule matches, the event is silently dropped.
    fn root_transitions() -> &'static [StateRule<Self>] {
        &[]
    }
}
