# Copyright 2025 Bloxide, all rights reserved
[package]
name = "wibble-impl"
version.workspace = true
edition.workspace = true
description = "Concrete action implementations for wibble"
publish = false

[dependencies]
bloxide-core = { workspace = true }
wibble-blox = { workspace = true }
wibble-messages = { workspace = true }
