// Copyright 2025 Bloxide, all rights reserved
//! Generate code from all blox.toml files in the workspace.

use std::path::{Path, PathBuf};
use walkdir::WalkDir;

pub fn generate(workspace: Option<PathBuf>) -> anyhow::Result<()> {
    let root = workspace.unwrap_or_else(|| {
        let manifest_dir =
            PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string()));
        find_workspace_root(&manifest_dir).unwrap_or(manifest_dir)
    });

    let mut count = 0;
    for entry in WalkDir::new(&root)
        .max_depth(4)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_name() == "blox.toml")
    {
        let toml_path = entry.path();
        let crate_dir = toml_path.parent().unwrap();
        let src_dir = crate_dir.join("src");
        let generated_dir = src_dir.join("generated");

        std::fs::create_dir_all(&generated_dir)?;

        let files = match bloxide_codegen::generate_from_toml(toml_path) {
            Ok(files) => files,
            Err(e) => {
                eprintln!(
                    "bloxide: warning: failed to generate for {}: {}",
                    toml_path.display(),
                    e
                );
                continue;
            }
        };
        for (filename, content) in &files {
            let path = generated_dir.join(filename);

            // Only write if changed (preserves mtime for caching)
            let needs_write = if path.exists() {
                std::fs::read_to_string(&path)? != *content
            } else {
                true
            };

            if needs_write {
                std::fs::write(&path, content)?;
                println!("bloxide: generated {}", path.display());
            }
        }

        // Ensure lib.rs includes the generated module
        ensure_generated_mod(&src_dir, &files)?;
        count += 1;
    }

    println!("bloxide: processed {} blox.toml files", count);

    // Format generated files so that `cargo fmt -- --check` passes.
    let status = std::process::Command::new("cargo")
        .args(["fmt"])
        .current_dir(&root)
        .status();
    if let Err(e) = status {
        eprintln!("bloxide: warning: failed to run cargo fmt: {}", e);
    }

    Ok(())
}

fn find_workspace_root(start: &Path) -> Option<PathBuf> {
    let mut current = start;
    loop {
        let cargo_toml = current.join("Cargo.toml");
        if cargo_toml.exists() {
            if let Ok(content) = std::fs::read_to_string(&cargo_toml) {
                if content.contains("[workspace]") {
                    return Some(current.to_path_buf());
                }
            }
        }
        match current.parent() {
            Some(parent) => current = parent,
            None => return None,
        }
    }
}

fn ensure_generated_mod(
    src_dir: &Path,
    generated_files: &[(String, String)],
) -> anyhow::Result<()> {
    let lib_rs = src_dir.join("lib.rs");
    let mod_line = "pub mod generated;\n";

    if lib_rs.exists() {
        let content = std::fs::read_to_string(&lib_rs)?;
        if !content.contains("mod generated") {
            std::fs::write(&lib_rs, format!("{}\n{}", mod_line, content))?;
        }
    }

    // Write generated/mod.rs with pub mod declarations for each generated file.
    // Preserve existing .rs files in the directory that are no longer emitted by
    // the current generator (e.g. hand-written or stale generated modules).
    let generated_mod = src_dir.join("generated").join("mod.rs");
    let mut mod_names: Vec<String> = generated_files
        .iter()
        .filter_map(|(filename, _)| {
            if filename.ends_with(".rs") && filename != "mod.rs" {
                Some(filename.trim_end_matches(".rs").to_string())
            } else {
                None
            }
        })
        .collect();
    if generated_mod.parent().unwrap().exists() {
        for entry in std::fs::read_dir(generated_mod.parent().unwrap())? {
            let entry = entry?;
            let path = entry.path();
            if path.is_file() {
                if let Some(name) = path.file_stem().and_then(|s| s.to_str()) {
                    let filename = format!("{}.rs", name);
                    if filename != "mod.rs" && !mod_names.iter().any(|n| n == name) {
                        mod_names.push(name.to_string());
                    }
                }
            }
        }
    }

    let mut mod_content = String::from(
        "// Copyright 2025 Bloxide, all rights reserved\n// Auto-generated module.\n// Files in this directory are generated by bloxide-codegen.\n",
    );
    for mod_name in mod_names {
        // topology module exports a #[macro_export] handler_table macro
        if mod_name == "topology" {
            mod_content.push_str("#[macro_use]\n");
        }
        mod_content.push_str(&format!("pub mod {};\n", mod_name));
        mod_content.push_str(&format!(
            "#[allow(unused_imports)]\npub use {}::*;\n",
            mod_name
        ));
    }
    std::fs::write(&generated_mod, mod_content)?;

    Ok(())
}
