// Copyright 2025 Bloxide, all rights reserved
//! Generate code from all blox.toml files in the workspace.

use std::path::{Path, PathBuf};
use walkdir::WalkDir;

pub fn generate(workspace: Option<PathBuf>) -> anyhow::Result<()> {
    let root = workspace.unwrap_or_else(|| {
        let manifest_dir =
            PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string()));
        find_workspace_root(&manifest_dir).unwrap_or(manifest_dir)
    });

    let mut count = 0;
    for entry in WalkDir::new(&root)
        .max_depth(4)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_name() == "blox.toml")
    {
        let toml_path = entry.path();
        let crate_dir = toml_path.parent().unwrap();
        let src_dir = crate_dir.join("src");
        let generated_dir = src_dir.join("generated");

        std::fs::create_dir_all(&generated_dir)?;

        let files = match bloxide_codegen::generate_from_toml(toml_path) {
            Ok(files) => files,
            Err(e) => {
                eprintln!(
                    "bloxide: warning: failed to generate for {}: {}",
                    toml_path.display(),
                    e
                );
                continue;
            }
        };
        for (filename, content) in files {
            let path = generated_dir.join(&filename);

            // Only write if changed (preserves mtime for caching)
            let needs_write = if path.exists() {
                std::fs::read_to_string(&path)? != content
            } else {
                true
            };

            if needs_write {
                std::fs::write(&path, content)?;
                println!("bloxide: generated {}", path.display());
            }
        }

        // Ensure lib.rs includes the generated module
        ensure_generated_mod(&src_dir)?;
        count += 1;
    }

    println!("bloxide: processed {} blox.toml files", count);
    Ok(())
}

fn find_workspace_root(start: &Path) -> Option<PathBuf> {
    let mut current = start;
    loop {
        let cargo_toml = current.join("Cargo.toml");
        if cargo_toml.exists() {
            if let Ok(content) = std::fs::read_to_string(&cargo_toml) {
                if content.contains("[workspace]") {
                    return Some(current.to_path_buf());
                }
            }
        }
        match current.parent() {
            Some(parent) => current = parent,
            None => return None,
        }
    }
}

fn ensure_generated_mod(src_dir: &Path) -> anyhow::Result<()> {
    let lib_rs = src_dir.join("lib.rs");
    let mod_line = "pub mod generated;\n";

    if lib_rs.exists() {
        let content = std::fs::read_to_string(&lib_rs)?;
        if !content.contains("mod generated") {
            std::fs::write(&lib_rs, format!("{}\n{}", mod_line, content))?;
        }
    }

    // Create generated/mod.rs if not exists
    let generated_mod = src_dir.join("generated").join("mod.rs");
    if !generated_mod.exists() {
        let mod_content =
            "// Auto-generated module.\n// Files in this directory are generated by bloxide-codegen.\n";
        std::fs::write(&generated_mod, mod_content)?;
    }

    Ok(())
}
