// Copyright 2025 Bloxide, all rights reserved
//! Scaffold a new blox following the five-layer pattern.

use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::utils::{
    generate_spec_md, to_camel_case, update_workspace_cargo_toml, WorkspaceAddition,
};

pub fn new_blox(name: &str, messages: Option<&str>, actions: Option<&str>) -> Result<()> {
    let name_snake = name.to_lowercase().replace("-", "_");
    let name_camel = to_camel_case(name);

    let spec_dir = Path::new("spec/bloxes");
    fs::create_dir_all(spec_dir)?;
    let spec_path = spec_dir.join(format!("{}.md", name_snake));
    fs::write(&spec_path, generate_spec_md(&name_snake, &name_camel))?;
    println!("Created: {}", spec_path.display());

    create_blox_crate(&name_snake, &name_camel, messages, actions)?;

    let member_path = format!("crates/bloxes/{}", name_snake);
    let dep_name = format!("{}-blox", name_snake);
    let dep_toml_line = format!(
        r#"{} = {{ path = "crates/bloxes/{}" }}"#,
        dep_name, name_snake
    );
    update_workspace_cargo_toml(&[
        WorkspaceAddition::Member(member_path),
        WorkspaceAddition::Dependency {
            name: dep_name,
            toml_line: dep_toml_line,
        },
    ])?;

    println!("\nScaffolded new blox '{}'", name);
    println!("Next steps:");
    println!(
        "  1. Edit spec/bloxes/{}.md to define states and transitions",
        name_snake
    );
    println!(
        "  2. Edit crates/bloxes/{}/src/actions.rs to define action functions",
        name_snake
    );
    println!("  3. Run `cargo blox generate` to generate boilerplate");

    Ok(())
}

pub fn create_blox_crate(
    name_snake: &str,
    name_camel: &str,
    messages: Option<&str>,
    actions: Option<&str>,
) -> Result<()> {
    let crate_dir = Path::new("crates/bloxes").join(name_snake);
    let src_dir = crate_dir.join("src");
    let gen_dir = src_dir.join("generated");
    fs::create_dir_all(&gen_dir)?;

    let mut deps = String::from(
        r#"bloxide-core = { workspace = true, features = ["alloc"] }
bloxide-macros = { workspace = true }
"#,
    );
    if let Some(msg) = messages {
        deps.push_str(&format!("{} = {{ workspace = true }}\n", msg));
    }
    if let Some(act) = actions {
        deps.push_str(&format!("{} = {{ workspace = true }}\n", act));
    }

    let cargo_toml = format!(
        r#"# Copyright 2025 Bloxide, all rights reserved
[package]
name = "{name_snake}-blox"
version.workspace = true
edition.workspace = true
description = "{name_camel} actor blox — runtime-agnostic"
repository.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["bloxide-core/std"]

[dependencies]
{deps}"#
    );
    fs::write(crate_dir.join("Cargo.toml"), cargo_toml)?;

    let mut blox_toml = format!(
        r#"[actor]
name = "{name_camel}"

[event]
name = "{name_camel}Event"
"#
    );

    // If messages crate provided, auto-add a mailbox
    if let Some(msg_crate) = messages {
        let msg_type = to_camel_case(msg_crate.trim_end_matches("-messages")) + "Msg";
        let msg_module = msg_crate.replace("-", "_");
        blox_toml.push_str(&format!(
            r#"
[[event.mailboxes]]
variant = "Msg"
message = "{msg_type}"
message_path = "{msg_module}::{msg_type}"
"#
        ));
    }

    // Auto-generate a minimal [context] section
    let mut context_toml = format!(
        r#"
[context]
name = "{name_camel}Ctx"
"#
    );

    // If actions crate provided, add a behavior field with placeholder delegate
    if let Some(_act_crate) = actions {
        context_toml.push_str(
            r#"generics = "<B: CountsTicks>"
"#,
        );
        context_toml.push_str(
            r#"
[[context.fields]]
name = "self_id"
ty = "ActorId"
"#,
        );
        context_toml.push_str(
            r#"
[[context.fields]]
name = "behavior"
ty = "B"
delegates = ["CountsTicks"]
"#,
        );
    } else {
        context_toml.push_str(
            r#"
[[context.fields]]
name = "self_id"
ty = "ActorId"
"#,
        );
    }

    blox_toml.push_str(&context_toml);

    blox_toml.push_str(
        r#"
[topology]
handler_fns = []
"#,
    );

    fs::write(crate_dir.join("blox.toml"), blox_toml)?;

    let lib_rs = r#"// Copyright 2025 Bloxide, all rights reserved
#![no_std]

#[cfg(feature = "std")]
extern crate std;

pub mod generated;
pub mod actions;
pub mod prelude;

#[cfg(all(test, feature = "std"))]
mod tests;

pub use generated::*;
"#;
    fs::write(src_dir.join("lib.rs"), lib_rs)?;

    let actions_rs = format!(
        r#"// Copyright 2025 Bloxide, all rights reserved
//! Action functions and transition rules for {name_camel}.
//! This file is NOT regenerated by `cargo blox generate`.
//! Add your action functions and StateFns constants here.

// use crate::prelude::*;
// TODO: Add imports for your action crate traits and message types

// impl<R: BloxRuntime> {name_camel}Spec<R> {{
//     // Add action functions here
// }}

// impl<R: BloxRuntime> {name_camel}Spec<R> {{
//     // Add StateFns constants here
// }}
"#
    );
    fs::write(src_dir.join("actions.rs"), actions_rs)?;

    let prelude_rs = format!(
        r#"// Copyright 2025 Bloxide, all rights reserved
pub use crate::{{{name_camel}Ctx, {name_camel}Event, {name_camel}Spec, {name_camel}State}};
"#
    );
    fs::write(src_dir.join("prelude.rs"), prelude_rs)?;

    let tests_rs = format!(
        r#"// Copyright 2025 Bloxide, all rights reserved
//! Unit tests for the {name_snake} blox.
"#
    );
    fs::write(src_dir.join("tests.rs"), tests_rs)?;

    let gen_mod_rs =
        "// Auto-generated module.\n// Files in this directory are generated by bloxide-codegen.\n";
    fs::write(gen_dir.join("mod.rs"), gen_mod_rs)?;

    println!("Created: {}", crate_dir.display());
    Ok(())
}
